// ── QUANT MOO — vite-plugin-electron-ipc ─────────────────────────────────
// Auto-generates preload API types from IPC handler modules
// T51: Round 15 P0 — production plugin

import type { Plugin, ResolvedConfig } from 'vite';
import fs from 'fs';
import path from 'path';
import log from 'electron-log';

interface IpcHandler {
  channel: string;
  domain: string;
  file: string;
  line: number;
}

function scanIPCModules(ipcDir: string): IpcHandler[] {
  const handlers: IpcHandler[] = [];
  if (!fs.existsSync(ipcDir)) return handlers;
  
  const files = fs.readdirSync(ipcDir).filter(f => f.endsWith('-ipc.ts'));
  for (const file of files) {
    const content = fs.readFileSync(path.join(ipcDir, file), 'utf8');
    const lines = content.split('\n');
    for (let i = 0; i < lines.length; i++) {
      const m = lines[i].match(/ipcMain\.handle\(['"]([^'"]+)['"]/);
      if (m) {
        const domain = m[1].split(':')[0];
        handlers.push({ channel: m[1], domain, file, line: i + 1 });
      }
    }
  }
  return handlers;
}

function generatePreloadTypes(handlers: IpcHandler[]): string {
  const domains = new Map<string, string[]>();
  for (const h of handlers) {
    if (!domains.has(h.domain)) domains.set(h.domain, []);
    domains.get(h.domain)!.push(h.channel);
  }
  
  let out = `// Auto-generated by vite-plugin-electron-ipc\n`;
  out += `// ${handlers.length} IPC handlers from ${new Set(handlers.map(h => h.file)).size} modules\n\n`;
  out += `export interface ElectronAPI {\n`;
  for (const [domain, channels] of domains) {
    out += `  ${domain}: {\n`;
    for (const ch of channels) {
      const method = ch.split(':').slice(1).join(':').replace(/-/g, '_');
      out += `    ${method}(...args: unknown[]): Promise<any>;\n`;
    }
    out += `  };\n`;
  }
  out += `}\n\n`;
  out += `declare global {\n`;
  out += `  interface Window {\n`;
  out += `    api: ElectronAPI;\n`;
  out += `    electron: { ipcRenderer: any };\n`;
  out += `  }\n`;
  out += `}\n`;
  return out;
}

function generateBridgeAPI(handlers: IpcHandler[]): string {
  let out = `// Auto-generated by vite-plugin-electron-ipc\n`;
  out += `// Bridge API for renderer process\n\n`;
  out += `const ipc = window.electron?.ipcRenderer;\n\n`;
  
  const domains = new Map<string, string[]>();
  for (const h of handlers) {
    if (!domains.has(h.domain)) domains.set(h.domain, []);
    domains.get(h.domain)!.push(h.channel);
  }
  
  for (const [domain, channels] of domains) {
    out += `// ── ${domain} ──\n`;
    for (const ch of channels) {
      const method = ch.split(':').slice(1).join(':').replace(/-/g, '_');
      out += `export async function ${domain}_${method}(...args: unknown[]): Promise<any> {\n`;
      out += `  if (!ipc) return { success: false, error: 'IPC not available' };\n`;
      out += `  return ipc.invoke('${ch}', ...args);\n`;
      out += `}\n\n`;
    }
  }
  return out;
}

export function electronIPCPlugin(options?: { outputDir?: string }): Plugin {
  let config: ResolvedConfig;
  const outDir = options?.outputDir || 'src/generated';
  
  return {
    name: 'vite-plugin-electron-ipc',
    enforce: 'pre',
    
    configResolved(resolvedConfig) {
      config = resolvedConfig;
    },
    
    buildStart() {
      const ipcDir = path.resolve(config.root, 'electron/ipc');
      const handlers = scanIPCModules(ipcDir);
      
      const types = generatePreloadTypes(handlers);
      const bridge = generateBridgeAPI(handlers);
      
      const genDir = path.resolve(config.root, outDir);
      if (!fs.existsSync(genDir)) fs.mkdirSync(genDir, { recursive: true });
      
      fs.writeFileSync(path.join(genDir, 'electron-api.d.ts'), types);
      fs.writeFileSync(path.join(genDir, 'bridge-api.gen.ts'), bridge);
      
      log.info(`[vite-plugin-electron-ipc] Generated ${handlers.length} IPC handlers`);
      log.info(`  -> ${path.join(outDir, 'electron-api.d.ts')}`);
      log.info(`  -> ${path.join(outDir, 'bridge-api.gen.ts')}`);
    },
  };
}

export default electronIPCPlugin;
