// ══ R277 QClaw Task 1: 84全球因子+12宏观文案 (6h) ══
// 交付: src/lib/market/global-84plus12-factor-copy-r277.ts
//
// 14市場×6因子大类=84国别因子 + 12宏观因子
// 设计原则:
//   1. 同大类跨市场可比较——PE=低/中/高分位统一但基准各异
//   2. 每个市场有本土特色备注（鬼子用"割安"、印度用"FII"等本土地道表述）
//   3. 宏观因子有明确的好坏阈值和历史分位
//   4. 可操作: 读完知道「现在买这个市场是便宜还是贵」

export const GLOBAL_84_PLUS_12_FACTOR_COPY = {

  // ══════════════════════════════════════════════════════
  // PART A: 84国别因子 (14市场 × 6大类)
  // ══════════════════════════════════════════════════════

  // ── 因子大类模板（跨市场共用定义） ──
  categories: {
    valuation: {
      title: "估值",
      titleEn: "Valuation",
      emoji: "💰",
      question: "这市场贵不贵？",
      universalDontTrust: "低PE≠一定涨。日本1990年代PE跌到10倍以下后继续跌了十年——便宜可以变得更便宜。PE分位告诉你「相对历史便宜」，不是「马上要涨」。",
    },
    momentum: {
      title: "动量",
      titleEn: "Momentum",
      emoji: "🚀",
      question: "趋势往哪走？",
      universalDontTrust: "动量是双刃剑——上涨趋势里买赚钱的概率高，但反转时亏最快。永远不要只看动量不看估值。动量+低估值=最优组合。",
    },
    foreignFlow: {
      title: "外资流",
      titleEn: "Foreign Flow",
      emoji: "🌏",
      question: "外资在买还是卖？",
      universalDontTrust: "外资单日/单周数据波动大。连续4周的趋势才值得看。偶尔一天的大额流出可能是ETF调仓，不要恐慌。",
    },
    risk: {
      title: "风险",
      titleEn: "Risk",
      emoji: "⚠️",
      question: "现在安全吗？",
      universalDontTrust: "VIX/波动率是滞后指标——它在恐慌发生后飙升，不是提前预警。低VIX≠安全，很多时候大跌前VIX最低。",
    },
    macro: {
      title: "宏观",
      titleEn: "Macro",
      emoji: "📊",
      question: "经济引擎转得怎么样？",
      universalDontTrust: "宏观数据有滞后——GDP是你妈昨天才知道的事。股市领先经济6-12个月。PMI/领先指标比GDP更及时。",
    },
    breadth: {
      title: "广度",
      titleEn: "Breadth",
      emoji: "🌡️",
      question: "涨是全市场涨还是只几只大股？",
      universalDontTrust: "市场宽度低但指数还涨=假强势。A股2015、美股2023都是少数大股拉指数掩护资金撤退。看指数时一定看宽度。",
    },
  },

  // ── 14 市场×每个市场6因子 ──
  markets: {
    // ═══ 日本 🇯🇵 ═══
    JP: {
      country: "日本",
      countryEn: "Japan",
      flag: "🇯🇵",
      indexName: "日経225",
      valuation: {
        id: "JP_VALUATION",
        name: "日本估值分位",
        nameEn: "JP Valuation Percentile",
        emoji: "💰",
        oneliner: "日経225的PE/PB相对近10年处于什么位置——日本的便宜是真便宜吗",
        description: "PE约15倍=全球最低之一。但日本低PE已经持续30年了——不能简单说便宜。看PE分位比看绝对值有意义。",
        ranges: [
          { condition: "PE分位<20%", meaning: "相对历史低估——但别期待立刻反转。日本可以便宜很多年", color: "yellow" },
          { condition: "PE分位20-40%", meaning: "偏低——按历史标准便宜。适合定投式分批建仓", color: "green" },
          { condition: "PE分位40-60%", meaning: "合理", color: "neutral" },
          { condition: "PE分位60-80%", meaning: "偏贵——日元贬值会扭曲估值，注意汇率调整后PE", color: "yellow" },
          { condition: "PE分位>80%", meaning: "贵——历史上PE>20倍时后续回报很差", color: "red" },
        ],
        localNote: "日本株の「割安」は30年来の罠。PEだけ見ずに、PBR<1銘柄の比率も見よ。",
        dontTrust: "巴菲特大买日本商社≠日本股市便宜——巴菲特买的是商社的全球大宗商品业务，不是赌日本经济复苏。日経PE低是因为成分股里银行和重工占比高。",
      },
      momentum: {
        id: "JP_MOMENTUM",
        name: "日本动量/趋势",
        nameEn: "JP Momentum",
        emoji: "🚀",
        oneliner: "日経最近涨跌的势头——日元贬值期=日本股市蜜月期",
        description: "3M/6M回报+相对MSCI World的超额收益。日元贬值>10%时日本出口股大涨。日元升值=日本股市天敌。",
        ranges: [
          { condition: "3M>10%+日元贬值", meaning: "出口驱动牛市——日元贬值+股市涨=经典日本模式", color: "green" },
          { condition: "3M>0%", meaning: "正动量", color: "green" },
          { condition: "3M 0~-5%", meaning: "回调——可能是买入机会（如果是日元升值导致则警惕）", color: "yellow" },
          { condition: "3M<-10%", meaning: "深度回调——大概率与日元急剧升值同步", color: "red" },
        ],
        localNote: "為替相場あっての日本株。円安の時だけ日本株は世界をアウトパフォームする。",
        dontTrust: "日元贬值推高的日本股市涨幅——对美元投资者是虚的。如果你用美元计价，日経涨15%+日元贬10%=实际只赚5%。",
      },
      foreignFlow: {
        id: "JP_FOREIGN_FLOW",
        name: "日本外资流",
        nameEn: "JP Foreign Flow",
        emoji: "🌏",
        oneliner: "外国人投资家在买日本股票吗——日本70%的成交量是外国人做的",
        description: "東証公布的海外投资者买卖额（週次データ）。外国人连续买入+日元贬值=最理想的组合。外国人抛售=日股大跌。",
        ranges: [
          { condition: "连续4周净买入>5000亿円", meaning: "外资强烈看好——日股最大的买方在行动", color: "green" },
          { condition: "连续净买入", meaning: "外资温和看多", color: "green" },
          { condition: "买卖交替", meaning: "方向不明", color: "neutral" },
          { condition: "连续净卖出", meaning: "外资撤退——警惕", color: "yellow" },
          { condition: "单周净卖出>1兆円", meaning: "外资恐慌出逃——可能触发踩踏", color: "red" },
        ],
        localNote: "外人さん（外国人投資家）が日本株の7割を動かす。外人の動きを見ずに日本株は語れない。",
      },
      risk: {
        id: "JP_RISK",
        name: "日本风险",
        nameEn: "JP Risk",
        emoji: "⚠️",
        oneliner: "日経VI+日元波动率+日本CDS——日本市场的三个温度计",
        description: "日経平均VI（Nikkei 225 VI）>30=恐慌峰值。同时关注JPY波动率——日元剧烈波动时日本股市必然动荡。",
        ranges: [
          { condition: "N225 VI<20", meaning: "平静——但过于平静可能是暴风雨前", color: "neutral" },
          { condition: "N225 VI 20-25", meaning: "正常波动", color: "neutral" },
          { condition: "N225 VI 25-30", meaning: "紧张——回调风险上升", color: "yellow" },
          { condition: "N225 VI>30", meaning: "恐慌——巴菲特名言适用：'别人恐惧我贪婪——但要等VIX开始回落'", color: "red" },
        ],
        localNote: "日経VI>30は買い場のサイン。ただしVIXがピークアウトしてから仕込むべし。",
        dontTrust: "日本央行买ETF时会压低波动率——VI低迷可能只是央行在托市，不代表真安全。",
      },
      macro: {
        id: "JP_MACRO",
        name: "日本宏观",
        nameEn: "JP Macro",
        emoji: "📊",
        oneliner: "日本央行+GDP+通胀——日本市场的三体问题",
        description: "日銀短観(企业信心)>0=景气扩张。核心CPI>2%=BOJ可能退出宽松=日元走强=日股承压。日银政策转向=日本市场最大的变量。",
        ranges: [
          { condition: "短観>10+核心CPI<2%", meaning: "金发女孩——经济好但不需要加息。日股最佳环境", color: "green" },
          { condition: "短観>0", meaning: "景气温和扩张——正常", color: "neutral" },
          { condition: "短観<0", meaning: "景气收缩——警惕。BOJ可能加大宽松", color: "yellow" },
          { condition: "核心CPI>3%+BOJ鹰派", meaning: "BOJ被迫加息——日元跳涨+日股暴跌风险", color: "red" },
        ],
        localNote: "日銀が動けば全てが動く。YCC（イールドカーブ・コントロール）の微調整すら株と為替の大波乱を起こす。",
      },
      breadth: {
        id: "JP_BREADTH",
        name: "日本市场广度",
        nameEn: "JP Market Breadth",
        emoji: "🌡️",
        oneliner: "涨跌是日本全市场还是只几只出口大股——牛市的质量检查",
        description: "东证一部涨跌比+%股票在25日线上方。>60%=健康牛市。TOPIX比日経225更反映市场真实广度（TOPIX含2000+只）。",
        ranges: [
          { condition: "涨跌比>2+宽度>70%", meaning: "全面牛市——信号最强", color: "green" },
          { condition: "涨跌比1.5-2", meaning: "偏强——正常", color: "green" },
          { condition: "涨跌比1-1.5", meaning: "中性", color: "neutral" },
          { condition: "涨跌比<1+宽度<40%", meaning: "弱势——即使日経不跌也是假稳", color: "red" },
        ],
        localNote: "日経だけ見るな。TOPIXのほうが正直だ。日経225は値がさ株の動きに引っ張られすぎる。",
      },
    },

    // ═══ 印度 🇮🇳 ═══
    IN: {
      country: "印度",
      countryEn: "India",
      flag: "🇮🇳",
      indexName: "Nifty 50",
      valuation: {
        id: "IN_VALUATION",
        name: "印度估值分位",
        nameEn: "IN Valuation Percentile",
        emoji: "💰",
        oneliner: "Nifty PE处于几年分位——印度永远是全球最贵，关键是「比平时贵了多少」",
        description: "印度PE常年20-25倍——因为GDP增速高（6-7%），市场天然给溢价。关键是看PE偏离历史均值的幅度。",
        ranges: [
          { condition: "PE<18", meaning: "极度便宜——通常是卢比崩盘或政治危机导致，是买入机会", color: "green" },
          { condition: "PE 18-22", meaning: "相对便宜——印度标准下的便宜", color: "green" },
          { condition: "PE 22-26", meaning: "正常——印度常态就是贵", color: "neutral" },
          { condition: "PE>26", meaning: "贵——印度PE>26时未来1年回报通常不如定期存款", color: "red" },
        ],
        localNote: "India is always 'expensive'. Don't compare its PE to China or Japan — compare it to India's own history.",
        dontTrust: "Nifty PE被金融股拉低——剔除银行和Reliance后PE在30+。看板块PE比看整体PE更有意义。印度中小盘PE远超大盘。",
      },
      momentum: {
        id: "IN_MOMENTUM",
        name: "印度动量",
        nameEn: "IN Momentum",
        emoji: "🚀",
        oneliner: "Nifty的涨势——印度是动量因子最强的市场之一",
        description: "印度市场趋势持续性远超其他新兴市场。3月动量>10%大概率继续。卢比趋势和Nifty趋势高度相关——卢比稳定/升值时外资涌入。",
        ranges: [
          { condition: "3M>15%+FII流入", meaning: "资金驱动牛市——印度最强做多信号", color: "green" },
          { condition: "3M>0%", meaning: "正动量——顺势", color: "green" },
          { condition: "3M -5%~0%", meaning: "横盘或微跌——观望", color: "neutral" },
          { condition: "3M<-10%+FII流出", meaning: "外资撤退+卢比贬值——典型危机模式", color: "red" },
        ],
        localNote: "FIIs are the elephants that move the Nifty. When FIIs buy, the market goes up. When FIIs sell, even the best stocks fall.",
      },
      foreignFlow: {
        id: "IN_FOREIGN_FLOW",
        name: "印度FII/DII流",
        nameEn: "IN FII/DII Flow",
        emoji: "🌏",
        oneliner: "外国机构投资者(FII) vs 国内机构(DII)——两个大象在角力",
        description: "FII净买入=外资看好印度。DII净买入=国内资金接盘。FII卖出+DII买入=国内接外资的货——短期偏空。FII和DII同时买入=最强信号。",
        ranges: [
          { condition: "FII连续买+DII连续买", meaning: "共振向上——印度市场最bullish的信号", color: "green" },
          { condition: "FII买入", meaning: "外资看好——利多", color: "green" },
          { condition: "FII卖+DII买", meaning: "DII接盘模式——短期看空但跌不深", color: "yellow" },
          { condition: "FII卖+DII卖", meaning: "所有人都在跑——重大风险信号", color: "red" },
        ],
        localNote: "FII+DII together = ₹X,XXX crore net. When both buy, Nifty almost always rallies. This is the most reliable signal in Indian markets.",
      },
      risk: {
        id: "IN_RISK",
        name: "印度风险",
        nameEn: "IN Risk",
        emoji: "⚠️",
        oneliner: "India VIX+卢比波动——印度市场的双引擎风险指标",
        description: "India VIX（Nifty波动率指数）>25=恐慌。卢比单日贬值>1%=外资恐慌出逃的信号。印度的风险不只是市场风险——还有政治风险（选举/改革/地缘）。",
        ranges: [
          { condition: "India VIX<15", meaning: "平静——印度常态就是偏高", color: "neutral" },
          { condition: "India VIX 15-20", meaning: "正常偏高", color: "yellow" },
          { condition: "India VIX 20-25", meaning: "紧张——可能与选举/预算/地缘有关", color: "yellow" },
          { condition: "India VIX>25", meaning: "恐慌——买入机会通常出现在VIX从30回落到20的途中", color: "red" },
        ],
        localNote: "India VIX is naturally higher than US VIX. Don't panic at 20 — that's normal. Panic at 30+.",
        dontTrust: "India VIX受Nifty期权到期日影响——每月最后一个周四附近VIX会脉冲式上升，不是真恐慌。",
      },
      macro: {
        id: "IN_MACRO",
        name: "印度宏观",
        nameEn: "IN Macro",
        emoji: "📊",
        oneliner: "GDP+CPI+Repo Rate——印度经济的三脚架",
        description: "GDP增速>6%=正常速度。CPI>6%=RBI被迫加息=利空。Repo Rate（政策利率）走势决定资金成本。财政赤字/GDP是关键长期指标。",
        ranges: [
          { condition: "GDP>7%+CPI 4-6%", meaning: "高增长+温和通胀——印度金发女孩。股市最佳环境", color: "green" },
          { condition: "GDP 5-7%", meaning: "正常增长——印度标准", color: "neutral" },
          { condition: "GDP<5%+CPI>6%", meaning: "滞胀风险——低增长+高通胀=RBI进退两难", color: "red" },
        ],
        localNote: "Monsoon rains affect GDP more than the RBI. A bad monsoon = food inflation + rural demand slump = double hit to stocks.",
        dontTrust: "印度GDP数据频繁修正——一两年后回头看，当时的数据可能被修改了10-20%。不要基于一个季度的GDP做长期决策。",
      },
      breadth: {
        id: "IN_BREADTH",
        name: "印度市场广度",
        nameEn: "IN Market Breadth",
        emoji: "🌡️",
        oneliner: "Nifty涨但Midcap/Smallcap在跌？——印度市场最危险的背离",
        description: "Nifty涨跌比+中小盘vs大盘的相对表现。印度散户爱炒中小盘——中小盘热度是最真实的情绪指标。",
        ranges: [
          { condition: "涨跌比>2+Midcap同步涨", meaning: "全面牛市——最佳状态", color: "green" },
          { condition: "涨跌比1.5-2", meaning: "偏强", color: "green" },
          { condition: "Nifty涨+Midcap跌", meaning: "大股拉指数=资金撤退——危险背离", color: "red" },
          { condition: "涨跌比<0.5", meaning: "普跌——恐慌中", color: "red" },
        ],
        localNote: "When Nifty is up but mid-caps are down, the smart money is distributing. This divergence has preceded every major Indian market correction.",
      },
    },

    // ═══ 韩国 🇰🇷 ═══
    KR: {
      country: "韩国",
      countryEn: "South Korea",
      flag: "🇰🇷",
      indexName: "KOSPI",
      valuation: {
        id: "KR_VALUATION",
        name: "韩国估值分位",
        nameEn: "KR Valuation Percentile",
        emoji: "💰",
        oneliner: "KOSPI PE分位——韩国永远打折的宿命（Korea Discount）",
        description: "韩国PE常年比同等级经济体低20-30%——这就是所谓的'Korea Discount'（韩国折价）。因为北韩地缘风险+财阀治理问题+缺乏股东回报文化。PB<1的公司占比高是韩国特色。",
        ranges: [
          { condition: "PE<10+PB<0.9", meaning: "极度低估——通常是北韩危机或全球衰退导致", color: "green" },
          { condition: "PE 10-12", meaning: "低估——买韩国就是在打折时买", color: "green" },
          { condition: "PE 12-14", meaning: "正常——但韩国正常就是打折", color: "neutral" },
          { condition: "PE>14", meaning: "贵——PE>14时不要追，等Korea Discount回归", color: "red" },
        ],
        localNote: "코리아 디스카운트는 실존한다. PER이 낮다고 무조건 사지 말고, 주주환원 정책을 보라.",
        dontTrust: "Korea Discount可能永远不会消失——把'低PE'当做买入韩国唯一理由的人，已经等了20年了。买入韩国的理由应该是企业价值提升计划/分红增加/治理改革，不是便宜。",
      },
      momentum: {
        id: "KR_MOMENTUM",
        name: "韩国动量",
        nameEn: "KR Momentum",
        emoji: "🚀",
        oneliner: "KOSPI趋势——半导体周期=韩国股市的心跳",
        description: "三星+SK海力士占KOSPI权重超30%。DRAM/NAND价格=韩国股市的先行指标。半导体周期向上=韩国牛市。",
        ranges: [
          { condition: "3M>10%+三星领涨", meaning: "半导体驱动牛市——三星涨+外资买=最强信号", color: "green" },
          { condition: "3M>0%", meaning: "正动量", color: "green" },
          { condition: "3M -5%~0%", meaning: "横盘——等待半导体价格信号", color: "neutral" },
          { condition: "3M<-10%+三星暴跌", meaning: "半导体下行周期——韩国熊市", color: "red" },
        ],
        localNote: "삼성전자만 봐도 코스피 방향을 알 수 있다. 반도체 사이클이 바닥을 찍을 때가 코스피 최고의 매수 타이밍.",
      },
      foreignFlow: {
        id: "KR_FOREIGN_FLOW",
        name: "韩国外资流",
        nameEn: "KR Foreign Flow",
        emoji: "🌏",
        oneliner: "외국인(外国人)在买韩国吗——外资买三星=买KOSPI",
        description: "韩国交易所公布的외국인 순매수。外资集中买半导体=强烈看多信号。外资买三星/海力士+卖其他=不是真看好韩国，只是在赌芯片周期。",
        ranges: [
          { condition: "外资连续买三星+SK海力士", meaning: "半导体β交易——外资在赌芯片周期上行", color: "green" },
          { condition: "外资连续净买入", meaning: "外资风险转暖——利多", color: "green" },
          { condition: "买卖交替", meaning: "方向不明", color: "neutral" },
          { condition: "外资连续净卖出", meaning: "外资撤退——通常伴随韩元贬值", color: "red" },
        ],
        localNote: "외국인이 삼성전자만 집중 매수할 땐 '진짜 한국 러브콜'이 아니라 반도체 베팅일 뿐이다.",
      },
      risk: {
        id: "KR_RISK",
        name: "韩国风险",
        nameEn: "KR Risk",
        emoji: "⚠️",
        oneliner: "VKOSPI+北韩+韩元——韩国市场永远的三重风险",
        description: "VKOSPI>25=恐慌。北韩导弹试射=脉冲式风险（通常1-3天恢复）。韩元大幅贬值=外资流出加速。韩国风险=地缘+汇率+半导体周期的三维叠加。",
        ranges: [
          { condition: "VKOSPI<20", meaning: "平静——但韩国平静期一般不超3个月", color: "neutral" },
          { condition: "VKOSPI 20-25", meaning: "正常——韩国标准偏高", color: "yellow" },
          { condition: "VKOSPI>25", meaning: "恐慌——买入机会。每次北韩危机导致的VKOSPI飙升都是买点", color: "green" },
          { condition: "VKOSPI>30+北韩事件", meaning: "极度恐慌——历史数据: 北韩事件后1个月KOSPI平均上涨", color: "green" },
        ],
        localNote: "북한 리스크는 매수 기회다. 지난 20년간 북한발 코스피 급락은 1~3개월 내 회복됐다. 진짜 위험은 반도체 다운사이클.",
        dontTrust: "北韩风险被严重高估了——市场早已免疫。真正的韩国风险是半导体周期和三星的经营决策，不是导弹。",
      },
      macro: {
        id: "KR_MACRO",
        name: "韩国宏观",
        nameEn: "KR Macro",
        emoji: "📊",
        oneliner: "出口+半导体出货+韩国央行——韩国的经济三驾马车",
        description: "韩国出口增速=最领先的宏观指标（韩国出口数据每月1号公布，全球最早）。出口增速<0%=经济警报。半导体出货量同比是核心中的核心。",
        ranges: [
          { condition: "出口增速>10%+半导体出货>20%", meaning: "出口超级周期——韩国最佳宏观环境", color: "green" },
          { condition: "出口增速>0%", meaning: "正常——韩国经济在扩张", color: "green" },
          { condition: "出口增速 -5%~0%", meaning: "出口放缓——警惕。可能领先GDP下行", color: "yellow" },
          { condition: "出口增速<-10%", meaning: "出口骤降——全球需求崩盘的先行信号", color: "red" },
        ],
        localNote: "한국 수출은 글로벌 경기의 '카나리아'다. 한국 수출이 꺾이면 세계 경기가 꺾인다는 신호.",
        dontTrust: "韩国出口数据每月1号公布——市场开盘前就被消化了。等到你看到数据再行动，已经晚了。出口增速的趋势方向比单月数据重要10倍。",
      },
      breadth: {
        id: "KR_BREADTH",
        name: "韩国市场广度",
        nameEn: "KR Market Breadth",
        emoji: "🌡️",
        oneliner: "KOSPI涨但KOSDAQ在跌？——散户恐慌的信号",
        description: "KOSPI(大盘)+KOSDAQ(创业板)的涨跌比。KOSDAQ代表散户情绪——KOSDAQ暴跌+KOSPI横盘=散户踩踏。",
        ranges: [
          { condition: "KOSPI涨+KOSDAQ涨", meaning: "全面牛市——机构+散户共振", color: "green" },
          { condition: "KOSPI涨+KOSDAQ跌", meaning: "大股拉指数——散户在撤退（通常是聪明钱的信号）", color: "yellow" },
          { condition: "KOSPI跌+KOSDAQ跌", meaning: "全面下跌", color: "red" },
        ],
        localNote: "코스닥이 코스피보다 먼저 무너진다. 동학개미(개인투자자)의 투심은 코스닥에서 가장 진솔하게 드러난다.",
      },
    },

    // ═══ 台湾 🇹🇼 ═══
    TW: {
      country: "台湾",
      countryEn: "Taiwan",
      flag: "🇹🇼",
      indexName: "加權指數",
      valuation: {
        id: "TW_VALUATION",
        name: "台湾估值分位",
        nameEn: "TW Valuation Percentile",
        emoji: "💰",
        oneliner: "台股PE分位——台积电决定了大盘估值",
        description: "台积电占加權指數权重超30%。台积电PE=市场PE的锚。台积电PE<15=便宜，>25=贵。非台积电PE跟历史比才有意义。",
        ranges: [
          { condition: "大盘PE<13", meaning: "低估——通常是全球科技股大跌导致的", color: "green" },
          { condition: "大盘PE 13-16", meaning: "正常偏低——台股常态", color: "green" },
          { condition: "大盘PE 16-18", meaning: "合理偏高", color: "neutral" },
          { condition: "大盘PE>18", meaning: "偏贵——台积电PE可能已到高估区", color: "red" },
        ],
        localNote: "台積電的PE就是台股的PE。單看大盤PE不準——扣除台積電後PE會更低，但不是便宜。",
        dontTrust: "除去台积电的台股PE很低——但那些公司是真低PE还是夕阳产业要分清楚。高股息股（电信/金融）天然PE低≠便宜。",
      },
      momentum: {
        id: "TW_MOMENTUM",
        name: "台湾动量",
        nameEn: "TW Momentum",
        emoji: "🚀",
        oneliner: "台股趋势——台积电涨=大盘涨。几乎是一一对应的关系",
        description: "台股动量由台积电驱动。关注台积电的相对强弱：台积电>大盘=科技权重在增长。台积电<大盘=非科技补涨=通常不持久。",
        ranges: [
          { condition: "3M>10%+台积电创新高", meaning: "科技驱动牛市——台积电带大盘飞", color: "green" },
          { condition: "3M>0%", meaning: "正动量", color: "green" },
          { condition: "3M -5%~0%", meaning: "横盘——等待台积电法说会信号", color: "neutral" },
          { condition: "3M<-10%", meaning: "回调——大概率与台积电下跌同步", color: "red" },
        ],
        localNote: "台積電法說會前後一周，台股震盪最劇烈。不要在那時候加碼。等法說會後方向明確再進。",
      },
      foreignFlow: {
        id: "TW_FOREIGN_FLOW",
        name: "台湾三大法人",
        nameEn: "TW 3-Institution Flow",
        emoji: "🌏",
        oneliner: "外资+投信+自营商——三方资金角力决定台股方向",
        description: "外资：连续买超=看好。投信（基金）：买超=本地资金活跃。自营商：卖超往往是避险（对冲权证）。三者同买=最强信号。",
        ranges: [
          { condition: "外资买+投信买", meaning: "内外资共振——最强做多信号", color: "green" },
          { condition: "外资买+投信卖", meaning: "外资主导——投信获利了结（正常）", color: "green" },
          { condition: "外资卖+投信买", meaning: "投信护盘——通常是短期，外资卖压力更大", color: "yellow" },
          { condition: "外资卖+投信卖", meaning: "法人大逃亡——重大风险信号", color: "red" },
        ],
        localNote: "三大法人同步買超=台股最強發動信號。反之同步賣超=一定要減碼。",
        dontTrust: "自营商卖超不一定是看空——很多是权证避险操作。单看自营商卖超会误判。三大法人中以外资动向最重要。",
      },
      risk: {
        id: "TW_RISK",
        name: "台湾风险",
        nameEn: "TW Risk",
        emoji: "⚠️",
        oneliner: "台指VIX+海峡风险——台股永远的风险溢价来源",
        description: "台指选择权波动率指数（台指VIX）。海峡紧张=VIX跳升。但从历史看，海峡事件对台股影响越来越小（市场已免疫）。",
        ranges: [
          { condition: "台指VIX<15", meaning: "平静", color: "neutral" },
          { condition: "台指VIX 15-20", meaning: "正常偏高——台股常态", color: "yellow" },
          { condition: "台指VIX 20-25", meaning: "紧张——可能有海峡事件或全球科技抛售", color: "red" },
          { condition: "台指VIX>25", meaning: "恐慌——海峡事件导致的恐慌=买入机会（历史上无一例外）", color: "green" },
        ],
        localNote: "海峽風險造成的急跌都是買點。過去30年每次海峽危機後台股都創新高。真正的風險是全球半導體衰退，不是政治。",
      },
      macro: {
        id: "TW_MACRO",
        name: "台湾宏观",
        nameEn: "TW Macro",
        emoji: "📊",
        oneliner: "出口订单+PMI+M1B——台湾经济的三大领先指标",
        description: "台湾出口订单年增率=未来3-6个月出口的领先指标。M1B(狭义货币)>M2(广义货币)=资金动能足(黄金交叉)。外销订单中电子产品占比>50%=看半导体的状态。",
        ranges: [
          { condition: "出口订单>10%+M1B>M2", meaning: "资金面+基本面双多——最强宏观组合", color: "green" },
          { condition: "出口订单>0%", meaning: "正常扩张", color: "green" },
          { condition: "出口订单<0%", meaning: "订单萎缩——台股3-6个月后下跌概率高", color: "red" },
        ],
        localNote: "M1B-M2黃金交叉(資金行情啟動)出現時，台股通常還有一波漲勢。這是台股最可靠的總經信號。",
      },
      breadth: {
        id: "TW_BREADTH",
        name: "台湾市场广度",
        nameEn: "TW Market Breadth",
        emoji: "🌡️",
        oneliner: "台积电涨但其他股票没涨——假强势的经典信号",
        description: "加權指數涨跌家数+集中度。台积电一家贡献指数过半涨幅=假强势（宽度差）。行情必须扩散到非台积电才算健康。",
        ranges: [
          { condition: "涨跌比>2+电子/传产齐涨", meaning: "全面牛市——最理想", color: "green" },
          { condition: "台积电涨+涨跌比<1", meaning: "一只独秀=假强势——台积电在拉大盘掩护出货", color: "red" },
          { condition: "涨跌比<0.5", meaning: "普跌——风险模式", color: "red" },
        ],
        localNote: "台積電大漲但跌的家數比漲的多=假突破。健康的台股是電子+傳產+金融三大類股一起動。",
      },
    },

    // ═══ 欧洲 🇪🇺 ═══
    EU: {
      country: "欧洲",
      countryEn: "Europe",
      flag: "🇪🇺",
      indexName: "STOXX 600",
      valuation: {
        id: "EU_VALUATION",
        name: "欧洲估值分位",
        nameEn: "EU Valuation Percentile",
        emoji: "💰",
        oneliner: "STOXX 600 PE分位——欧洲永远比美国便宜，但要分清是折价还是陷阱",
        description: "STOXX 600 PE常年比S&P 500低20-30%。便宜有道理（增长慢+银行权重大+政治风险高）。但PE<12时=历史级便宜（欧债危机/脱欧/战争）。",
        ranges: [
          { condition: "PE<12", meaning: "历史级低估——通常是重大危机（2011欧债/2020新冠/2022乌克兰）", color: "green" },
          { condition: "PE 12-14", meaning: "低估区间——值得关注", color: "green" },
          { condition: "PE 14-16", meaning: "正常——欧洲常态", color: "neutral" },
          { condition: "PE>16", meaning: "偏贵——欧洲PE>16时外资兴趣下降", color: "yellow" },
          { condition: "PE>18", meaning: "贵——别追", color: "red" },
        ],
        localNote: "Europe is not 'cheap' — it's 'cheap for a reason'. Understand the reason before buying the discount.",
        dontTrust: "欧洲整体PE低是因为银行和能源占比高——这两个行业天然PE低。看板块PE更准确。德国DAX和法国CAC的PE通常比STOXX 600高2-3倍。",
      },
      momentum: {
        id: "EU_MOMENTUM",
        name: "欧洲动量",
        nameEn: "EU Momentum",
        emoji: "🚀",
        oneliner: "STOXX 600趋势——欧元弱=欧洲股市强（出口驱动）",
        description: "欧元/美元汇率与STOXX 600高度负相关。欧元贬值>10%=欧洲出口企业利润暴增=STOXX跑赢。欧元升值=逆风。",
        ranges: [
          { condition: "3M>10%+欧元贬值", meaning: "出口红利——欧元走弱是欧洲牛市的隐藏引擎", color: "green" },
          { condition: "3M>0%", meaning: "正动量", color: "green" },
          { condition: "3M -5%~0%", meaning: "横盘——可能欧元在走强", color: "neutral" },
          { condition: "3M<-10%+欧元升值", meaning: "双重打击——欧洲特色危机模式", color: "red" },
        ],
        localNote: "When the euro drops, European stocks rise — and vice versa. This is the single strongest macro relationship in European equities.",
      },
      foreignFlow: {
        id: "EU_FOREIGN_FLOW",
        name: "欧洲外资流",
        nameEn: "EU Foreign Flow",
        emoji: "🌏",
        oneliner: "全球资金在流入还是流出欧洲——EPFR欧洲股票基金流向",
        description: "欧洲股票ETF/基金的周度净流入。连续4周净流入=全球资金开始关注洼地。欧洲通常是最后被资金关照的市场。",
        ranges: [
          { condition: "连续4周净流入", meaning: "资金轮动到欧洲——可能是从美股撤出的钱", color: "green" },
          { condition: "净流入", meaning: "偏正面", color: "green" },
          { condition: "小幅净流出", meaning: "正常——欧洲常年是资金流出地", color: "neutral" },
          { condition: "大额净流出", meaning: "加速撤离——可能欧元区危机", color: "red" },
        ],
        localNote: "Europe is usually the last place global money goes. When it finally arrives, the rally can be powerful but short. Take profits quickly.",
      },
      risk: {
        id: "EU_RISK",
        name: "欧洲风险",
        nameEn: "EU Risk",
        emoji: "⚠️",
        oneliner: "VSTOXX+边缘国家利差——欧洲的双重风险温度计",
        description: "VSTOXX (Euro STOXX 50波动率指数)>30=欧元区恐慌。意/德10年国债利差(BTP-Bund spread)>200bp=边缘国家压力。两项同时上升=欧债危机重现信号。",
        ranges: [
          { condition: "VSTOXX<20+意德利差<150bp", meaning: "平静——欧洲最佳状态", color: "green" },
          { condition: "VSTOXX 20-25", meaning: "轻度紧张——可能某个国家选举或政策不确定", color: "yellow" },
          { condition: "VSTOXX 25-30", meaning: "显著紧张——注意利差是否也在扩大", color: "red" },
          { condition: "VSTOXX>30+利差>200bp", meaning: "双重危机——2011模式。远离欧洲银行和外围国家", color: "red" },
        ],
        localNote: "The real European risk indicator isn't VSTOXX — it's the Italy-Germany spread. When BTP-Bund widens above 250bp, it's time to sell European banks.",
      },
      macro: {
        id: "EU_MACRO",
        name: "欧洲宏观",
        nameEn: "EU Macro",
        emoji: "📊",
        oneliner: "PMI+ECB利率——决定欧洲经济的两个核心",
        description: "欧元区综合PMI>50=扩张。<50=收缩。ECB政策利率走势=欧洲银行盈利能力的关键。ZEW德国经济景气指数=最重要的软数据领先指标。",
        ranges: [
          { condition: "综合PMI>52+ECB偏鸽", meaning: "金发女孩——欧洲最好的宏观环境", color: "green" },
          { condition: "综合PMI 48-52", meaning: "停滞——欧洲常态", color: "neutral" },
          { condition: "综合PMI<48", meaning: "收缩——经济衰退信号", color: "red" },
        ],
        localNote: "The German ZEW survey is the best leading indicator for European stocks. When ZEW turns negative, STOXX 600 usually follows within 2-3 months.",
      },
      breadth: {
        id: "EU_BREADTH",
        name: "欧洲市场广度",
        nameEn: "EU Market Breadth",
        emoji: "🌡️",
        oneliner: "STOXX 600涨跌比——德国在拉还是全欧洲在涨？",
        description: "STOXX 600内涨跌家数比。德国DAX一家占比过高——DAX涨+其他市场跌=德国独强=不可持续。全欧洲同涨=真牛市。",
        ranges: [
          { condition: "涨跌比>2+多国同涨", meaning: "全面走强——欧洲牛市真来了", color: "green" },
          { condition: "涨跌比1-2", meaning: "正常", color: "neutral" },
          { condition: "DAX涨+涨跌比<0.8", meaning: "德国独强=假强势——资金在从外围国家撤退", color: "red" },
        ],
        localNote: "When only German stocks rise and Italian/Spanish stocks fall, it's 'flight to quality' within Europe — the worst kind of rally.",
      },
    },

    // ═══ 巴西 🇧🇷 ═══
    BR: {
      country: "巴西",
      countryEn: "Brazil",
      flag: "🇧🇷",
      indexName: "Ibovespa",
      valuation: {
        id: "BR_VALUATION",
        name: "巴西估值分位",
        nameEn: "BR Valuation Percentile",
        emoji: "💰",
        oneliner: "Ibovespa PE——巴西股市贵不贵的唯一靠谱判断",
        description: "巴西PE波动极大（6-20倍）——因为大宗商品周期+政治动荡。PE<8=极度便宜（通常是政治崩溃时）。PE>15=贵。",
        ranges: [
          { condition: "PE<8", meaning: "极度低估——政治危机导致的超卖。历史上PE<8后1年平均回报极高", color: "green" },
          { condition: "PE 8-10", meaning: "便宜——巴西的买入区间", color: "green" },
          { condition: "PE 10-13", meaning: "正常", color: "neutral" },
          { condition: "PE 13-16", meaning: "偏贵——但大宗商品牛市时可以接受", color: "yellow" },
          { condition: "PE>16", meaning: "贵——历史上PE>16后回报很差", color: "red" },
        ],
        localNote: "No Brasil, PE baixo é sempre crise política. Se você aguentar a montanha-russa política, é a melhor hora pra comprar.",
        dontTrust: "巴西PE极低时不要只看估值——政治风险可能是真实的。2015年PE<8是因为总统被弹劾、GDP暴跌、货币崩盘同时发生。",
      },
      momentum: {
        id: "BR_MOMENTUM",
        name: "巴西动量",
        nameEn: "BR Momentum",
        emoji: "🚀",
        oneliner: "Ibovespa的涨跌——大宗商品周期+政治的双引擎",
        description: "铁矿石+石油+大豆=巴西股市的DNA。Vale+Petrobras两只股票决定大盘方向。大宗商品价格×汇率=巴西股票美元回报的核心公式。",
        ranges: [
          { condition: "3M>15%+商品涨", meaning: "大宗驱动牛市——新兴市场最暴力的上涨", color: "green" },
          { condition: "3M>0%", meaning: "正动量", color: "green" },
          { condition: "3M -10%~0%", meaning: "回调——正常波动。巴西20%回调是家常便饭", color: "neutral" },
          { condition: "3M<-15%", meaning: "崩盘——通常是政治+商品双重打击", color: "red" },
        ],
        localNote: "Brasil sobe escada e desce elevador. As altas são lentas, as quedas são violentas. Nunca use stop-loss apertado no Brasil.",
      },
      foreignFlow: {
        id: "BR_FOREIGN_FLOW",
        name: "巴西外资流",
        nameEn: "BR Foreign Flow",
        emoji: "🌏",
        oneliner: "外资在买巴西吗——外资进出巴西像开关电灯",
        description: "B3公布的estrangeiro流量。外资在巴西的行为高度二元——不是狂热买就是恐慌卖。新兴市场基金配置是主导因素。",
        ranges: [
          { condition: "连续4周净买入", meaning: "外资回归——通常是全球Risk-On信号", color: "green" },
          { condition: "净买入", meaning: "正面", color: "green" },
          { condition: "小幅净卖出", meaning: "正常波动", color: "neutral" },
          { condition: "大额净卖出", meaning: "Risk-Off——外资从新兴市场全面撤退", color: "red" },
        ],
        localNote: "O gringo entra e sai do Brasil como quem acende e apaga a luz. Não leve para o pessoal — é fluxo de fundo de emergentes.",
      },
      risk: {
        id: "BR_RISK",
        name: "巴西风险",
        nameEn: "BR Risk",
        emoji: "⚠️",
        oneliner: "Ibovespa波动率+CDS+雷亚尔——巴西的三维风险矩阵",
        description: "巴西天然波动率全球最高之一。BRL单日跌2%=正常。CDS>300bp=政治/财政危机。巴西风险永远存在——关键是风险是否已被定价。",
        ranges: [
          { condition: "CDS<200bp+雷亚尔稳定", meaning: "风险适中——巴西最好的状态", color: "green" },
          { condition: "CDS 200-300bp", meaning: "风险升高——正常巴西波动", color: "yellow" },
          { condition: "CDS>300bp+雷亚尔暴跌", meaning: "危机模式——可能财政/政治风暴", color: "red" },
        ],
        localNote: "Brasil nunca é seguro. A pergunta não é 'tem risco?' — é 'o risco já está no preço?'. CDS alto + PE baixo = pode ser a hora de comprar.",
      },
      macro: {
        id: "BR_MACRO",
        name: "巴西宏观",
        nameEn: "BR Macro",
        emoji: "📊",
        oneliner: "Selic利率+财政赤字+通胀——巴西宏观的圣三一",
        description: "Selic(政策利率)走势=巴西最重要的宏观变量。Selic下行=股市牛市（资金从债券流向股票）。财政赤字/GDP>8%=危险信号。",
        ranges: [
          { condition: "Selic下行+财政在改善", meaning: "最佳环境——降息+财政纪律=巴西最牛组合", color: "green" },
          { condition: "Selic稳定", meaning: "中性", color: "neutral" },
          { condition: "Selic上行+财政恶化", meaning: "滞胀+财政危机——股债汇三杀风险", color: "red" },
        ],
        localNote: "Selic é o que importa. Quando o BC começa a cortar, é hora de comprar bolsa. Quando sobe, é hora de vender.",
        dontTrust: "巴西央行的独立性一直被政治侵蚀——Selic决策不纯粹是经济考量。总统施压降息时不要盲目乐观。",
      },
      breadth: {
        id: "BR_BREADTH",
        name: "巴西市场广度",
        nameEn: "BR Market Breadth",
        emoji: "🌡️",
        oneliner: "Petrobras+Vale涨但其他82只跌——巴西特有的集中度风险",
        description: "Ibovespa中Petrobras+Vale权重超25%。两只股涨+其他跌=假牛市。中小盘活跃度比大盘涨跌更能反映真实市场情绪。",
        ranges: [
          { condition: "涨跌比>2+中小盘活跃", meaning: "真实牛市——难得一见", color: "green" },
          { condition: "两只权重涨+涨跌比<0.8", meaning: "大宗撑盘——其他股票在跌。危险信号", color: "red" },
        ],
        localNote: "Quando só Petrobras e Vale sobem, a festa é falsa. Ibovespa sem as duas é o índice que conta a verdade.",
      },
    },

    // ═══ 沙特 🇸🇦 ═══
    SA: {
      country: "沙特",
      countryEn: "Saudi Arabia",
      flag: "🇸🇦",
      indexName: "TASI",
      valuation: {
        id: "SA_VALUATION",
        name: "沙特估值分位",
        nameEn: "SA Valuation Percentile",
        emoji: "💰",
        oneliner: "Tadawul PE分位——沙特=油价+愿景2030的双重定价",
        description: "沙特PE受油价和改革预期双重驱动。油价$80+时沙特财政宽裕+PE扩张。PE<15=便宜（通常油价<60时见）。PE>20=偏贵。",
        ranges: [
          { condition: "PE<15", meaning: "低估——油价低迷期=买入沙特的好时机", color: "green" },
          { condition: "PE 15-18", meaning: "正常偏低", color: "green" },
          { condition: "PE 18-22", meaning: "合理——沙特正常估值区间", color: "neutral" },
          { condition: "PE>22", meaning: "偏贵——通常油价>100时", color: "red" },
        ],
        localNote: "السوق السعودي = النفط + رؤية 2030. عندما يكون النفط فوق 80، كل شيء جيد. عندما ينخفض تحت 60، تبدأ المشاكل.",
        dontTrust: "沙特PE受Aramco权重影响巨大——Aramco PE≈全球石油巨头平均。剔除Aramco的沙特PE更高。新上市股票（愿景2030相关）PE极高但属于成长型定价。",
      },
      momentum: {
        id: "SA_MOMENTUM",
        name: "沙特动量",
        nameEn: "SA Momentum",
        emoji: "🚀",
        oneliner: "TASI跟着油价走——油涨沙特涨，油跌沙特跌。简单粗暴",
        description: "TASI和布伦特油价相关系数>0.7。油价趋势=沙特股市趋势。外资准入开放后，全球资金流入提供额外动量。",
        ranges: [
          { condition: "油价>80+3M>10%", meaning: "油价牛+股市牛=最强正反馈", color: "green" },
          { condition: "3M>0%", meaning: "正动量", color: "green" },
          { condition: "油价<60+3M<0%", meaning: "油价崩=沙股崩——2008/2014/2020三次无一例外", color: "red" },
        ],
        localNote: "Oil above $80 = Saudi budget surplus = market up. This relationship has held for 30 years.",
      },
      foreignFlow: {
        id: "SA_FOREIGN_FLOW",
        name: "沙特外资流",
        nameEn: "SA Foreign Flow",
        emoji: "🌏",
        oneliner: "合格外国投资者(QFI)的流入——沙特开放后外资在真金白银投票",
        description: "QFII净买入额。外资持有沙特股票比例仍低（<5%）但快速增长。MSCI/FTSE纳入=被动资金恒定流入=长期利好。",
        ranges: [
          { condition: "QFI连续净买入", meaning: "外资加速入场——沙特开放红利的核心体现", color: "green" },
          { condition: "净买入", meaning: "正面——长期趋势向上", color: "green" },
          { condition: "净卖出", meaning: "外资获利了结——短期负面但长期趋势未改", color: "yellow" },
        ],
        localNote: "Foreign ownership in Saudi is still <5% of market cap. The inflow story has years to run. Every dip from foreign selling is a buying opportunity.",
      },
      risk: {
        id: "SA_RISK",
        name: "沙特风险",
        nameEn: "SA Risk",
        emoji: "⚠️",
        oneliner: "油价崩盘+地缘冲突=沙特的双重风险触发器",
        description: "布伦特油价的隐含波动率+中东地缘局势。油价跌破沙特财政盈亏平衡线（约$80）=财政紧缩=经济下行=股市承压。",
        ranges: [
          { condition: "油价>80+地缘稳定", meaning: "安全的——沙特最佳状态", color: "green" },
          { condition: "油价60-80", meaning: "适度风险——财政略有压力但可控", color: "yellow" },
          { condition: "油价<60或地缘升级", meaning: "高风险——油价崩或中东战争都是严重威胁", color: "red" },
        ],
        localNote: "Saudi breakeven oil price is ~$80/bbl. Below that for 6+ months, the fiscal situation gets uncomfortable.",
      },
      macro: {
        id: "SA_MACRO",
        name: "沙特宏观",
        nameEn: "SA Macro",
        emoji: "📊",
        oneliner: "油价×财政×非油GDP——沙特经济转型的三条腿",
        description: "财政赤字/GDP<3%=健康。非油GDP增速=愿景2030真伪的验证——>3%才是真转型。沙特央行(SAMA)利率跟美联储走。",
        ranges: [
          { condition: "非油GDP>3%+油价>80", meaning: "双重红利——石油富+改革见效。最佳状态", color: "green" },
          { condition: "非油GDP>0%", meaning: "转型在进行——但石油仍是主导", color: "neutral" },
          { condition: "油价<60+财政赤字>5%", meaning: "危机模式——油价暴跌+转型未完成=双重打击", color: "red" },
        ],
        localNote: "Vision 2030 is real, but it's a 15-year story. Don't trade Saudi on one quarter of non-oil GDP. Watch the multi-year trend.",
      },
      breadth: {
        id: "SA_BREADTH",
        name: "沙特市场广度",
        nameEn: "SA Market Breadth",
        emoji: "🌡️",
        oneliner: "Aramco涨≠沙特涨——但大多数时候确实是这样",
        description: "Aramco占TASI权重超大。Aramco涨+银行涨=真牛市。Aramco跌+银行跌=全面撤退。银行股表现比Aramco更能反映本土经济健康度。",
        ranges: [
          { condition: "涨跌比>1.5+银行板块涨", meaning: "健康牛市——本土经济+石油双驱动", color: "green" },
          { condition: "Aramco涨+涨跌比<0.8", meaning: "单一驱动——仅在油价飙升时有意义", color: "yellow" },
          { condition: "涨跌比<0.5", meaning: "普跌——撤退模式", color: "red" },
        ],
        localNote: "When Saudi banks are rising alongside Aramco, the rally is real. Banks = domestic economy proxy in Saudi.",
      },
    },

    // ═══ 新加坡 🇸🇬 ═══
    SG: {
      country: "新加坡",
      countryEn: "Singapore",
      flag: "🇸🇬",
      indexName: "STI",
      valuation: {
        id: "SG_VALUATION",
        name: "新加坡估值分位",
        nameEn: "SG Valuation Percentile",
        emoji: "💰",
        oneliner: "STI PE分位——全球最被低估的发达市场之一",
        description: "STI PE约12-14倍=亚洲最便宜发达市场。高股息率(>4%)=重要估值支撑。银行三巨头(DBS/OCBC/UOB)PE决定整体估值。",
        ranges: [
          { condition: "PE<11", meaning: "低估——通常是全球危机时。买入窗口", color: "green" },
          { condition: "PE 11-13", meaning: "偏低——新加坡常态", color: "green" },
          { condition: "PE 13-15", meaning: "合理", color: "neutral" },
          { condition: "PE>15", meaning: "偏贵——利率下行环境可达，但历史高位", color: "red" },
        ],
        localNote: "Singapore is the most boring market in Asia — and that's exactly why it works for dividends. Don't expect excitement, expect income.",
      },
      momentum: {
        id: "SG_MOMENTUM",
        name: "新加坡动量",
        nameEn: "SG Momentum",
        emoji: "🚀",
        oneliner: "STI趋势——新加坡=全球贸易的温度计",
        description: "新加坡是开放经济体——全球贸易增速=新加坡股市的命脉。全球经济衰退=新加坡率先反应。反之全球复苏=新加坡领先反弹。",
        ranges: [
          { condition: "3M>5%+全球PMI升", meaning: "贸易复苏驱动——新加坡领先反弹", color: "green" },
          { condition: "3M 0-5%", meaning: "温和上涨——银行REITs股息稳定回报", color: "green" },
          { condition: "3M -3%~0%", meaning: "微跌——正常波动", color: "neutral" },
          { condition: "3M<-5%", meaning: "显著下跌——全球贸易放缓信号", color: "red" },
        ],
        localNote: "Singapore is a trade barometer. When global trade slows, Singapore slows first. When trade recovers, Singapore recovers first.",
      },
      foreignFlow: {
        id: "SG_FOREIGN_FLOW",
        name: "新加坡外资流",
        nameEn: "SG Foreign Flow",
        emoji: "🌏",
        oneliner: "全球资金把新加坡当亚洲安全港——钱进还是出",
        description: "新加坡是亚洲的瑞士——全球Risk-Off时资金流入新加坡（安全港效应）。Risk-On时资金流出新加坡去新兴市场博高收益。",
        ranges: [
          { condition: "全球Risk-Off+外资流入SG", meaning: "安全港模式——新加坡逆势上涨。经典防御", color: "green" },
          { condition: "外资净流入", meaning: "正面", color: "green" },
          { condition: "全球Risk-On+外资流出SG", meaning: "资金转战新兴市场——新加坡补涨空间被压缩", color: "yellow" },
        ],
        localNote: "Money flows into Singapore when the world is scared, and out when the world is greedy. It's the Asia safe haven.",
      },
      risk: {
        id: "SG_RISK",
        name: "新加坡风险",
        nameEn: "SG Risk",
        emoji: "⚠️",
        oneliner: "新加坡波幅低但全球化风险高——安全港也有漏水的时候",
        description: "STI波动率天然低于大多数亚洲市场（银行+REITs=防御型）。SGD强势=外资信心。SGD走弱=风险预警。新加坡独特风险：周边国家衰退拖累。",
        ranges: [
          { condition: "波动率<15%+SGD稳定", meaning: "新加坡正常状态——低波动", color: "green" },
          { condition: "波动率15-20%", meaning: "轻度紧张——可能是全球性事件", color: "yellow" },
          { condition: "波动率>20%", meaning: "恐慌——通常是全球金融危机波及新加坡", color: "red" },
        ],
        localNote: "Singapore volatility spikes only during global crises. When STI vol > 20%, it's almost always a global issue, not a local one.",
      },
      macro: {
        id: "SG_MACRO",
        name: "新加坡宏观",
        nameEn: "SG Macro",
        emoji: "📊",
        oneliner: "出口+PMI+SGD汇率——新加坡经济的三面镜子",
        description: "新加坡非油国内出口(NODX)同比增速=最重要的月度经济指标。电子出口=最大项。PMI>50=扩张。SGD NEER(名义有效汇率)=MAS的政策工具。",
        ranges: [
          { condition: "NODX>10%+PMI>50", meaning: "出口繁荣——新加坡最好的宏观组合", color: "green" },
          { condition: "NODX>0%", meaning: "正常", color: "neutral" },
          { condition: "NODX<-5%", meaning: "出口萎缩——全球需求大幅下滑的先行信号", color: "red" },
        ],
        localNote: "Singapore NODX data is one of the earliest monthly trade indicators in the world. When it turns negative, global trade is in trouble.",
      },
      breadth: {
        id: "SG_BREADTH",
        name: "新加坡市场广度",
        nameEn: "SG Market Breadth",
        emoji: "🌡️",
        oneliner: "STI 30只成分股——广度参考意义有限，关注REITs vs 银行",
        description: "STI只有30只成分股，涨跌比参考价值有限。更有意义的是REITs板块vs银行板块的相对表现=市场在追逐收益(REITs)还是价值(银行)。",
        ranges: [
          { condition: "REITs涨+银行涨", meaning: "全面走强——利率下行+经济好=最理想", color: "green" },
          { condition: "REITs涨+银行跌", meaning: "利率下行预期——资金流向高收益", color: "neutral" },
          { condition: "REITs跌+银行跌", meaning: "全面走弱——利率上行+经济担忧", color: "red" },
        ],
        localNote: "In Singapore, REITs vs Banks tells you more about market direction than breadth. REITs up = rate cut hopes. Banks up = economic recovery.",
      },
    },

    // ═══ 澳洲 🇦🇺 ═══
    AU: {
      country: "澳洲",
      countryEn: "Australia",
      flag: "🇦🇺",
      indexName: "ASX 200",
      valuation: {
        id: "AU_VALUATION",
        name: "澳洲估值分位",
        nameEn: "AU Valuation Percentile",
        emoji: "💰",
        oneliner: "ASX PE分位——矿业+银行双寡头决定了澳洲整体估值",
        description: "ASX 200 PE约15-17倍=发达国家中等。银行PE<12倍=便宜。矿业PE波动剧烈（大宗商品周期）。注意：澳洲股息率全球最高之一，含Franking Credit(红利抵免)。",
        ranges: [
          { condition: "PE<14", meaning: "低估——通常是矿业崩盘导致的大幅折价", color: "green" },
          { condition: "PE 14-16", meaning: "偏低——正常", color: "green" },
          { condition: "PE 16-18", meaning: "合理", color: "neutral" },
          { condition: "PE>18", meaning: "偏贵——可能大宗商品超级周期顶峰", color: "red" },
        ],
        localNote: "Aussie stocks are dividend machines. The PE is just one piece — franking credits add ~1.5% after-tax return that PE doesn't capture.",
      },
      momentum: {
        id: "AU_MOMENTUM",
        name: "澳洲动量",
        nameEn: "AU Momentum",
        emoji: "🚀",
        oneliner: "ASX 200走势——铁矿石+AUD决定了方向",
        description: "铁矿石价格=ASX矿产板块的锚。AUD汇率×大宗商品=ASX 200美元回报的核心。AUD走强=外资获利了结压力。",
        ranges: [
          { condition: "3M>8%+铁矿石涨", meaning: "资源驱动牛市——ASX最经典的上涨模式", color: "green" },
          { condition: "3M>0%", meaning: "正动量", color: "green" },
          { condition: "3M -5%~0%", meaning: "横盘——澳洲常态", color: "neutral" },
          { condition: "3M<-8%", meaning: "下跌——通常是全球商品需求担忧", color: "red" },
        ],
        localNote: "When iron ore goes up, ASX goes up. When China slows, ASX goes down. It's that simple.",
      },
      foreignFlow: {
        id: "AU_FOREIGN_FLOW",
        name: "澳洲外资流",
        nameEn: "AU Foreign Flow",
        emoji: "🌏",
        oneliner: "全球资金把澳洲当高股息目的地——外资进出=股息吸引力",
        description: "外资持有澳洲股票约40%。全球利率下行=澳洲高股息吸引力上升=外资流入。利率上行=外资流出。",
        ranges: [
          { condition: "全球利率下行+外资流入", meaning: "澳洲高股息成为全球稀缺品——资金流入", color: "green" },
          { condition: "外资净流入", meaning: "正面", color: "green" },
          { condition: "外资净流出", meaning: "全球资金寻求更高收益——澳洲吸引力下降", color: "yellow" },
        ],
        localNote: "Foreigners own ~40% of ASX. They're here for the dividends. When global rates fall, they buy. When rates rise, they sell.",
      },
      risk: {
        id: "AU_RISK",
        name: "澳洲风险",
        nameEn: "AU Risk",
        emoji: "⚠️",
        oneliner: "ASX VIX+中国风险=澳洲的独特风险矩阵",
        description: "A-VIX(澳洲波动率指数)。澳洲最大的独特风险：中国需求（40%出口去中国）。中国GDP放缓=澳洲股市的最大单一风险。",
        ranges: [
          { condition: "A-VIX<15+中国经济正常", meaning: "安全", color: "green" },
          { condition: "A-VIX 15-20", meaning: "轻度紧张", color: "yellow" },
          { condition: "A-VIX>20+中国PMI<50", meaning: "双重风险——中国减速+市场恐慌=澳洲最痛", color: "red" },
        ],
        localNote: "Australia's biggest risk isn't at home — it's in China. 40% of exports go to China. A China slowdown = an Australia recession.",
      },
      macro: {
        id: "AU_MACRO",
        name: "澳洲宏观",
        nameEn: "AU Macro",
        emoji: "📊",
        oneliner: "RBA利率+就业+大宗出口——澳洲经济的三合一",
        description: "RBA现金利率=银行盈利能力+房贷压力的双刃剑。失业率<4%=劳动力紧张。贸易条件(Terms of Trade)=大宗出口价格/进口价格比=国民购买力。",
        ranges: [
          { condition: "RBA暂停加息+就业好", meaning: "软着陆——澳洲最佳宏观环境", color: "green" },
          { condition: "RBA加息+就业恶化", meaning: "滞胀风险——房贷压力+消费萎缩", color: "red" },
        ],
        localNote: "RBA rate decisions are the single biggest driver of Australian bank stocks — and banks are 25% of ASX 200.",
      },
      breadth: {
        id: "AU_BREADTH",
        name: "澳洲市场广度",
        nameEn: "AU Market Breadth",
        emoji: "🌡️",
        oneliner: "矿业涨+银行跌还是银行涨+矿业跌——决定牛市真伪",
        description: "ASX 200中矿业+银行+能源>50%权重。两个板块都涨=真牛市。一个板块涨一个板块跌=板块轮动=结构市。",
        ranges: [
          { condition: "矿业涨+银行涨", meaning: "全面牛市——资源+金融共振。最强信号", color: "green" },
          { condition: "矿业涨+银行跌", meaning: "资源通胀交易——利率预期上升压制银行", color: "yellow" },
          { condition: "矿业跌+银行涨", meaning: "防御轮动——资金从资源转向金融", color: "neutral" },
          { condition: "矿业跌+银行跌", meaning: "全面撤退", color: "red" },
        ],
        localNote: "When both miners AND banks are rising, it's a genuine Australian bull market. One without the other is just sector rotation.",
      },
    },

    // ═══ 英国 🇬🇧 ═══
    GB: {
      country: "英国",
      countryEn: "United Kingdom",
      flag: "🇬🇧",
      indexName: "FTSE 100",
      valuation: {
        id: "GB_VALUATION",
        name: "英国估值分位",
        nameEn: "GB Valuation Percentile",
        emoji: "💰",
        oneliner: "FTSE 100 PE——脱欧后全球最便宜的主要市场",
        description: "FTSE 100 PE约11-13倍=G7最低。但便宜有原因（矿业+石油+银行权重高=天然PE低+英国GDP增长慢）。FTSE 250(本土中盘)PE更有参考价值。",
        ranges: [
          { condition: "PE<10", meaning: "极度低估——危机时(脱欧公投/新冠/LDI危机)", color: "green" },
          { condition: "PE 10-12", meaning: "低估——英国常态=便宜", color: "green" },
          { condition: "PE 12-14", meaning: "正常", color: "neutral" },
          { condition: "PE>14", meaning: "偏贵——通常英镑走强时PE扩张", color: "yellow" },
        ],
        localNote: "FTSE 100 looks cheap because it's full of miners, oil majors and banks. FTSE 250 is the real UK economy — and it's not as cheap.",
        dontTrust: "英镑贬值让FTSE 100看起来更便宜（跨国公司赚外币报表折算多）。英镑跌10%=FTSE PE自动降1倍——不是真的变便宜了。",
      },
      momentum: {
        id: "GB_MOMENTUM",
        name: "英国动量",
        nameEn: "GB Momentum",
        emoji: "🚀",
        oneliner: "FTSE趋势——英镑跌FTSE涨，英镑涨FTSE横。经典脱欧后模式",
        description: "FTSE 100成分股70%+收入来自海外=英镑贬值直接增厚利润。英镑跌10%≈FTSE涨5-8%。汇率永远是第一变量。",
        ranges: [
          { condition: "3M>8%+英镑走弱", meaning: "英镑贬值红利——FTSE经典的上涨模式", color: "green" },
          { condition: "3M>0%", meaning: "正动量", color: "green" },
          { condition: "3M -5%~0%+英镑走强", meaning: "英镑升值压制——正常的逆风", color: "neutral" },
          { condition: "3M<-8%", meaning: "显著下跌——可能英镑急升或全球危机", color: "red" },
        ],
        localNote: "Sterling down = FTSE up. This is the most predictable macro relationship in UK equities. A weak pound IS the UK bull case.",
      },
      foreignFlow: {
        id: "GB_FOREIGN_FLOW",
        name: "英国外资流",
        nameEn: "GB Foreign Flow",
        emoji: "🌏",
        oneliner: "全球并购资金+ETF流——英国是外资最喜欢的收购目标",
        description: "英国上市公司因估值低常被外资收购。外资收购活动活跃=正面信号（外资在为英国资产出高价）。ETF流入也体现被动配置。",
        ranges: [
          { condition: "M&A活跃+ETF净流入", meaning: "外资在真金白银买英国——长期利好", color: "green" },
          { condition: "ETF净流出+M&A冷清", meaning: "外资对英国失去兴趣——熊市信号", color: "red" },
        ],
        localNote: "The best signal for UK stocks is M&A activity. When foreign companies are buying UK firms, it means UK assets are undervalued.",
      },
      risk: {
        id: "GB_RISK",
        name: "英国风险",
        nameEn: "GB Risk",
        emoji: "⚠️",
        oneliner: "FTSE VIX+英镑波动+政治——英国的三维风险",
        description: "FTSE 100波动率指数。政治风险是英国最大的特色风险——脱欧/LDI养老金危机/预算案风波。英镑急贬=双刃剑（股市涨但外资恐慌）。",
        ranges: [
          { condition: "FTSE VIX<15+政治稳定", meaning: "平静——罕见的好状态", color: "green" },
          { condition: "FTSE VIX 15-20", meaning: "正常——但英国政治总有意外", color: "yellow" },
          { condition: "FTSE VIX>20", meaning: "恐慌——通常是政治事件(LDI/预算/大选)", color: "red" },
        ],
        localNote: "The UK has a unique ability to create financial crises out of political decisions. Budget statements and PM changes are the biggest risk events.",
      },
      macro: {
        id: "GB_MACRO",
        name: "英国宏观",
        nameEn: "GB Macro",
        emoji: "📊",
        oneliner: "BOE利率+CPI+GDP——英国经济的核心三角",
        description: "BOE基准利率=英国房贷成本+消费能力的核心变量。CPI>4%=BOE被迫加息=经济承压。服务业PMI>制造业PMI（英国是服务业主导）。",
        ranges: [
          { condition: "CPI回落+BOE暂停", meaning: "加息终点=英国股市的转折点。最佳买入窗口", color: "green" },
          { condition: "CPI>4%+BOE加息中", meaning: "加息周期——英国经济承压。等待加息终点", color: "yellow" },
          { condition: "GDP负增长+通胀顽固", meaning: "滞胀——英国最差宏观环境。远离", color: "red" },
        ],
        localNote: "The Bank of England hiking cycle peak is the single best time to buy UK stocks. Rate cuts are when the rally really starts.",
      },
      breadth: {
        id: "GB_BREADTH",
        name: "英国市场广度",
        nameEn: "GB Market Breadth",
        emoji: "🌡️",
        oneliner: "FTSE 100 vs FTSE 250——谁在涨比涨跌比更重要",
        description: "FTSE 100 (大盘)涨+FTSE 250(中盘)跌=大型跨国公司涨+本土公司跌=英镑贬值模式。FTSE 250比FTSE 100更能反映真英国经济。",
        ranges: [
          { condition: "FTSE 100+250同涨", meaning: "全面牛市——英镑稳定+全球经济复苏。最好状态", color: "green" },
          { condition: "FTSE 100涨+250跌", meaning: "英镑贬值推动——本土经济其实不好", color: "yellow" },
          { condition: "FTSE 250涨+100跌", meaning: "本土复苏——英镑走强+内需改善”。罕见", color: "green" },
          { condition: "两者同跌", meaning: "全面熊市", color: "red" },
        ],
        localNote: "FTSE 250 is the real UK. FTSE 100 is the world. When they diverge, bet on FTSE 250 telling the truth about the UK economy.",
      },
    },

    // ═══ 加拿大 🇨🇦 ═══
    CA: {
      country: "加拿大",
      countryEn: "Canada",
      flag: "🇨🇦",
      indexName: "TSX Composite",
      valuation: {
        id: "CA_VALUATION",
        name: "加拿大估值分位",
        nameEn: "CA Valuation Percentile",
        emoji: "💰",
        oneliner: "TSX PE——能源+金融决定了加拿大整体估值",
        description: "TSX PE约14-16倍。能源+材料+金融>60%权重=天然低PE。剔除这三个板块PE会高3-4倍。跟S&P 500比PE没意义——成分结构完全不同。",
        ranges: [
          { condition: "PE<13", meaning: "低估——通常油价暴跌时出现", color: "green" },
          { condition: "PE 13-15", meaning: "偏低——正常", color: "green" },
          { condition: "PE 15-17", meaning: "合理", color: "neutral" },
          { condition: "PE>17", meaning: "偏贵——注意油价是否也处于高位", color: "yellow" },
        ],
        localNote: "TSX PE looks cheap because of heavy energy/financials weighting. Don't compare it to the S&P 500 — compare it to TSX history.",
      },
      momentum: {
        id: "CA_MOMENTUM",
        name: "加拿大动量",
        nameEn: "CA Momentum",
        emoji: "🚀",
        oneliner: "石油+加元+美股=加拿大股市的三驾马车",
        description: "油价涨=能源板块涨=TSX涨。加元是石油货币——油价和加元同向。美股S&P 500涨=加拿大受益（两国经济高度融合）。",
        ranges: [
          { condition: "油价涨+SPX涨", meaning: "动力全开——加拿大最牛环境", color: "green" },
          { condition: "3M>0%", meaning: "正动量", color: "green" },
          { condition: "油价跌+SPX跌", meaning: "双重打击——加拿大少有的熊市模式", color: "red" },
        ],
        localNote: "Oil and the S&P 500 — those are the two things that matter for TSX. When both are up, Canada wins. When either is down, it's tough.",
      },
      foreignFlow: {
        id: "CA_FOREIGN_FLOW",
        name: "加拿大外资流",
        nameEn: "CA Foreign Flow",
        emoji: "🌏",
        oneliner: "美国投资者买加拿大=TSX最可靠的资金流入",
        description: "美国是加拿大最大的外资来源。美股估值太高时，资金溢出到加拿大（同样的北美经济+更低PE+更高股息）。UN/US利率差是关键。",
        ranges: [
          { condition: "美股贵+资金流入加", meaning: "溢出效应——美国贵了就买加拿大", color: "green" },
          { condition: "资金净流入", meaning: "正面", color: "green" },
          { condition: "资金净流出", meaning: "资金回流美国——通常是美国加息时", color: "yellow" },
        ],
        localNote: "When US stocks look expensive, money flows north to Canada. Same economy, lower PE, higher dividends. This flow is a reliable signal.",
      },
      risk: {
        id: "CA_RISK",
        name: "加拿大风险",
        nameEn: "CA Risk",
        emoji: "⚠️",
        oneliner: "VIXC+油价波动+房地产——加拿大的三重风险",
        description: "S&P/TSX VIX(VIXC)。加拿大独特风险=房地产（房贷/GDP全球最高之一）。房价崩=银行股崩=TSX崩。油价是主要外部风险。",
        ranges: [
          { condition: "VIXC<15+房价稳定", meaning: "安全——加拿大最稳态", color: "green" },
          { condition: "VIXC 15-20", meaning: "轻度紧张", color: "yellow" },
          { condition: "VIXC>20+油价崩", meaning: "高风险——能源+金融双杀模式", color: "red" },
        ],
        localNote: "Canada's biggest risk isn't oil — it's housing. When home prices fall >10%, Canadian bank stocks get crushed, and TSX follows.",
      },
      macro: {
        id: "CA_MACRO",
        name: "加拿大宏观",
        nameEn: "CA Macro",
        emoji: "📊",
        oneliner: "BOC利率+就业+石油出口——加拿大经济三角",
        description: "BoC利率与美国Fed高度同步（利差不能太大否则加元剧烈波动）。就业人数变化=最重要的月度数据。WCS(加拿大重油)价格vs WTI价差=能源出口竞争力。",
        ranges: [
          { condition: "BoC暂停+就业稳定", meaning: "软着陆——加拿大最理想状态", color: "green" },
          { condition: "BoC加息+房价下跌", meaning: "双重压力——房贷成本上升+财富效应消退=消费萎缩", color: "red" },
        ],
        localNote: "Canada can't diverge from the Fed for long. If the BoC cuts while the Fed holds, the loonie crashes — and that's a crisis for importers.",
      },
      breadth: {
        id: "CA_BREADTH",
        name: "加拿大市场广度",
        nameEn: "CA Market Breadth",
        emoji: "🌡️",
        oneliner: "能源+金融+材料——这三个板块必须两个以上在涨才是真牛市",
        description: "TSX三大板块权重>60%。两板块涨=板块轮动牛。三板块同涨=超级牛。只有一板块涨=假强势。",
        ranges: [
          { condition: "能源+金融同涨", meaning: "核心共振——TSX最可靠的牛市模式", color: "green" },
          { condition: "只有一个板块涨", meaning: "单一驱动力——不持久", color: "yellow" },
          { condition: "三大板块同步下跌", meaning: "全面撤退——红色警报", color: "red" },
        ],
        localNote: "In Canada, breadth is simple: energy + financials + materials = 60%+ of TSX. If two of the three are rising, the market is healthy.",
      },
    },

    // ═══ 越南 🇻🇳 ═══
    VN: {
      country: "越南",
      countryEn: "Vietnam",
      flag: "🇻🇳",
      indexName: "VN-Index",
      valuation: {
        id: "VN_VALUATION",
        name: "越南估值分位",
        nameEn: "VN Valuation Percentile",
        emoji: "💰",
        oneliner: "VN-Index PE——越南=最便宜的前沿市场",
        description: "越南PE约12-15倍=前沿市场中最低之一。增长快(GDP 6-7%)但PE低=增长调整后估值(PEG)极低。FOL(外资持股上限)已达的股票通常溢价。",
        ranges: [
          { condition: "PE<12", meaning: "极度低估——流动性危机/政策打压时出现", color: "green" },
          { condition: "PE 12-14", meaning: "偏低——正常", color: "green" },
          { condition: "PE 14-17", meaning: "合理——越南增长快，这个PE不算贵", color: "neutral" },
          { condition: "PE>17", meaning: "偏贵——越南历史上PE>18后回调概率高", color: "red" },
        ],
        localNote: "Việt Nam rẻ nhất trong các thị trường cận biên. PEG < 1 là bình thường ở đây — không có nghĩa là cổ phiếu rẻ.",
        dontTrust: "越南PE低但流动性也低——卖出时可能找不到买家。估值低≠容易赚钱。FOL到顶的股票PE最低但外资不能再买=没有推升动力。",
      },
      momentum: {
        id: "VN_MOMENTUM",
        name: "越南动量",
        nameEn: "VN Momentum",
        emoji: "🚀",
        oneliner: "VN-Index=散户的战场——动量极强但反转也极快",
        description: "越南散户占交易量90%=动量效应极强=追涨杀跌文化极致。上涨时涨到不合理，下跌时跌到不合理。动量交易在越南很有效但止盈止损必须紧。",
        ranges: [
          { condition: "3M>20%", meaning: "火箭模式——散户狂热。谨慎追，止盈要紧", color: "green" },
          { condition: "3M 0-20%", meaning: "正常上涨", color: "green" },
          { condition: "3M -10%~0%", meaning: "回调——越南常态波动", color: "neutral" },
          { condition: "3M<-15%", meaning: "崩盘——散户恐慌踩踏。反弹通常在1-2个月内", color: "red" },
        ],
        localNote: "Nhà đầu tư cá nhân chiếm 90% giao dịch ở Việt Nam. Khi họ sợ, họ bán tất cả. Khi họ tham, họ mua tất cả. Cực đoan là bình thường.",
      },
      foreignFlow: {
        id: "VN_FOREIGN_FLOW",
        name: "越南外资流",
        nameEn: "VN Foreign Flow",
        emoji: "🌏",
        oneliner: "FOL(外资持股上限)=越南市场最独有的信号",
        description: "外资持股上限(Foreign Ownership Limit)49%/100%因公司而异。FOL已达+外资排队买=稀缺性溢价=超强看多信号。FOL放宽=暴利机会。",
        ranges: [
          { condition: "FOL达上限+外资排队", meaning: "稀缺性溢价——最确定的赚钱机会", color: "green" },
          { condition: "外资净买入", meaning: "正面", color: "green" },
          { condition: "外资净卖出", meaning: "外资撤离——通常是ETF调仓或新兴市场出逃", color: "red" },
        ],
        localNote: "Room ngoại (FOL) là tín hiệu quan trọng nhất ở Việt Nam. Cổ phiếu hết room + nước ngoài xếp hàng mua = giá chắc chắn tăng.",
      },
      risk: {
        id: "VN_RISK",
        name: "越南风险",
        nameEn: "VN Risk",
        emoji: "⚠️",
        oneliner: "越南流动性+政策+汇率——前沿市场的三大风险",
        description: "胡志明交易所经常超负荷（成交量超系统容量=交易中断）。政策风险（突然收紧信贷/打压投机）。VND贬值=外资卖出的最大动机。",
        ranges: [
          { condition: "成交量正常+VND稳定", meaning: "正常——越南暂时安全", color: "green" },
          { condition: "成交量异常放大+政策收紧", meaning: "政策打压风险——越南证监会经常干预", color: "red" },
          { condition: "VND大幅贬值", meaning: "外资加速撤离——汇兑损失>股票收益", color: "red" },
        ],
        localNote: "Rủi ro lớn nhất ở Việt Nam không phải là giá cổ phiếu — mà là thanh khoản và chính sách. Sàn HoSE quá tải là chuyện bình thường.",
      },
      macro: {
        id: "VN_MACRO",
        name: "越南宏观",
        nameEn: "VN Macro",
        emoji: "📊",
        oneliner: "FDI+出口+信贷增长——越南经济的三引擎",
        description: "FDI(外国直接投资)=越南经济的真正引擎（三星/LG/富士康）。出口增速>10%=健康。信贷增长=国内流动性的核心指标。",
        ranges: [
          { condition: "FDI增长+出口>10%", meaning: "制造业繁荣——越南金发女孩环境", color: "green" },
          { condition: "出口>0%", meaning: "正常", color: "neutral" },
          { condition: "出口<0%+信贷紧缩", meaning: "双重收缩——越南经济下行周期", color: "red" },
        ],
        localNote: "FDI là động cơ thực sự của kinh tế Việt Nam. Khi Samsung và Foxconn mở rộng nhà máy, VN-Index tăng. Khi họ cắt giảm, VN-Index giảm.",
      },
      breadth: {
        id: "VN_BREADTH",
        name: "越南市场广度",
        nameEn: "VN Market Breadth",
        emoji: "🌡️",
        oneliner: "散户占90%→涨跌比是越南市场最真实的情绪温度计",
        description: "散户驱动的市场=涨跌比直接反映恐慌/贪婪。涨跌比>2=贪婪（注意见顶）。涨跌比<0.3=极度恐慌（可能见底）。",
        ranges: [
          { condition: "涨跌比1.5-2+成交量温和", meaning: "健康上涨——最好的状态", color: "green" },
          { condition: "涨跌比>3+成交量暴增", meaning: "散户狂热——历史上几乎每次都是顶部信号", color: "red" },
          { condition: "涨跌比<0.3", meaning: "恐慌性抛售——散户在踩踏。底部区域", color: "green" },
        ],
        localNote: "Khi tất cả các cổ phiếu đều tăng và volume vọt lên, đó là lúc bán. Khi tất cả đều giảm và không ai muốn mua, đó là lúc mua.",
      },
    },

    // ═══ 印尼 🇮🇩 ═══
    ID: {
      country: "印尼",
      countryEn: "Indonesia",
      flag: "🇮🇩",
      indexName: "IDX Composite (IHSG)",
      valuation: {
        id: "ID_VALUATION",
        name: "印尼估值分位",
        nameEn: "ID Valuation Percentile",
        emoji: "💰",
        oneliner: "IHSG PE——东南亚最大经济体，估值合理偏高就是正常",
        description: "IHSG PE约14-17倍=新兴市场中偏贵。但印尼GDP增速5%+年轻人口结构支撑估值溢价。银行+消费是核心板块。",
        ranges: [
          { condition: "PE<13", meaning: "低估——通常是卢比危机时", color: "green" },
          { condition: "PE 13-15", meaning: "偏低——买入区间", color: "green" },
          { condition: "PE 15-18", meaning: "正常——印尼常态偏高", color: "neutral" },
          { condition: "PE>18", meaning: "偏贵——连印尼都觉得贵了", color: "red" },
        ],
        localNote: "IHSG jarang murah. Kalau PER di bawah 13, itu biasanya karena krisis Rupiah dan itu momen terbaik untuk beli.",
      },
      momentum: {
        id: "ID_MOMENTUM",
        name: "印尼动量",
        nameEn: "ID Momentum",
        emoji: "🚀",
        oneliner: "IHSG=大宗商品+国内消费——双引擎驱动",
        description: "印尼是煤炭+棕榈油+镍的最大出口国之一。商品超级周期=印尼股市超级牛市。国内消费升级(中产阶级扩大)=长期动量。",
        ranges: [
          { condition: "商品价涨+3M>10%", meaning: "商品驱动牛市——印尼最赚钱的周期", color: "green" },
          { condition: "3M>0%", meaning: "正动量——可能是消费升级的长期趋势", color: "green" },
          { condition: "3M<-10%", meaning: "回调——大概率商品价格暴跌导致", color: "red" },
        ],
        localNote: "Indonesia adalah supermarket komoditas. Saat harga batu bara dan sawit naik, IHSG naik. Saat jatuh, IHSG jatuh.",
      },
      foreignFlow: {
        id: "ID_FOREIGN_FLOW",
        name: "印尼外资流",
        nameEn: "ID Foreign Flow",
        emoji: "🌏",
        oneliner: "外资持有印尼股票>40%——外资一动，IHSG抖三抖",
        description: "外资持有印尼流通股市值超40%——是所有东南亚市场中外资占比最高的之一。外资连续买入=IHSG主升浪。外资卖出=几乎必然下跌。",
        ranges: [
          { condition: "外资连买4周", meaning: "外资驱动牛市——跟风就行", color: "green" },
          { condition: "外资净买入", meaning: "正面", color: "green" },
          { condition: "外资净卖出<2周", meaning: "短期获利了结——正常", color: "neutral" },
          { condition: "外资连卖4周", meaning: "外资撤退——别挡路", color: "red" },
        ],
        localNote: "Asing pegang 40%+ IHSG. Ikuti arus asing — kalau mereka beli, ikut beli. Kalau mereka jual, jangan melawan.",
      },
      risk: {
        id: "ID_RISK",
        name: "印尼风险",
        nameEn: "ID Risk",
        emoji: "⚠️",
        oneliner: "卢比贬值+资本外流=印尼经典危机模式",
        description: "IDR是新兴市场最脆弱的货币之一——美联储加息=IDR贬值=外资卖出=股市崩盘。印尼央行(BI)干预=短期维稳但消耗外汇储备。",
        ranges: [
          { condition: "IDR稳定+CDS低", meaning: "安全——外资满意印尼宏观", color: "green" },
          { condition: "IDR贬值>5%+外资流出", meaning: "中风险——需要密切关注", color: "yellow" },
          { condition: "IDR暴跌>10%+外资加速撤", meaning: "危机模式——别捡便宜。等卢比稳定再进场", color: "red" },
        ],
        localNote: "Rupiah adalah kunci. Kalau Rupiah jatuh, jangan beli saham Indonesia dulu — tunggu Rupiah stabil baru masuk.",
      },
      macro: {
        id: "ID_MACRO",
        name: "印尼宏观",
        nameEn: "ID Macro",
        emoji: "📊",
        oneliner: "BI利率+贸易顺差+消费——印尼宏观三大件",
        description: "BI 7天逆回购利率=政策利率。商品贸易顺差=印尼经常账户的最强支撑。消费信心指数=国内需求的最好领先指标。",
        ranges: [
          { condition: "贸易顺差+BI稳定", meaning: "最健康状态——经常账户盈余+货币政策稳定", color: "green" },
          { condition: "贸易顺差缩小+BI加息", meaning: "压力上升——加息+出口减少=双重打击", color: "red" },
        ],
        localNote: "Surplus perdagangan adalah tameng Indonesia. Selama ekspor komoditas kuat, Rupiah aman dan IHSG bisa naik.",
      },
      breadth: {
        id: "ID_BREADTH",
        name: "印尼市场广度",
        nameEn: "ID Market Breadth",
        emoji: "🌡️",
        oneliner: "银行+消费两大板块必须同步——单腿走不远",
        description: "IHSG由银行(>30%)+消费(>15%)驱动。银行涨+消费跌=利好只在金融体系=不健康。银行涨+消费涨=全民牛市。",
        ranges: [
          { condition: "银行涨+消费涨", meaning: "全市场共振——印尼最可靠的牛市模式", color: "green" },
          { condition: "银行涨+消费跌", meaning: "宏观利好未传导居民——不健康", color: "yellow" },
          { condition: "银行跌+消费跌", meaning: "全面撤退", color: "red" },
        ],
        localNote: "Bank dan konsumsi harus naik bareng. Kalau cuma bank yang naik, itu bukan bull market — itu cuma window dressing.",
      },
    },

    // ═══ 马来西亚 🇲🇾 ═══
    MY: {
      country: "马来西亚",
      countryEn: "Malaysia",
      flag: "🇲🇾",
      indexName: "KLCI",
      valuation: {
        id: "MY_VALUATION",
        name: "马来西亚估值分位",
        nameEn: "MY Valuation Percentile",
        emoji: "💰",
        oneliner: "KLCI PE——东南亚最被忽视的市场，常年低估值",
        description: "KLCI PE约13-15倍=东南亚最低之一。银行+棕榈油+公用事业=稳定但没增长=低PE合理。高股息率(>4%)=买入理由。",
        ranges: [
          { condition: "PE<12", meaning: "低估——通常MYR崩盘时出现", color: "green" },
          { condition: "PE 12-14", meaning: "偏低——马来西亚就是便宜", color: "green" },
          { condition: "PE 14-16", meaning: "正常", color: "neutral" },
          { condition: "PE>16", meaning: "偏贵——大选行情或棕榈油超级周期", color: "yellow" },
        ],
        localNote: "Malaysia is cheap for a reason — low growth, policy uncertainty, and brain drain. Buy for dividends, not for growth.",
      },
      momentum: {
        id: "MY_MOMENTUM",
        name: "马来西亚动量",
        nameEn: "MY Momentum",
        emoji: "🚀",
        oneliner: "KLCI=棕榈油+MYR+政治——三个变量一个都不能少",
        description: "棕榈油价涨=种植板块涨=KLCI第一大驱动力。MYR(马币)强=外资有信心。大选前6个月KLCI通常涨(政策糖果)。",
        ranges: [
          { condition: "棕榈油涨+MYR稳", meaning: "双利好——最可能上涨的环境", color: "green" },
          { condition: "3M>0%", meaning: "正动量", color: "green" },
          { condition: "棕榈油跌+MYR跌", meaning: "双杀——KLCI最惨模式", color: "red" },
        ],
        localNote: "Harga sawit adalah nadi KLCI. Bila harga sawit naik, KLCI naik. Hubungan ini sudah berlangsung 30 tahun.",
      },
      foreignFlow: {
        id: "MY_FOREIGN_FLOW",
        name: "马来西亚外资流",
        nameEn: "MY Foreign Flow",
        emoji: "🌏",
        oneliner: "外资对马来西亚又爱又恨——高股息=爱，政治动荡=恨",
        description: "外资持有大马国债>股市（利差交易）。外资买卖大马股票的决定因素=MYR汇率预期+棕榈油趋势+政治稳定度。",
        ranges: [
          { condition: "MYR升值预期+棕榈油涨+外资买", meaning: "三重利好——外资格外青睐", color: "green" },
          { condition: "MYR贬值+政治不稳", meaning: "外资加速出走——别对抗趋势", color: "red" },
        ],
        localNote: "Foreigners hold more Malaysian bonds than stocks. When they sell MYR bonds, they sell stocks too. Watch bond flows as a leading indicator.",
      },
      risk: {
        id: "MY_RISK",
        name: "马来西亚风险",
        nameEn: "MY Risk",
        emoji: "⚠️",
        oneliner: "MYR+政治+棕榈油——马来西亚风险铁三角",
        description: "1MDB级别的政治丑闻可以让KLCI暴跌20%+。MYR是亚洲最被操控的货币之一（资本管制历史）。棕榈油被欧盟抵制=长期风险。",
        ranges: [
          { condition: "政局稳定+MYR稳定", meaning: "正常——马来西亚的最佳状态", color: "green" },
          { condition: "政治丑闻/MYR干预", meaning: "政治风险上升——减仓观望", color: "red" },
        ],
        localNote: "Risiko politik adalah risiko terbesar di Malaysia. Skandal 1MDB menjatuhkan KLCI 20%+. Jangan underestimate politik.",
      },
      macro: {
        id: "MY_MACRO",
        name: "马来西亚宏观",
        nameEn: "MY Macro",
        emoji: "📊",
        oneliner: "BNM利率+出口+财政——马来西亚经济的均衡器",
        description: "BNM隔夜政策利率(OPR)=银行业盈利能力的关键。电子+棕榈油出口=外汇收入两大支柱。财政赤字/GDP<3.5%=国际评级安全线。",
        ranges: [
          { condition: "OPR稳定+出口增长", meaning: "健康——马来西亚最佳宏观状态", color: "green" },
          { condition: "出口下滑+财政赤字>4%", meaning: "压力——评级可能下调风险", color: "red" },
        ],
        localNote: "Ekonomi Malaysia sangat terbuka. Ekspor adalah segalanya. Bila ekspor turun, semuanya turun.",
      },
      breadth: {
        id: "MY_BREADTH",
        name: "马来西亚市场广度",
        nameEn: "MY Market Breadth",
        emoji: "🌡️",
        oneliner: "KLCI 30只+中小盘——中小盘活跃才是真市场",
        description: "KLCI只有30只成分股。看FBM Small Cap+FBM ACE(创业板)比看KLCI涨跌比更有意义。中小盘活跃=散户在参与=真牛市。",
        ranges: [
          { condition: "KLCI涨+ACE涨", meaning: "全面牛市——大盘+散户齐活跃", color: "green" },
          { condition: "KLCI涨+ACE跌", meaning: "机构独舞——散户不在。假涨", color: "yellow" },
          { condition: "KLCI跌+ACE跌", meaning: "全面下跌", color: "red" },
        ],
        localNote: "ACE Market adalah penunjuk sentimen runcit terbaik di Malaysia. Kalau ACE naik, maknanya pelabur runcit sedang aktif — itu bull market sebenar.",
      },
    },
  },

  // ══════════════════════════════════════════════════════
  // PART B: 12 宏观因子（全球通用）
  // ══════════════════════════════════════════════════════

  macro: {
    sectionTitle: "🌐 全球宏观因子",
    sectionTitleEn: "Global Macro Factors",
    sectionSubtitle: "12个跨国可比宏观指标——理解每个国家的经济背景温度",

    GDP_REAL: {
      id: "GDP_REAL",
      name: "GDP实际增速",
      nameEn: "Real GDP Growth",
      emoji: "📈",
      category: "增长",
      oneliner: "剔除通胀后经济真实增长了多少——最基础的宏观指标",
      description: "GDP同比实际增速（已扣除价格因素）。发达国家2-3%正常，新兴市场5-7%正常。增速<0=衰退。增速>同国历史平均+2%=过热。",
      ranges: [
        { condition: "增速>趋势+2%", meaning: "经济过热——通胀压力上升。央行可能加息", color: "yellow" },
        { condition: "增速在趋势±1%", meaning: "正常增长——金发女孩", color: "green" },
        { condition: "增速<趋势-2%", meaning: "显著放缓——接近衰退", color: "yellow" },
        { condition: "增速<0", meaning: "衰退——GDP连续两季负增长=技术性衰退", color: "red" },
      ],
      dontTrust: "GDP是回顾性数据——告诉你的是过去的事。股市已在6-12个月前定价了GDP。不要用GDP做短期择时。领先指标(PMI/消费者信心)比GDP更有用。",
      publishFrequency: "季度",
      source: "各国统计局",
    },
    CPI_YOY: {
      id: "CPI_YOY",
      name: "CPI同比",
      nameEn: "CPI YoY",
      emoji: "🏷️",
      category: "物价",
      oneliner: "一篮子商品服务比一年前贵了多少——你的购买力被吞噬的速度",
      description: "CPI同比增长率。发达市场目标2%，新兴市场容忍3-5%。CPI>目标×2=央行被迫加息=利空风险资产。<0=通缩=经济大麻烦。",
      ranges: [
        { condition: "CPI在目标±0.5%", meaning: "价格稳定——央行最舒服。利好资产价格", color: "green" },
        { condition: "CPI目标-目标×1.5", meaning: "轻微通胀——央行观望。中性", color: "neutral" },
        { condition: "CPI>目标×2", meaning: "高通胀——央行被迫大幅加息。风险资产大利空", color: "red" },
        { condition: "CPI<0", meaning: "通缩——比通胀更可怕。日本失去的30年的根本原因", color: "red" },
      ],
      dontTrust: "CPI不是真实的「你的通胀」——你的消费篮子和CPI篮子不一样。CPI不含房价(含租金)。房价翻倍但CPI可能只有3%。另外CPI权重每几年调整一次，降低了真实通胀感。",
      publishFrequency: "月度",
      source: "各国统计局",
    },
    PMI_MANUF: {
      id: "PMI_MANUF",
      name: "制造业PMI",
      nameEn: "Manufacturing PMI",
      emoji: "🏭",
      category: "增长",
      oneliner: "采购经理人指数——宏观经济最及时的领先指标",
      description: "PMI>50=制造业扩张。<50=收缩。是全球经济周期最敏感的实时指标。PMI连续3月下行=经济减速预警。PMI连续3月上行=复苏确认。",
      ranges: [
        { condition: "PMI>55", meaning: "强劲扩张——经济加速", color: "green" },
        { condition: "PMI 50-55", meaning: "温和扩张——正常", color: "green" },
        { condition: "PMI 48-50", meaning: "轻微收缩——警戒线边缘", color: "yellow" },
        { condition: "PMI<48", meaning: "显著收缩=经济衰退高风险", color: "red" },
      ],
      dontTrust: "PMI是软数据（问卷调查情绪）不是硬数据（实际产量）。有时候PMI下降是因为公司变悲观而不是因为订单真的少了。结合工业产出和用电量验证。",
      publishFrequency: "月度（每月1-3日）",
      source: "S&P Global / Markit / ISM",
    },
    UNEMPLOYMENT: {
      id: "UNEMPLOYMENT",
      name: "失业率",
      nameEn: "Unemployment Rate",
      emoji: "👷",
      category: "就业",
      oneliner: "想工作但没工作的人占比——经济的最大滞后指标",
      description: "失业率是最滞后的经济指标——经济衰退开始后失业率才上升，复苏开始后失业率才下降。但失业率突然跳升（>0.5%/月）=衰退已来。",
      ranges: [
        { condition: "失业率<自然失业率", meaning: "劳动力紧张——工资上升压力=通胀风险", color: "yellow" },
        { condition: "失业率接近自然率", meaning: "充分就业——正常", color: "green" },
        { condition: "失业率>自然率+1%", meaning: "劳动力松弛——经济低于潜力", color: "yellow" },
        { condition: "失业率跳升>0.5%/月", meaning: "衰退确认——已经开始了", color: "red" },
      ],
      dontTrust: "失业率被严重美化了——放弃找工作的人不算「失业」。真正的未充分利用率(U-6在美国)通常比官方失业率高50-100%。低失业率不一定是好信号——可能是低质量就业。",
      publishFrequency: "月度",
      source: "各国统计局",
    },
    POLICY_RATE: {
      id: "POLICY_RATE",
      name: "政策利率",
      nameEn: "Policy Rate",
      emoji: "🏦",
      category: "货币",
      oneliner: "央行基准利率——一切资产定价的锚",
      description: "央行设定的基准利率（Fed Funds Rate/ECB Refi Rate等）。利率↑=资金成本↑=PE压缩=利空股市。利率↓=资金便宜=PE扩张=利好股市。利率方向比绝对水平重要。",
      ranges: [
        { condition: "降息周期中", meaning: "货币宽松——利好风险资产。利率下降=PE扩张", color: "green" },
        { condition: "利率稳定", meaning: "持有——观察数据等央行信号", color: "neutral" },
        { condition: "加息周期中", meaning: "货币紧缩——利空风险资产。利率上升=PE压缩+经济减速", color: "red" },
        { condition: "加息末端（预计将暂停）", meaning: "拐点信号——历史上暂停加息后股市通常反弹", color: "green" },
      ],
      dontTrust: "Never fight the Fed——但是要区分「加息中」和「加息末」。最后一次加息到第一次降息之间，股市往往已经在涨了。不要等到降息才买。",
      publishFrequency: "央行会议(6-8周一次)",
      source: "各国央行",
    },
    M2_YOY: {
      id: "M2_YOY",
      name: "M2货币供应增速",
      nameEn: "M2 Money Supply YoY",
      emoji: "💸",
      category: "货币",
      oneliner: "市面上的钱多了多少——流动性盛筵的尺度",
      description: "M2(广义货币)同比增速。M2增速-GDP增速=超发货币=最终会流向资产价格(股市/房地产/商品)。M2增速急降=流动性枯竭=利空所有资产。",
      ranges: [
        { condition: "M2增速>GDP+5%", meaning: "大水漫灌——资产价格有强力支撑。但注意通胀风险", color: "green" },
        { condition: "M2增速≈GDP增速", meaning: "货币中性——正常", color: "neutral" },
        { condition: "M2增速<GDP增速", meaning: "货币紧缩——流动性不足。资产价格承压", color: "yellow" },
        { condition: "M2增速<0", meaning: "绝对收缩——极罕见。历史上与深度衰退/金融危机伴生", color: "red" },
      ],
      dontTrust: "货币乘数会变——即使M2大增，如果货币流通速度(Velocity)下降，实际通胀可能不高。2020年M2暴增但通缩了两年=流动性陷阱。M2→资产价格不是直接的——要看钱流去哪。",
      publishFrequency: "月度",
      source: "各国央行",
    },
    IND_PROD_YOY: {
      id: "IND_PROD_YOY",
      name: "工业产出增速",
      nameEn: "Industrial Production YoY",
      emoji: "⚙️",
      category: "增长",
      oneliner: "工厂实际产出了多少——经济的硬数据(非问卷)",
      description: "工业产出同比增速=制造业+矿业+公用事业的实际产出变化。是硬数据——不是问卷调查是实际产量。对制造业导向经济体(中日韩德)尤其重要。",
      ranges: [
        { condition: "增速>5%", meaning: "强劲增长——制造业繁荣", color: "green" },
        { condition: "增速 0-5%", meaning: "温和增长——正常", color: "green" },
        { condition: "增速 -3%~0%", meaning: "轻度收缩——预警", color: "yellow" },
        { condition: "增速<-3%", meaning: "显著收缩——工业衰退", color: "red" },
      ],
      dontTrust: "工业产出数据经常大幅修正——初值和终值差距可以很大。库存周期会扭曲工业产出——去库存时产出下降不一定代表需求下降。结合零售销售看终端需求。",
      publishFrequency: "月度",
      source: "各国统计局",
    },
    RETAIL_SALES: {
      id: "RETAIL_SALES",
      name: "零售销售增速",
      nameEn: "Retail Sales YoY",
      emoji: "🛒",
      category: "增长",
      oneliner: "消费者花了多少钱——经济70%=消费。消费=一切",
      description: "零售销售同比增速=消费者支出的最直接衡量。增速>5%=消费旺盛=经济好。<0%=消费萎缩=衰退信号。消费者信心+零售销售=最完整的消费画面。",
      ranges: [
        { condition: "增速>5%", meaning: "消费旺盛——经济引擎在高速运转", color: "green" },
        { condition: "增速 0-5%", meaning: "正常消费——温和增长", color: "neutral" },
        { condition: "增速<0", meaning: "消费萎缩——经济在减速。严重时=衰退前兆", color: "red" },
      ],
      dontTrust: "零售销售不含服务消费（餐饮/旅游/医疗）——现代经济中服务消费占比越来越高。另外，通胀可能让零售销售「增长」而实际量在下降。看实际零售销售(剔除通胀)更有意义。",
      publishFrequency: "月度",
      source: "各国统计局",
    },
    TRADE_BALANCE_GDP: {
      id: "TRADE_BALANCE_GDP",
      name: "贸易盈余/GDP",
      nameEn: "Trade Balance / GDP",
      emoji: "🚢",
      category: "对外",
      oneliner: "出口比进口多还是少——国家在赚钱还是花钱",
      description: "贸易差额÷GDP。正=顺差(赚钱)。负=逆差(花钱)。>5%=大量顺差(中国/德国/沙特)。<-5%=大量逆差(美国/英国)。长期逆差=债务累积+货币贬值压力。",
      ranges: [
        { condition: "顺差>5%GDP", meaning: "强顺差——货币有升值压力。外汇储备积累", color: "green" },
        { condition: "顺差0-5%GDP", meaning: "小幅顺差——健康", color: "green" },
        { condition: "逆差0-3%GDP", meaning: "小幅逆差——可接受", color: "neutral" },
        { condition: "逆差>5%GDP", meaning: "大额逆差——货币长期贬值压力。依赖外资流入", color: "red" },
      ],
      dontTrust: "贸易顺差不一定是好事——可能是国内消费太弱，只能靠出口。贸易逆差不一定是坏事——美国逆差是因为美元是全球储备货币。顺差/逆差要看原因，不是看数字。",
      publishFrequency: "月度",
      source: "各国海关/统计局",
    },
    CURRENT_ACCOUNT_GDP: {
      id: "CURRENT_ACCOUNT_GDP",
      name: "经常账户/GDP",
      nameEn: "Current Account / GDP",
      emoji: "🌐",
      category: "对外",
      oneliner: "国家在世界上是赚钱还是借钱——比贸易差额更全面的度量",
      description: "经常账户差额=贸易差额+服务+投资收益+转移支付。赤字>5%GDP=严重依赖外资=脆弱(新兴市场尤甚)。盈余>5%=过度储蓄=内需不足。",
      ranges: [
        { condition: "盈余>3%GDP", meaning: "对外盈余——国家在积累对外资产", color: "green" },
        { condition: "盈余0-3%/赤字0-3%", meaning: "大致平衡——健康", color: "green" },
        { condition: "赤字3-5%GDP", meaning: "对外赤字偏高——需要外资持续流入", color: "yellow" },
        { condition: "赤字>5%GDP", meaning: "危险——历史上新兴市场经常账户赤字>5%+外汇储备不足=货币危机范式", color: "red" },
      ],
      dontTrust: "经常账户盈余国家不一定安全——中国盈余巨大但资本账户管制=钱不一定留在国内。日本盈余巨大但GDP停滞30年。盈余=储蓄过多=消费不足=经济增长慢。",
      publishFrequency: "季度",
      source: "各国央行/IMF",
    },
    FX_RESERVES: {
      id: "FX_RESERVES",
      name: "外汇储备",
      nameEn: "FX Reserves",
      emoji: "🏦",
      category: "对外",
      oneliner: "央行账户里有多少外币——国家的弹药库",
      description: "外汇储备(美元计)。覆盖进口月数>6=安全(新兴市场标准)。>12=过度储备。<3=危险（1997亚洲金融危机所有受创国外储<3个月进口）。储备骤降=中央银行在卖外汇托市=危机信号。",
      ranges: [
        { condition: "覆盖进口>12个月", meaning: "储备充足——抵御外部冲击能力强", color: "green" },
        { condition: "覆盖进口6-12个月", meaning: "正常——新兴市场标准安全线", color: "green" },
        { condition: "覆盖进口3-6个月", meaning: "偏低——外储紧张。加息/资本管制可能", color: "yellow" },
        { condition: "覆盖进口<3个月", meaning: "极度危险——1997亚洲金融危机重现", color: "red" },
      ],
      dontTrust: "外汇储备多不一定安全——如果大部分是借来的(通过外债)而不是赚来的(通过贸易顺差)。中国外储3万亿但大部分是长期贸易顺差积累=真安全。土耳其外储看起来多但大部分是swap借来的=假安全。",
      publishFrequency: "月度",
      source: "各国央行/IMF",
    },
    GOVT_DEBT_GDP: {
      id: "GOVT_DEBT_GDP",
      name: "政府债务/GDP",
      nameEn: "Government Debt / GDP",
      emoji: "📊",
      category: "对外",
      oneliner: "政府欠了多少钱——国家的长期健康体检",
      description: "政府总债务÷GDP。<60%=健康(EU马斯特里赫特标准)。60-100%=中等。>100%=高负债(日本例外—250%但没问题因为大部分本国持有)。发达市场>新兴市场的安全线不同。",
      ranges: [
        { condition: "<60%GDP", meaning: "健康——财政空间充裕", color: "green" },
        { condition: "60-100%GDP", meaning: "中度——需要关注但发达国家通常无虞", color: "neutral" },
        { condition: ">100%GDP(发达)", meaning: "高负债——日本案例证明不是末日但限制政策空间", color: "yellow" },
        { condition: ">100%GDP(新兴)+外汇债务占比高", meaning: "危险——新兴市场高债务+外币债=违约范式", color: "red" },
      ],
      dontTrust: "债务/GDP不是越高越危险——日本250%没事因为95%是国内持有+有自己的央行可以印钱。阿根廷50%就违约了因为外汇债务占比高。债务的货币结构和持有者比总金额更重要。",
      publishFrequency: "季度/年度",
      source: "IMF/各国财政部",
    },
  },

  // ── 工具函数 ──
  getMarketFactors(marketId: string) {
    const m = this.markets[marketId as keyof typeof this.markets];
    if (!m) return null;
    const { country, countryEn, flag, indexName, ...factors } = m;
    return factors;
  },
  getAllMarketIds(): string[] {
    return Object.keys(this.markets);
  },
  getMacroFactor(id: string) {
    return this.macro[id as keyof typeof this.macro] ?? null;
  },
  getAllMacroIds(): string[] {
    return Object.keys(this.macro).filter(k => k !== 'sectionTitle' && k !== 'sectionTitleEn' && k !== 'sectionSubtitle');
  },
};

export default GLOBAL_84_PLUS_12_FACTOR_COPY;
