// ══ R277 QClaw Task 2 (先做): 14市场分类标签 (2h) ══
// 交付: src/lib/market/global-market-labels-r277.ts
//
// 14市场: JP IN KR TW EU BR SA SG AU GB CA VN ID MY
// + 12宏观标签
// 设计原则: 本土地道命名、分类层次清晰、可搜索

export const GLOBAL_MARKET_LABELS = {

  // ══ 14市场本体标签 ══
  markets: {
    JP: {
      id: "JP",
      flag: "🇯🇵",
      name: "日本",
      nameEn: "Japan",
      nameNative: "日本",
      exchange: "東京証券取引所",
      exchangeShort: "東証",
      index: "日経225",
      indexCode: "N225",
      currency: "JPY",
      currencyName: "円",
      timezone: "Asia/Tokyo",
      marketHours: "9:00-11:30 / 12:30-15:00 JST",
      description: "全球第三大股市。央行ETF购买=最大特色。日元汇率=外资最大顾虑。",
      keyTraits: ["央行直接购股", "日元敏感", "出口导向"],
    },
    IN: {
      id: "IN",
      flag: "🇮🇳",
      name: "印度",
      nameEn: "India",
      nameNative: "भारत",
      exchange: "NSE / BSE",
      exchangeShort: "NSE",
      index: "Nifty 50",
      indexCode: "NIFTY50",
      currency: "INR",
      currencyName: "₹",
      timezone: "Asia/Kolkata",
      marketHours: "9:15-15:30 IST",
      description: "全球增长最快的经济体。FII/DII资金流向=最核心指标。卢比贬值=隐形成本。",
      keyTraits: ["FII驱动", "卢比波动", "人口红利"],
    },
    KR: {
      id: "KR",
      flag: "🇰🇷",
      name: "韩国",
      nameEn: "South Korea",
      nameNative: "한국",
      exchange: "한국거래소",
      exchangeShort: "KRX",
      index: "KOSPI",
      indexCode: "KOSPI",
      currency: "KRW",
      currencyName: "₩",
      timezone: "Asia/Seoul",
      marketHours: "9:00-15:30 KST",
      description: "半导体=国家命脉。三星电子占KOSPI权重的20%+。外资买卖三星=大盘方向。",
      keyTraits: ["半导体集中", "外资敏感", "地缘风险"],
    },
    TW: {
      id: "TW",
      flag: "🇹🇼",
      name: "台湾",
      nameEn: "Taiwan",
      nameNative: "臺灣",
      exchange: "臺灣證券交易所",
      exchangeShort: "TWSE",
      index: "加權指數",
      indexCode: "TAIEX",
      currency: "TWD",
      currencyName: "NT$",
      timezone: "Asia/Taipei",
      marketHours: "9:00-13:30 TST",
      description: "台积电≈台灣大盘。“買台積電就是買加權指數”。三大法人=外资+投信+自营商。",
      keyTraits: ["台积电一家独大", "三大法人", "海峡风险溢价"],
    },
    EU: {
      id: "EU",
      flag: "🇪🇺",
      name: "欧洲",
      nameEn: "Europe",
      nameNative: "Europe",
      exchange: "泛欧交易所 / 德交所",
      exchangeShort: "STOXX",
      index: "STOXX 600",
      indexCode: "SXXP",
      currency: "EUR",
      currencyName: "€",
      timezone: "Europe/Paris",
      marketHours: "9:00-17:30 CET (各国有差)",
      description: "600家公司跨17国。不是一个统一市场=国别风险仍在。DAX+FTSE+CAC三分天下。",
      keyTraits: ["多国分散", "银行权重高", "政治风险（脱欧/选举）"],
    },
    BR: {
      id: "BR",
      flag: "🇧🇷",
      name: "巴西",
      nameEn: "Brazil",
      nameNative: "Brasil",
      exchange: "B3",
      exchangeShort: "B3",
      index: "Ibovespa",
      indexCode: "IBOV",
      currency: "BRL",
      currencyName: "R$",
      timezone: "America/Sao_Paulo",
      marketHours: "10:00-17:30 BRT",
      description: "大宗商品+政治=巴西股市的DNA。Petrobras+Vale两只股决定大盘一半方向。",
      keyTraits: ["商品依赖", "政治风险极高", "BRL崩盘=股市崩盘"],
    },
    SA: {
      id: "SA",
      flag: "🇸🇦",
      name: "沙特",
      nameEn: "Saudi Arabia",
      nameNative: "المملكة",
      exchange: "Tadawul",
      exchangeShort: "TADAWUL",
      index: "TASI",
      indexCode: "TASI",
      currency: "SAR",
      currencyName: "SR",
      timezone: "Asia/Riyadh",
      marketHours: "10:00-15:00 AST (周日-周四)",
      description: "石油=一切。油价$80以上=沙特财政宽松+股市涨。Aramco占Tadawul权重超30%。",
      keyTraits: ["油价绑定", "周日开盘", "Aramco一家独大"],
    },
    SG: {
      id: "SG",
      flag: "🇸🇬",
      name: "新加坡",
      nameEn: "Singapore",
      nameNative: "Singapore",
      exchange: "SGX",
      exchangeShort: "SGX",
      index: "STI (海峡时报指数)",
      indexCode: "STI",
      currency: "SGD",
      currencyName: "S$",
      timezone: "Asia/Singapore",
      marketHours: "9:00-17:00 SGT",
      description: "亚洲金融中心。REITs之都=40+只REITs。银行三巨头(DBS/OCBC/UOB)权重极高。",
      keyTraits: ["REITs之都", "银行三巨头", "亚洲美元枢纽"],
    },
    AU: {
      id: "AU",
      flag: "🇦🇺",
      name: "澳洲",
      nameEn: "Australia",
      nameNative: "Australia",
      exchange: "ASX",
      exchangeShort: "ASX",
      index: "ASX 200",
      indexCode: "AS51",
      currency: "AUD",
      currencyName: "A$",
      timezone: "Australia/Sydney",
      marketHours: "10:00-16:00 AEST",
      description: "矿业+银行=澳洲市场的两条腿。BHP+Rio Tinto+四大银行=ASX 200半壁江山。",
      keyTraits: ["矿业银行双寡头", "AUD商品货币", "高股息文化"],
    },
    GB: {
      id: "GB",
      flag: "🇬🇧",
      name: "英国",
      nameEn: "United Kingdom",
      nameNative: "United Kingdom",
      exchange: "London Stock Exchange",
      exchangeShort: "LSE",
      index: "FTSE 100",
      indexCode: "UKX",
      currency: "GBP",
      currencyName: "£",
      timezone: "Europe/London",
      marketHours: "8:00-16:30 GMT",
      description: "老牌金融中心。FTSE 100以矿业、石油、银行为主=实际是个新兴市场指数。高股息股票集中地。",
      keyTraits: ["矿业石油权重大", "高股息", "英镑汇率=外资进出开关"],
    },
    CA: {
      id: "CA",
      flag: "🇨🇦",
      name: "加拿大",
      nameEn: "Canada",
      nameNative: "Canada",
      exchange: "Toronto Stock Exchange",
      exchangeShort: "TSX",
      index: "TSX Composite",
      indexCode: "TSX",
      currency: "CAD",
      currencyName: "C$",
      timezone: "America/Toronto",
      marketHours: "9:30-16:00 EST",
      description: "能源+金融+矿业的天下。TSX中能源和材料占30%+。石油价格≈加拿大股市的隐形主力。",
      keyTraits: ["能源矿业主导", "加元=石油货币", "美股联动极强"],
    },
    VN: {
      id: "VN",
      flag: "🇻🇳",
      name: "越南",
      nameEn: "Vietnam",
      nameNative: "Việt Nam",
      exchange: "HoSE / HNX",
      exchangeShort: "HoSE",
      index: "VN-Index",
      indexCode: "VNINDEX",
      currency: "VND",
      currencyName: "₫",
      timezone: "Asia/Ho_Chi_Minh",
      marketHours: "9:00-14:45 ICT",
      description: "东南亚最活跃的前沿市场。外资持股上限(FOL)已达的股票=最受欢迎。散户占比90%=波动极大。",
      keyTraits: ["FOL达上限信号", "散户主导", "出口导向制造"],
    },
    ID: {
      id: "ID",
      flag: "🇮🇩",
      name: "印尼",
      nameEn: "Indonesia",
      nameNative: "Indonesia",
      exchange: "IDX",
      exchangeShort: "IDX",
      index: "IDX Composite (IHSG)",
      indexCode: "JCI",
      currency: "IDR",
      currencyName: "Rp",
      timezone: "Asia/Jakarta",
      marketHours: "9:00-15:00 WIB",
      description: "东南亚最大经济体。银行+消费+大宗商品。外资持股比例高=对全球流动性敏感。",
      keyTraits: ["外资持股高", "大宗商品出口", "内需消费崛起"],
    },
    MY: {
      id: "MY",
      flag: "🇲🇾",
      name: "马来西亚",
      nameEn: "Malaysia",
      nameNative: "Malaysia",
      exchange: "Bursa Malaysia",
      exchangeShort: "BURSA",
      index: "KLCI",
      indexCode: "FBMKLCI",
      currency: "MYR",
      currencyName: "RM",
      timezone: "Asia/Kuala_Lumpur",
      marketHours: "9:00-17:00 MYT",
      description: "棕榈油+石油+伊斯兰金融。全球最大棕榈油生产国之一。银行股=KLCI最大权重板块。",
      keyTraits: ["棕榈油价联动", "伊斯兰金融", "外资禁空限制"],
    },
  },

  // ══ 14市场统一6大类因子标签 ══
  factorCategories: {
    valuation: {
      id: "valu",
      name: "估值",
      nameEn: "Valuation",
      description: "这市场贵不贵——PE/股息相对历史和同行的位阶",
      emoji: "💰",
      commonFactors: ["PE", "PB", "Dividend Yield", "Earnings Yield"],
    },
    momentum: {
      id: "mom",
      name: "动量/回报",
      nameEn: "Momentum & Return",
      description: "最近涨了还是跌了——趋势的方向和强度",
      emoji: "🚀",
      commonFactors: ["3M Return", "6M Return", "Relative Strength vs World", "52W High Proximity"],
    },
    foreignFlow: {
      id: "flow",
      name: "外资资金流",
      nameEn: "Foreign Flow",
      description: "外国人/外资在买还是卖——非居民资金的真实方向",
      emoji: "🌏",
      commonFactors: ["Foreign Net Buy", "Foreign Ownership %", "Foreign Turnover Ratio"],
    },
    risk: {
      id: "risk",
      name: "风险/波动",
      nameEn: "Risk & Volatility",
      description: "这个市场现在安全吗——波动率、CDS、汇率风险",
      emoji: "⚠️",
      commonFactors: ["Local VIX", "CDS Spread", "Currency Beta", "Max Drawdown"],
    },
    macro: {
      id: "macro",
      name: "本地宏观",
      nameEn: "Local Macro",
      description: "这个国家的经济基本面——GDP/通胀/利率的背景温度",
      emoji: "📊",
      commonFactors: ["GDP Growth", "CPI", "Policy Rate", "PMI"],
    },
    breadth: {
      id: "breadth",
      name: "广度/情绪",
      nameEn: "Breadth & Sentiment",
      description: "涨跌是全市场还是只几只大股在拉——市场健康度",
      emoji: "🌡️",
      commonFactors: ["Advance/Decline Ratio", "% Stocks Above 200MA", "Market Cap Breadth"],
    },
  },

  // ══ 12宏观因子标签 ══
  macroCategories: {
    growth: {
      id: "macro_growth",
      name: "增长",
      nameEn: "Growth",
      emoji: "📈",
      factors: ["GDP_REAL", "GDP_PER_CAPITA", "IND_PROD_YOY"],
    },
    prices: {
      id: "macro_prices",
      name: "物价",
      nameEn: "Prices",
      emoji: "🏷️",
      factors: ["CPI_YOY", "CORE_CPI", "PPI_YOY"],
    },
    labor: {
      id: "macro_labor",
      name: "就业",
      nameEn: "Labor",
      emoji: "👷",
      factors: ["UNEMPLOYMENT", "LABOR_PARTICIPATION"],
    },
    monetary: {
      id: "macro_monetary",
      name: "货币",
      nameEn: "Monetary",
      emoji: "🏦",
      factors: ["POLICY_RATE", "M2_YOY", "LOAN_GROWTH"],
    },
    external: {
      id: "macro_external",
      name: "对外",
      nameEn: "External",
      emoji: "🌐",
      factors: ["TRADE_BALANCE_GDP", "CURRENT_ACCOUNT_GDP", "FX_RESERVES", "GOVT_DEBT_GDP"],
    },
  },

  // ── 快速查找 ──
  getMarket(id: string) {
    return this.markets[id as keyof typeof this.markets] ?? null;
  },
  getMarketList() {
    return Object.values(this.markets).map(m => ({ id: m.id, flag: m.flag, name: m.name }));
  },
  getCategory(id: string) {
    return (this.factorCategories as any)[id] ?? null;
  },
  getMacroCategory(id: string) {
    return (this.macroCategories as any)[id] ?? null;
  },
};

export default GLOBAL_MARKET_LABELS;
