// ── R222-auto#1: 🇭🇰 香港市场策略模板定义 ────────────────────────────────
// 独立模板文件 — TemplateEngine按需加载
// 铁律合规: 权重和=100%, 止损规则, 适用市场, 失效自检

import type { FactorStrategyTemplate } from './factor-strategy-templates';

export const HK_TEMPLATES: FactorStrategyTemplate[] = [
  {
    id: 'hk-ah-premium',
    name: 'AH Premium Arbitrage',
    nameCn: 'AH溢价套利',
    category: 'hk',
    difficulty: 3,
    timeHorizon: 'swing',
    expectedHoldingDays: '5-20天',
    holdingDays: { min: 5, max: 20, unit: 'day' },
    fourIronRules: {
      humanLine: '当A股比H股贵超30%时买H股卖A股，溢价回落到15%以下平仓。利用同一公司两地定价差套利。',
      stopLossRule: 'AH溢价扩大超过入场时5%止损，或单只亏损超过3%止损。',
      marketScope: [{ market: '🇭🇰', assetClass: '股票' }],
      failureCheck: 'AH溢价指数连续10日低于10%时策略失效；人民币汇率剧烈波动时暂停。',
    },
    factorCombo: [
      { factorId: 'FACTOR_AH_PREMIUM', factorName: 'AH溢价因子', weight: 40, direction: 'long' },
      { factorId: 'FACTOR_HK_SOUTHBOUND', factorName: '港股通资金流向', weight: 20, direction: 'long' },
      { factorId: 'FACTOR_LOW_VOL', factorName: '低波动因子', weight: 15, direction: 'long' },
      { factorId: 'FACTOR_VALUE_PB', factorName: '市净率价值', weight: 15, direction: 'long' },
      { factorId: 'FACTOR_MOM_6M', factorName: '6个月动量', weight: 10, direction: 'long' },
    ],
    aiTriggerPoints: [
      { id: 'hk-ah-deep-diagnosis', label: 'AI深度诊断', touchpointId: 'AI_DEEP_DIAGNOSIS', costUSDT: 1.5, description: '分析AH溢价走势及套利机会评估' },
      { id: 'hk-ah-signal-push', label: '信号推送', touchpointId: 'AI_FACTOR_SIGNAL_PUSH', costUSDT: 0.5, description: 'AH溢价突破阈值实时推送' },
      { id: 'hk-ah-backtest', label: '回测解读', touchpointId: 'AI_BACKTEST_READ', costUSDT: 1, description: '历史AH溢价套利回测分析' },
      { id: 'hk-ah-alt-data', label: 'ALT数据解锁', touchpointId: 'FACTOR_ALT_DATA_UNLOCK', costUSDT: 1.5, description: '港股通实时资金流+北向资金数据' },
    ],
    tags: ['hk', 'arbitrage', 'ah-premium'],
    version: '2.1.0',
  },
  {
    id: 'hk-warrant-direction',
    name: 'HK Warrant Direction',
    nameCn: '港股涡轮方向追踪',
    category: 'hk',
    difficulty: 4,
    timeHorizon: 'swing',
    expectedHoldingDays: '1-7天',
    holdingDays: { min: 1, max: 7, unit: 'day' },
    fourIronRules: {
      humanLine: '追踪HK窝轮(涡轮)街货量变化，街货增加+正股放量→跟庄做多，街货骤降→反向做空。',
      stopLossRule: '正股跌破20日均线止损，或涡轮溢价率超过30%止损。',
      marketScope: [{ market: '🇭🇰', assetClass: '涡轮/牛熊证' }],
      failureCheck: '涡轮成交额连续3日低于1000万港元时失效；发行商取消做市时立即平仓。',
    },
    factorCombo: [
      { factorId: 'FACTOR_WARRANT_FLOW', factorName: '涡轮资金流向', weight: 35, direction: 'long' },
      { factorId: 'FACTOR_TURNOVER_RATE', factorName: '换手率因子', weight: 25, direction: 'long' },
      { factorId: 'FACTOR_SHORT_INTEREST', factorName: '沽空比率', weight: 15, direction: 'short' },
      { factorId: 'FACTOR_MOM_1M', factorName: '1个月动量', weight: 15, direction: 'long' },
      { factorId: 'FACTOR_HK_SOUTHBOUND', factorName: '港股通资金流向', weight: 10, direction: 'long' },
    ],
    aiTriggerPoints: [
      { id: 'hk-warrant-signal', label: '信号推送', touchpointId: 'AI_FACTOR_SIGNAL_PUSH', costUSDT: 0.5, description: '涡轮街货异动实时推送' },
      { id: 'hk-warrant-diagnosis', label: '深度诊断', touchpointId: 'AI_DEEP_DIAGNOSIS', costUSDT: 1.5, description: '涡轮方向+隐含波动率分析' },
    ],
    tags: ['hk', 'warrant', 'derivatives'],
    version: '2.1.0',
  },
  {
    id: 'hk-dividend-ladder',
    name: 'HK Dividend Ladder',
    nameCn: '港股股息阶梯',
    category: 'hk',
    difficulty: 2,
    timeHorizon: 'position',
    expectedHoldingDays: '30-90天',
    holdingDays: { min: 30, max: 90, unit: 'day' },
    fourIronRules: {
      humanLine: '买入港股中稳定派息且股息率>4%的蓝筹，构建阶梯式到期结构，每季度再平衡。',
      stopLossRule: '单只股票股息率降至3%以下减仓，股价跌破年线时止损。',
      marketScope: [{ market: '🇭🇰', assetClass: '股票' }],
      failureCheck: '恒指跌破20000点时暂停加仓；香港基准利率急升时重新评估。',
    },
    factorCombo: [
      { factorId: 'FACTOR_DIVIDEND_YIELD', factorName: '股息率因子', weight: 35, direction: 'long' },
      { factorId: 'FACTOR_QUALITY_ROE', factorName: 'ROE质量因子', weight: 25, direction: 'long' },
      { factorId: 'FACTOR_LOW_VOL', factorName: '低波动因子', weight: 20, direction: 'long' },
      { factorId: 'FACTOR_VALUE_PB', factorName: '市净率价值', weight: 10, direction: 'long' },
      { factorId: 'FACTOR_MOM_12M', factorName: '12个月动量', weight: 10, direction: 'long' },
    ],
    aiTriggerPoints: [
      { id: 'hk-div-health', label: '健康检查', touchpointId: 'AI_HEALTH_CHECK', costUSDT: 1, description: '月度组合体检+股息安全性评估' },
      { id: 'hk-div-signal', label: '信号推送', touchpointId: 'AI_FACTOR_SIGNAL_PUSH', costUSDT: 0.5, description: '除权除息日历+信号提醒' },
      { id: 'hk-div-diagnosis', label: '深度诊断', touchpointId: 'AI_DEEP_DIAGNOSIS', costUSDT: 1.5, description: '股息可持续性+财务健康深度分析' },
    ],
    tags: ['hk', 'dividend', 'income', 'blue-chip'],
    version: '2.1.0',
  },
  {
    id: 'hk-reit-yield',
    name: 'HK REIT Yield',
    nameCn: '港股REIT收息',
    category: 'hk',
    difficulty: 2,
    timeHorizon: 'position',
    expectedHoldingDays: '60-180天',
    holdingDays: { min: 60, max: 180, unit: 'day' },
    fourIronRules: {
      humanLine: '买入香港REIT中派息率>5%、资产净值折价>10%的标的，持有收息+等待折价修复。',
      stopLossRule: 'REIT股价跌破资产净值30%时止损，或派息率降至3%以下时卖出。',
      marketScope: [{ market: '🇭🇰', assetClass: 'REIT' }],
      failureCheck: '香港商业地产空置率连续上升2季度时失效；利率急升200bp时暂停。',
    },
    factorCombo: [
      { factorId: 'FACTOR_DIVIDEND_YIELD', factorName: '股息率因子', weight: 40, direction: 'long' },
      { factorId: 'FACTOR_NAV_DISCOUNT', factorName: '资产净值折价因子', weight: 25, direction: 'long' },
      { factorId: 'FACTOR_OCCUPANCY_RATE', factorName: '出租率因子', weight: 15, direction: 'long' },
      { factorId: 'FACTOR_LOW_VOL', factorName: '低波动因子', weight: 10, direction: 'long' },
      { factorId: 'FACTOR_VALUE_PB', factorName: '市净率价值', weight: 10, direction: 'long' },
    ],
    aiTriggerPoints: [
      { id: 'hk-reit-health', label: '健康检查', touchpointId: 'AI_HEALTH_CHECK', costUSDT: 1, description: 'REIT组合健康度+租金收入分析' },
      { id: 'hk-reit-diagnosis', label: '深度诊断', touchpointId: 'AI_DEEP_DIAGNOSIS', costUSDT: 1.5, description: 'REIT资产质量+租约到期风险分析' },
      { id: 'hk-reit-alt', label: 'ALT数据解锁', touchpointId: 'FACTOR_ALT_DATA_UNLOCK', costUSDT: 1.5, description: '香港商业地产租金+空置率实时数据' },
    ],
    tags: ['hk', 'reit', 'income', 'yield'],
    version: '2.1.0',
  },
  {
    id: 'hk-ipo-flip',
    name: 'HK IPO Flip Strategy',
    nameCn: '港股打新策略',
    category: 'hk',
    difficulty: 3,
    timeHorizon: 'intraday',
    expectedHoldingDays: '1-3天',
    holdingDays: { min: 1, max: 3, unit: 'day' },
    fourIronRules: {
      humanLine: 'IPO认购倍数>100倍+暗盘涨幅>10%→首日开盘买入，持有1-3日获利了结。核心是超额认购热度。',
      stopLossRule: '暗盘转跌超过5%止损，首日开盘低于发行价5%止损。',
      marketScope: [{ market: '🇭🇰', assetClass: '新股IPO' }],
      failureCheck: '港股IPO市场连续2个月零超额认购时策略失效；市场暴跌时暂停打新。',
    },
    factorCombo: [
      { factorId: 'FACTOR_IPO_SUBSCRIPTION', factorName: 'IPO认购倍数因子', weight: 35, direction: 'long' },
      { factorId: 'FACTOR_GREY_MARKET', factorName: '暗盘涨幅因子', weight: 30, direction: 'long' },
      { factorId: 'FACTOR_HK_SOUTHBOUND', factorName: '港股通资金流向', weight: 15, direction: 'long' },
      { factorId: 'FACTOR_MOM_1M', factorName: '1个月动量', weight: 10, direction: 'long' },
      { factorId: 'FACTOR_SECTOR_STRENGTH', factorName: '行业强度因子', weight: 10, direction: 'long' },
    ],
    aiTriggerPoints: [
      { id: 'hk-ipo-signal', label: '信号推送', touchpointId: 'AI_FACTOR_SIGNAL_PUSH', costUSDT: 0.5, description: '新股认购倍数突破阈值推送' },
      { id: 'hk-ipo-diagnosis', label: '深度诊断', touchpointId: 'AI_DEEP_DIAGNOSIS', costUSDT: 1.5, description: 'IPO基本面+市场情绪综合分析' },
      { id: 'hk-ipo-backtest', label: '回测解读', touchpointId: 'AI_BACKTEST_READ', costUSDT: 1, description: '历史打新策略回测表现' },
    ],
    tags: ['hk', 'ipo', 'event-driven'],
    version: '2.1.0',
  },
  {
    id: 'hk-short-squeeze',
    name: 'HK Short Squeeze Hunter',
    nameCn: '港股逼空猎手',
    category: 'hk',
    difficulty: 4,
    timeHorizon: 'swing',
    expectedHoldingDays: '3-14天',
    holdingDays: { min: 3, max: 14, unit: 'day' },
    fourIronRules: {
      humanLine: '港股沽空比率>20%+股价开始放量反弹时做多，利用空头回补推动股价上涨。',
      stopLossRule: '股价跌破反弹起点时止损，或沽空比率降至10%以下时止盈。',
      marketScope: [{ market: '🇭🇰', assetClass: '股票' }],
      failureCheck: '恒指连续下跌5日时暂停；个股沽空数据异常（无披露）时回避。',
    },
    factorCombo: [
      { factorId: 'FACTOR_SHORT_INTEREST', factorName: '沽空比率因子', weight: 35, direction: 'long' },
      { factorId: 'FACTOR_MOM_1M', factorName: '1个月动量', weight: 25, direction: 'long' },
      { factorId: 'FACTOR_TURNOVER_RATE', factorName: '换手率因子', weight: 20, direction: 'long' },
      { factorId: 'FACTOR_SHORT_SELLING', factorName: '沽空金额因子', weight: 10, direction: 'long' },
      { factorId: 'FACTOR_VOLATILITY', factorName: '波动率因子', weight: 10, direction: 'long' },
    ],
    aiTriggerPoints: [
      { id: 'hk-sqz-signal', label: '信号推送', touchpointId: 'AI_FACTOR_SIGNAL_PUSH', costUSDT: 0.5, description: '沽空比率异动实时推送' },
      { id: 'hk-sqz-diagnosis', label: '深度诊断', touchpointId: 'AI_DEEP_DIAGNOSIS', costUSDT: 1.5, description: '逼空概率+空头回补潜力评估' },
    ],
    tags: ['hk', 'short-squeeze', 'momentum', 'contrarian'],
    version: '2.1.0',
  },
];

export default HK_TEMPLATES;
