// ══ R244 QClaw P0-01: Factor Humanization — 188 Factors ══
// Consumable by JVS FactorEngine + ML FactorCard components
// Each factor: humanLabel (<=15 chars) + humanDesc (<=50 chars) + avoidNote (<=30 chars)
// Design principle: "我妈能看懂" — no formulas, no Greek letters, no jargon

export interface FactorHumanCopy {
  factorId: string;
  /** <=15 chars, the one-line pitch */
  humanLabel: string;
  /** <=50 chars, when and how to use this factor */
  humanDesc: string;
  /** <=30 chars, when NOT to use this factor */
  avoidNote: string;
}

export const FACTOR_HUMAN_COPY: Record<string, FactorHumanCopy> = {
  // ── Classic Factor (Fama-French + Carhart) ──
  MKT: { humanLabel: '市场风向标', humanDesc: '大盘涨我就涨，牛市里闭眼买的基准', avoidNote: '熊市里这个因子帮不上忙' },
  SIZE: { humanLabel: '小盘优势', humanDesc: '小公司长期比大公司涨得多，耐心持有', avoidNote: '流动性危机时小盘跌最惨' },
  HML: { humanLabel: '捡便宜货', humanDesc: '买市净率低的股票，等市场给公道价', avoidNote: '成长股牛市中会踏空' },
  EP_RATIO: { humanLabel: '市盈率倒选', humanDesc: '赚得多的公司更便宜，用盈利筛选', avoidNote: '亏钱公司不适用，会被误判' },
  CFP_RATIO: { humanLabel: '现金为王', humanDesc: '现金流充沛的公司抗跌，熊市更稳', avoidNote: '高增长公司现金少但回报高' },
  MOM_12M: { humanLabel: '强者恒强', humanDesc: '过去一年涨得多的，短期还会涨', avoidNote: '震荡市中反复打脸，别用' },
  MOM_6M: { humanLabel: '半年赢家', humanDesc: '半年表现最强的票，顺势跟进', avoidNote: '不适合电商/节日股，季节反转' },
  MOM_1M: { humanLabel: '短期追风', humanDesc: '最近一个月最猛的，短线抓趋势', avoidNote: '月末容易反转，别追最后几天' },
  MOM_6_1: { humanLabel: '掐头去尾', humanDesc: '去掉最近1个月噪音，更纯的趋势信号', avoidNote: '仍不适合高波动加密市场' },
  RMW: { humanLabel: '赚钱机器', humanDesc: '利润高的公司长期跑赢大盘', avoidNote: '科技股利润薄但成长快，会错过' },
  CMA: { humanLabel: '稳重派', humanDesc: '不瞎扩张的公司更靠谱，长期持有', avoidNote: '成长型公司会被误打低分' },
  QUAL: { humanLabel: '全能学霸', humanDesc: '盈利稳+负债低+资产好，三好学生', avoidNote: '垃圾股反弹时你会看着别人赚' },
  GROWTH: { humanLabel: '成长先锋', humanDesc: '营收和利润高速增长，未来之星', avoidNote: '加息周期里成长股最先挨打' },
  YIELD: { humanLabel: '收租型', humanDesc: '股息高的公司像收租，稳稳的幸福', avoidNote: '利率上升时高息股变鸡肋' },
  DIV_YIELD_12M: { humanLabel: '一年息票', humanDesc: '拿满一年的股息率，不急不躁', avoidNote: '周期股高息可能是陷阱' },

  // ── Fundamental Deep-Dive ──
  ACCRUALS: { humanLabel: '利润真金度', humanDesc: '利润是纸上富贵还是真金白银？一眼看穿', avoidNote: '金融企业会计特殊，此指标无效' },
  EARNINGS_VARIABILITY: { humanLabel: '业绩稳不稳', humanDesc: '盈利忽上忽下的公司不敢长持', avoidNote: '周期股天然波动大，会被误杀' },
  GROSS_PROFITABILITY: { humanLabel: '毛利率筛选', humanDesc: '毛利率高的公司有护城河，竞争少', avoidNote: '初创期烧钱公司会被低估' },
  NET_PAYOUT: { humanLabel: '老板大方', humanDesc: '分红+回购比率高的公司，股东友好', avoidNote: '成长阶段不分红不是坏事' },
  OPERATING_LEVERAGE: { humanLabel: '经营杠杆', humanDesc: '收入增10%利润增20%？找这种公司', avoidNote: '经济衰退时杠杆反向放大亏损' },
  ASSET_TURNOVER: { humanLabel: '效率之王', humanDesc: '同样资产产出更多收入的才是好生意', avoidNote: '轻资产公司此指标虚高，要甄别' },
  CASH_FLOW_YIELD: { humanLabel: '现金牛', humanDesc: '自由现金流充裕的公司，不怕寒冬', avoidNote: '资本开支高峰期现金流转负属正常' },
  DEBT_COVERAGE: { humanLabel: '还得起债', humanDesc: '赚的钱够还多少次利息？低了危险', avoidNote: '初创未盈利企业不适用' },
  EARNINGS_SURPRISE: { humanLabel: '惊喜制造机', humanDesc: '连续超预期的公司，市场会给溢价', avoidNote: '一次性事件导致超预期不等于好' },
  EARN_QUALITY: { humanLabel: '盈利含金量', humanDesc: '剔除非经常损益后的真实赚钱能力', avoidNote: '新兴行业会计准则灵活性大' },
  GROSS_MARGIN_TREND: { humanLabel: '利润走强', humanDesc: '毛利率持续上升说明竞争力在增强', avoidNote: '原材料涨价周期中会被误读' },
  F_SCORE: { humanLabel: '财务体检', humanDesc: 'Piotroski发明的9分体检表，高分选手', avoidNote: '仅适用于制造业，金融科技不适用' },
  ROE_STABILITY: { humanLabel: '稳赚不赔', humanDesc: 'ROE多年保持高位且波动小，真龙头', avoidNote: '高杠杆推高的ROE是假象' },
  INVENTORY_TURNOVER: { humanLabel: '货卖得快', humanDesc: '存货周转快的公司，资金效率高', avoidNote: '不同行业天然不同，不能跨行业比' },
  RECEIVABLE_TURNOVER: { humanLabel: '回款速度', humanDesc: '应收款转得快，说明下游不敢欠你', avoidNote: '季节性波动大，单季数据不可信' },
  FREE_CASH_FLOW: { humanLabel: '自由现金流', humanDesc: '去掉所有开支后还剩的钱，真赚钱', avoidNote: '高增长期公司FCF可能为负' },
  CURRENT_RATIO: { humanLabel: '短期偿债力', humanDesc: '流动资产vs流动负债，看能不能熬过明年', avoidNote: '行业差异大，零售和矿业不是一个量级' },
  INTEREST_COVERAGE: { humanLabel: '利息安全垫', humanDesc: '利润够还多少倍利息？低于3倍要小心', avoidNote: '无负债公司此指标无意义' },
  ROA: { humanLabel: '资产回报率', humanDesc: '每投100块资产赚几块？综合效率指标', avoidNote: '金融机构天然低ROA，不能一刀切' },

  // ── Analyst Sentiment ──
  ANALYST_MOMENTUM: { humanLabel: '分析师跟风', humanDesc: '评级在往上调的公司可能还在涨', avoidNote: '卖方分析师天然乐观，参考但别盲信' },
  EARNINGS_REVISION: { humanLabel: '盈利上调', humanDesc: '分析师刚调高了这家公司的利润预期', avoidNote: '调高可能是追涨，要结合自己判断' },
  TARGET_PRICE_IMPLIED: { humanLabel: '目标价空间', humanDesc: '当前股价离分析师目标价还有多远', avoidNote: '目标价经常不准，看趋势别看绝对值' },
  ANALYST_DISPERSION: { humanLabel: '分歧度', humanDesc: '分析师看法一致时信号更强，分歧大要小心', avoidNote: '热门股天然分歧大，不能只看这个' },
  RECOMMENDATION_CHANGE: { humanLabel: '评级变动', humanDesc: '昨天还是卖出今天变买入？重大信号', avoidNote: '单个分析师调级噪音多，看整体' },
  REVISION_RATIO: { humanLabel: '多空比', humanDesc: '上调人数比下调人数，看市场共识方向', avoidNote: '财报季扎堆调整时会有噪声' },

  // ── Market Sentiment ──
  FEAR_GREED_INDEX: { humanLabel: '恐慌贪婪表', humanDesc: '别人恐惧我贪婪，别人贪婪我恐惧', avoidNote: '极端情绪可以持续很久，别急着抄底' },
  PUT_CALL_SKEW: { humanLabel: '期权情绪表', humanDesc: '看跌vs看涨期权的价格差距暴露市场底牌', avoidNote: '机构用期权对冲不等于看空' },
  HIGH_LOW_RATIO: { humanLabel: '高低比', humanDesc: '创新高vs创新低股票数的对比看大势', avoidNote: '单日数据波动大，看5日移动均线' },
  ADVANCE_DECLINE: { humanLabel: '涨跌比', humanDesc: '涨的票多还是跌的多？一目了然看风向', avoidNote: '大盘股左右指数时此指标会失真' },
  OPTION_PCR: { humanLabel: 'Put Call比', humanDesc: 'Put多=恐慌，Call多=亢奋，极端值最有用', avoidNote: '每月期权到期日数据会跳变' },
  SOCIAL_SENTIMENT: { humanLabel: '社交情绪', humanDesc: '推特/Reddit/雪球上大家在聊什么', avoidNote: '水军和机器人会干扰，看趋势不看绝对值' },
  MEDIA_ATTENTION: { humanLabel: '上热搜了', humanDesc: '媒体突然疯狂报道某股票，关注度飙升', avoidNote: '热度高不等于会涨，经常是接盘信号' },
  INSIDER_TRADING: { humanLabel: '自己人交易', humanDesc: 'CEO/CFO买了自己公司股票？强烈看涨信号', avoidNote: '卖出可能是套现需要，不一定是看空' },
  SHORT_COVERING: { humanLabel: '逼空压力', humanDesc: '空头持仓过高时，一个利好就能起飞', avoidNote: '不要仅凭空头比例买入，基本面更重要' },
  NEWS_SENTIMENT: { humanLabel: '新闻情绪', humanDesc: 'AI读遍今日新闻判断市场心情好还是坏', avoidNote: '标题党会误导AI，参考即可' },
  INSTITUTIONAL_FLOW: { humanLabel: '机构动向', humanDesc: '大户资金流入还是流出？跟着聪明钱走', avoidNote: '机构调仓慢，散户跟风可能已经晚了' },
  INSIDER_BUYING: { humanLabel: '内部人买入', humanDesc: '高管自掏腰包买入，对自家公司真有信心', avoidNote: '买入金额太小(<年薪10%)参考价值低' },

  // ── Technical Indicators ──
  MA_20_60: { humanLabel: '金叉死叉', humanDesc: '短期均线上穿长期=买入，下穿=卖出', avoidNote: '震荡市频繁交叉会把你折腾死' },
  EMA_12_26: { humanLabel: 'MACD信号', humanDesc: '经典MACD，金叉买入死叉卖出，简单好用', avoidNote: '横盘时MACD基本失灵' },
  RSI_14: { humanLabel: '超买超卖', humanDesc: 'RSI低于30太便宜了，高于70太贵了', avoidNote: '强势趋势中RSI可以一直>70' },
  KDJ: { humanLabel: '随机指标', humanDesc: '比RSI更灵敏的震荡指标，适合短线', avoidNote: '极度灵敏容易假信号，需要配合使用' },
  BOLL: { humanLabel: '布林带', humanDesc: '价格碰到下轨可能反弹，碰到上轨可能回调', avoidNote: '趋势突破时布林带会持续打开' },
  ATR_14: { humanLabel: '真实波动', humanDesc: '看看这只票每天平均波动多少，定止损', avoidNote: '突发事件后ATR会飙，常规止损失效' },
  ADX: { humanLabel: '趋势强度', humanDesc: '数越大趋势越强，25以上=有趋势可追', avoidNote: 'ADX只告诉你趋势强弱，不告诉你方向' },
  OBV: { humanLabel: '能量潮', humanDesc: '成交量配合价格才靠谱，放量上涨=真好', avoidNote: '小盘庄股OBV容易被操纵' },
  CMF: { humanLabel: '资金进出', humanDesc: '观察真金白银的进出方向，比看K线诚实', avoidNote: '尾盘拉升无量的票CMF看不出来' },
  ICHIMOKU: { humanLabel: '一目均衡', humanDesc: '一个图看全趋势+支撑+阻力，日本交易员的秘密', avoidNote: '学习曲线陡，新手容易看花眼' },
  VWAP: { humanLabel: '均成交价', humanDesc: '机构大单的参考基准价，穿越VWAP=方向确认', avoidNote: '只适用于日内交易，隔夜后失效' },

  // ── Risk & Tail ──
  VOL_60D: { humanLabel: '波动率', humanDesc: '60天价格波动多大？越大越刺激也越危险', avoidNote: '低波动可能是暴风雨前的宁静' },
  LIQ: { humanLabel: '流动性', humanDesc: '买卖是否方便？不好卖的票别买太多', avoidNote: '小市值股票流动性差，大资金进不去' },
  MAX_DRAWDOWN: { humanLabel: '最大回撤', humanDesc: '历史最惨的时候亏了多少？你能接受吗', avoidNote: '过去最惨不代表未来最惨' },
  VAR_95: { humanLabel: '95%风控线', humanDesc: '95%概率下一天不会亏超过这个数', avoidNote: '剩下5%的黑天鹅才是真正要命的' },
  CVAR_95: { humanLabel: '极端损失', humanDesc: '如果那5%的倒霉事真发生了会亏多少', avoidNote: '模型假设基于历史，极端事件无法预测' },
  DOWNSIDE_DEVIATION: { humanLabel: '下行风险', humanDesc: '只看下跌那段的风险，上涨的忽略不计', avoidNote: '需要充足的历史数据做支撑' },
  SORTINO_RATIO: { humanLabel: '好波动率', humanDesc: '同样回报下谁跌得少谁获胜', avoidNote: '短期收益高的风险未必低' },
  OMEGA_RATIO: { humanLabel: '盈亏比', humanDesc: '赚的时候赚多少vs亏的时候亏多少', avoidNote: '样本量不够时Omega虚高' },
  TAIL_DEPENDENCE: { humanLabel: '熊市传染', humanDesc: '市场暴跌时这只票会不会一起跳水', avoidNote: '历史相关性在危机中经常失效' },
  CROWDING: { humanLabel: '拥挤度', humanDesc: '所有人都在买这个？可能要踩踏了', avoidNote: '拥挤策略可以持续远比你想象的久' },
  MOM_CRASH: { humanLabel: '动量崩盘', humanDesc: '动量策略突然亏损的历史时刻预警', avoidNote: '无法预测崩盘确切时间，只能预警' },
  BETA_STABILITY: { humanLabel: 'Beta稳不稳', humanDesc: '和大盘的关系是否稳定，不稳定=不可靠', avoidNote: '重大事件后Beta会剧变' },
  SKEWNESS: { humanLabel: '收益偏度', humanDesc: '涨跌分布是否对称？往右偏=小亏大赚', avoidNote: '需要大量样本才有统计意义' },
  KURTOSIS: { humanLabel: '极端频次', humanDesc: '出现极端涨跌的频率是否比正态分布高', avoidNote: '样本量<100时此指标无意义' },
  ALPHA_DECAY: { humanLabel: 'Alpha寿命', humanDesc: '超额收益在消失吗？快跑还是继续持有', avoidNote: '短期衰减可能是噪声不是趋势' },

  // ── Macro Sensitivity ──
  SECTOR_ROTATION: { humanLabel: '轮动风向', humanDesc: '钱在从哪个板块流到哪个板块', avoidNote: '轮动判断错误比不动更惨' },
  FX_EXPOSURE: { humanLabel: '汇率风险', humanDesc: '人民币/港币汇率波动对你持仓的影响', avoidNote: '汇率双向波动，对冲也有成本' },
  RATE_BETA: { humanLabel: '加息受害', humanDesc: '利率涨1%这只票会跌多少？敏感勿碰', avoidNote: '市场预期早已计入，加息当天未必跌' },
  INFLATION_BETA: { humanLabel: '通胀甜苦', humanDesc: '物价上涨对这只票是利好还是利空', avoidNote: '恶性通胀下所有资产都受伤' },
  USD_BETA: { humanLabel: '美元关联', humanDesc: '美元走强/走弱对这只票的影响方向', avoidNote: '关联性随时间变化，要持续更新' },
  OIL_BETA: { humanLabel: '油价影踪', humanDesc: '原油价格涨了对这只票是福是祸', avoidNote: '油价受地缘政治影响，模型预测有限' },
  CREDIT_SPREAD_BETA: { humanLabel: '信用风险', humanDesc: '企业债利率飙升时这只票扛得住吗', avoidNote: '信用事件突发，历史数据可能不够用' },
  ECONOMIC_SURPRISE: { humanLabel: '经济意外', humanDesc: '经济数据比预期好还是差？超预期=利好', avoidNote: '数据修正频繁，最初读数可能误导' },
  MARKET_REGIME: { humanLabel: '市场状态', humanDesc: '现在是牛市/熊市/震荡？不同状态用不同策略', avoidNote: '状态识别滞后的，等你发现已经切换了' },
  VOLUME_REGIME: { humanLabel: '量能状态', humanDesc: '放量还是缩量？量能决定趋势真假', avoidNote: '假期前后量能失真，不能据此判断' },
  YIELD_CURVE_SLOPE: { humanLabel: '曲线形态', humanDesc: '长短债利差暗示经济前景，倒挂=预警', avoidNote: '倒挂后经济衰退可能晚1-2年才来' },
  REAL_RATE: { humanLabel: '实际利率', humanDesc: '剔除通胀后的真实利率，影响估值中枢', avoidNote: '通胀预期变化快，实际利率也随之波动' },
  PMI_INDEX: { humanLabel: '制造业体温', humanDesc: 'PMI高于50=扩张，低于50=收缩', avoidNote: '单月波动常有，看3月均线' },
  VOLATILITY_REGIME: { humanLabel: '波动体制', humanDesc: '高波动区还是低波动区？切换时最危险', avoidNote: '体制切换往往突然发生' },
  FACTOR_LEAD_LAG: { humanLabel: '因子时差', humanDesc: '哪些因子在引领，哪些在跟随', avoidNote: '领先滞后关系会反转' },

  // ── Reversal & Seasonality ──
  STR_5D: { humanLabel: '5日反弹王', humanDesc: '跌了5天该反弹了？短线抄底参考', avoidNote: '跌停板无法卖出时此信号没用' },
  LTR_60M: { humanLabel: '5年大翻盘', humanDesc: '过去5年最惨的股票可能是下一批黑马', avoidNote: '有些公司是真的不行了，不是被错杀' },
  SEASONAL_1M: { humanLabel: '月度规律', humanDesc: '某些月份股市天然表现好，规律在重复', avoidNote: '历史规律不是铁律，会变异' },
  GAP_REVERSION: { humanLabel: '缺口必补', humanDesc: '跳空缺口大概率会回补，耐心等待', avoidNote: '业绩大幅超预期造成的缺口可能永不补' },
  MEAN_REVERSION_SPEED: { humanLabel: '回归速度', humanDesc: '偏离均线后回归的速度，快=短期机会', avoidNote: '趋势启动时是脱离均线不是回归' },

  // ── US-Specific ──
  US_VIX: { humanLabel: '恐慌指数', humanDesc: '华尔街恐惧的晴雨表，高=害怕，低=安逸', avoidNote: 'VIX低时大家都在睡觉，但风险在积累' },
  US_SHORT_RATIO: { humanLabel: '空头比例', humanDesc: '做空比率越高，逼空可能性越大', avoidNote: '基本面差的公司被做空有道理' },
  US_INST_HOLD: { humanLabel: '机构抱团', humanDesc: '机构持仓比例高的票通常更稳定', avoidNote: '机构一致性出逃时踩踏更严重' },
  US_BUYBACK: { humanLabel: '回购达人', humanDesc: '公司自己回购股票=觉得被低估了', avoidNote: '借钱回购的公司是在粉饰EPS' },
  US_EARN_SURPRISE: { humanLabel: '财报惊喜', humanDesc: '业绩超预期的公司后续表现更强', avoidNote: '超预期幅度小(<2%)的信号不可靠' },
  US_INSIDER_BUY: { humanLabel: '内部人抄底', humanDesc: 'CEO大笔买入自己公司股票，强烈信号', avoidNote: '卖出需申报很多原因，别只看买入' },
  US_SHORT_SQUEEZE: { humanLabel: '轧空风险', humanDesc: '空头太多了一个小利好就会引爆', avoidNote: '轧空结束后回落同样猛烈' },
  US_MEME_INDEX: { humanLabel: '散户热股', humanDesc: 'Reddit散户讨论热度飙升的票', avoidNote: '散户情绪来得快去得也快' },
  US_MARGIN_DEBT: { humanLabel: '杠杆温度', humanDesc: '保证金债务高=散户亢奋，低=恐惧', avoidNote: '历史高位不代表立即回调' },
  US_RESIDUAL_MOM: { humanLabel: '净动量', humanDesc: '去掉大盘和行业影响后的纯个股趋势', avoidNote: '计算复杂，普通用户不适用' },
  US_EP_RATIO: { humanLabel: '美股PE筛选', humanDesc: '找美股里市盈率最低的票，价值投资者最爱', avoidNote: '超低PE可能是价值陷阱' },
  US_BP_RATIO: { humanLabel: '美股PB筛选', humanDesc: '股价跌破净资产？可能被低估了', avoidNote: '银行保险适用，科技公司不适用' },
  US_DPS_STABILITY: { humanLabel: '分红老店', humanDesc: '连续多年稳定分红的公司，抗周期', avoidNote: '高分红不增长=债券替代品不是成长股' },

  // ── HK-Specific ──
  HKEX_SOUTHBOUND: { humanLabel: '北水南下', humanDesc: '内地资金通过港股通买入的信号', avoidNote: '南向资金有时是被动配置不是主动看好' },
  HKEX_CBCS_PREMIUM: { humanLabel: 'AH价差', humanDesc: 'A股贵H股便宜时，买港股等回归', avoidNote: '价差可能因为汇率/流动性持续存在' },
  HKEX_WARRANT_IV: { humanLabel: '涡轮情绪', humanDesc: '港股涡轮隐含波动的变化暗示大资金意图', avoidNote: '涡轮数据复杂，需要专业解读' },
  HKEX_DLHB: { humanLabel: '大轮候补', humanDesc: '港股通调入股候选名单的效应', avoidNote: '调入不等于马上涨，预期已计入' },
  HKEX_FUND_HOLD: { humanLabel: '基金持仓', humanDesc: '跟踪港股基金持仓变化找机构动向', avoidNote: '数据季度更新，已经滞后1-3个月' },
  HK_SOUTHBOUND_FLOW: { humanLabel: '北水净流入', humanDesc: '今天内地资金是买还是卖港股？', avoidNote: '单日数据波动大，看周度累计' },
  HK_SOUTHBOUND_TOP10: { humanLabel: '北水最爱', humanDesc: '内地资金最集中买入的前10只港股', avoidNote: '跟风买入时可能是短期高点' },
  HK_SOUTHBOUND_MOM: { humanLabel: '北水加速', humanDesc: '南向资金流入在加速还是在减速', avoidNote: '加速可能是尾声信号' },
  HK_CONTROLLING_SH: { humanLabel: '大股东质押', humanDesc: '大股东质押率高的港股要小心爆仓', avoidNote: '质押本身不等于危险，要看整体' },
  HK_DIV_CUT_RISK: { humanLabel: '减分红风险', humanDesc: '这只港股会不会砍股息？提前预警', avoidNote: '周期性减息不等于公司出了问题' },
  HK_WARRANT_GEX: { humanLabel: '涡轮Gamma', humanDesc: '做市商对冲行为可能导致价格加速运动', avoidNote: '仅对大型港股适用，小票数据少' },
  HK_CBBC_STREET: { humanLabel: '牛熊街货', humanDesc: '散户的牛熊证分布暴露了大众预期', avoidNote: '散户往往是反向指标' },
  HK_WARRANT_OI: { humanLabel: '涡轮持仓', humanDesc: '涡轮持仓的增减暗示聪明的钱在动', avoidNote: '持仓变化可能只是到期滚动' },
  HK_SHORT_SELL: { humanLabel: '沽空比率', humanDesc: '港股做空比例飙升？可能是暴跌前兆', avoidNote: '某些做空是对冲行为不是看空' },
  HK_ACC_RECEIVABLE: { humanLabel: '应收异常', humanDesc: '应收账款突然暴增？小心利润虚增', avoidNote: '行业账款周期不同，不能跨行业比' },
  HK_AH_PREMIUM: { humanLabel: 'AH溢价率', humanDesc: 'AH股差价多大？价差收窄有利可图', avoidNote: '熊市中AH溢价往往会扩大而不是收窄' },

  // ── Crypto (35) ──
  CRYPTO_FUNDING: { humanLabel: '永续费率', humanDesc: '资金费率太正=多头过热可空，太负=空头过热可多', avoidNote: '趋势市中费率保持极端很久' },
  CRYPTO_OI_DELTA: { humanLabel: '持仓变化', humanDesc: '持仓量增减暗示资金在进场还是离场', avoidNote: '交割日持仓量自然下降，不是信号' },
  CRYPTO_EXCHANGE_FLOW: { humanLabel: '交易所流入', humanDesc: '币大量转入交易所=可能要砸盘，转出=持有', avoidNote: '交易所内部转账会干扰统计' },
  CRYPTO_ORDERBOOK_IMB: { humanLabel: '订单簿失衡', humanDesc: '买单堆得多还是卖单堆得多？方向一目了然', avoidNote: '高频机器人会撤单制造假象' },
  CRYPTO_VOL_RATIO: { humanLabel: '放量方向', humanDesc: '放量上涨=真涨，放量下跌=真跌', avoidNote: '虚假刷量交易需要排除' },
  CRYPTO_VOLUME_PROFILE: { humanLabel: '量价密集区', humanDesc: '成交量最集中的价格区间=天然支撑/阻力', avoidNote: '突发新闻会瞬间打破所有支撑' },
  CRYPTO_BTC_CORR: { humanLabel: 'BTC跟班', humanDesc: 'BTC涨这个币跟不跟？跟得紧=BTC小弟', avoidNote: '山寨币可能走出独立行情' },
  CRYPTO_NVT: { humanLabel: '链上估值', humanDesc: '用链上交易量给代币估值，像PE但更真实', avoidNote: 'Layer1和DApp代币的NVT不可比' },
  CRYPTO_ACTIVE_ADDR: { humanLabel: '活跃用户', humanDesc: '链上活跃地址越多，网络效应越强', avoidNote: '空投/活动会造成地址激增假象' },
  CRYPTO_LIQUIDATIONS: { humanLabel: '爆仓量', humanDesc: '大规模爆仓后市场往往会反弹', avoidNote: '趋势市中爆完继续爆' },
  CRYPTO_SOCIAL_SENTIMENT: { humanLabel: '币圈情绪', humanDesc: 'Twitter/Telegram上的币圈讨论有多热', avoidNote: '付费喊单群会人为制造热度' },
  CRYPTO_WHALE_ACCUM: { humanLabel: '巨鲸囤货', humanDesc: '大钱包在持续买入，跟着聪明钱走', avoidNote: '巨鲸可能在多个钱包分散操作' },
  CRYPTO_WHALE_DISTRIB: { humanLabel: '巨鲸出货', humanDesc: '大钱包在持续减持，行情可能到顶', avoidNote: '巨鲸也可能只是在换钱包' },
  CRYPTO_MVRV: { humanLabel: '市场盈亏', humanDesc: '当前持有人平均盈亏，赚太多=该卖了', avoidNote: '牛市里MVRV可以长期偏高' },
  CRYPTO_FEAR_GREED: { humanLabel: '币圈贪婪度', humanDesc: '加密市场专属的恐慌贪婪指数', avoidNote: '极度贪婪时市场还能更贪婪' },
  CRYPTO_MOM_7D: { humanLabel: '7日动量', humanDesc: '一周内涨得最多的币，短线追涨', avoidNote: '加密市场7天可以翻天覆地' },
  CRYPTO_MOM_30D: { humanLabel: '月度动量', humanDesc: '一个月内表现最强的币', avoidNote: '大趋势市中追涨比抄底赚的多' },
  CRYPTO_MOM_90D: { humanLabel: '季度动量', humanDesc: '季度表现筛选长线强势币', avoidNote: '热门币可能已经在顶部区域' },
  CRYPTO_ALPHA_VS_BTC: { humanLabel: '跑赢BTC', humanDesc: '这个币的表现是否干过了老大哥BTC', avoidNote: '熊市中几乎所有币都跑不赢BTC' },
  CRYPTO_ALT_SEASON: { humanLabel: '山寨季', humanDesc: '山寨币整体跑赢BTC的时期，重仓时机', avoidNote: '山寨季结束时的回撤非常惨烈' },
  CRYPTO_NVT_SIGNAL: { humanLabel: 'NVT买卖', humanDesc: 'NVT偏离历史均值的买卖信号', avoidNote: '市场结构变化后NVT基准会漂移' },
  CRYPTO_STAKING_YIELD: { humanLabel: '质押收益', humanDesc: '质押代币赚利息，比较不同链的收益率', avoidNote: '高收益伴随更高通胀，代币会贬值' },
  CRYPTO_FEE_REVENUE: { humanLabel: '协议赚钱力', humanDesc: '这条链真的在赚钱吗？看协议收入', avoidNote: '补贴期收入虚高不可持续' },
  CRYPTO_TVL_GROWTH: { humanLabel: 'TVL增速', humanDesc: '锁仓量增长=生态在扩大，下降=在萎缩', avoidNote: 'TVL高可能是庞氏驱动' },
  CRYPTO_MAX_DRAWDOWN_30D: { humanLabel: '30日暴跌', humanDesc: '最近一个月最大跌了多少？心脏受得了吗', avoidNote: '加密回撤50%是常态' },
  CRYPTO_PRICE_CORRECTION: { humanLabel: '回调深度', humanDesc: '从历史高点跌了多少？看回调是否到位', avoidNote: '抄底之后可能还有抄地下室' },
  CRYPTO_LIQUIDATION_RISK: { humanLabel: '爆仓预警', humanDesc: '当前价格离你爆仓还有多远', avoidNote: '极端行情下滑点会让爆仓价偏高' },
  CRYPTO_EXCHANGE_RESERVE: { humanLabel: '交易所余额', humanDesc: '交易所里的币多了=抛压，少了=惜售', avoidNote: 'CEX数据不包含DEX' },
  CRYPTO_BRIDGE_FLOW: { humanLabel: '跨链资金', humanDesc: '钱在从哪条链流向哪条链', avoidNote: '跨链桥攻击后资金流向会突变' },
  CRYPTO_ECOSYSTEM_CORR: { humanLabel: '生态共振', humanDesc: 'BTC的生态(闪电网络)或ETH的L2表现', avoidNote: '生态相关不等于跟涨，可能吸血' },
  CRYPTO_VC_UNLOCK: { humanLabel: 'VC解禁日', humanDesc: '早期投资人解锁抛售的日期，日历标注', avoidNote: '市场已预期解禁，但具体抛压未知' },
  CRYPTO_DEVELOPER_ACTIVITY: { humanLabel: '开发者活跃', humanDesc: '代码提交多=项目在建设没跑路', avoidNote: '低质量提交和刷代码需要甄别' },
  CRYPTO_SMART_MONEY: { humanLabel: '聪明钱包', humanDesc: '历史上胜率高的钱包地址在买什么', avoidNote: '聪明钱也会犯错，不要盲跟' },
  CRYPTO_STABLECOIN_RATIO: { humanLabel: '稳定币占比', humanDesc: '稳定币占比高=资金在观望等入场', avoidNote: '稳定币也可能被赎回退出' },
  CRYPTO_S2F: { humanLabel: '稀缺模型', humanDesc: '比特币减半后的稀缺性估值模型', avoidNote: '假设备受质疑，不只看稀缺' },
  CRYPTO_HASH_RATE: { humanLabel: '矿业热度', humanDesc: '比特币算力变化预示矿工信心', avoidNote: '算力变化反映的是矿工不是投资者' },

  // ── Cross-Asset & Carry ──
  CARRY_EQUITY: { humanLabel: '股利差', humanDesc: '股息率减去无风险利率，利差大=有吸引力', avoidNote: '利率快速变化时利差信号失真' },
  CARRY_CRYPTO: { humanLabel: '加密套利', humanDesc: '做多现货做空永续赚差价', avoidNote: '需要双边头寸管理，爆仓风险存在' },
  CARRY_CURRENCY: { humanLabel: '外汇套利', humanDesc: '高息货币vs低息货币的利差交易', avoidNote: '汇率反向波动会吞噬全部利息收益' },
  BOND_CARRY: { humanLabel: '债券利差', humanDesc: '不同期限债券的收益率差异机会', avoidNote: '利率曲线大幅波动时策略失效' },
  CURRENCY_MOMENTUM: { humanLabel: '货币动量', humanDesc: '强势货币继续强的规律，外汇趋势追踪', avoidNote: '央行干预会打断货币趋势' },
  GOLD_MOMENTUM: { humanLabel: '黄金动能', humanDesc: '正在上涨的黄金还会继续涨', avoidNote: '美联储态度转变时黄金会瞬间反转' },
  COMMODITY_SPREAD: { humanLabel: '期现价差', humanDesc: '期货比现货贵=市场看好，便宜=看空', avoidNote: '仓储成本导致的价差不是市场信号' },
  CORR_REGIME: { humanLabel: '相关性切换', humanDesc: '不同资产的相关性在变，配置要调整', avoidNote: '识别滞后，切换后已来不及调整' },
  CROSS_ASSET_CORR: { humanLabel: '资产联动', humanDesc: '股债商品三者之间的联动关系', avoidNote: '金融危机时所有资产一起跌' },
  COMMODITY_MOMENTUM: { humanLabel: '商品趋势', humanDesc: '正在涨的商品大概率还会涨', avoidNote: '供给冲击后趋势会突然逆转' },
  BOND_MOMENTUM: { humanLabel: '债券趋势', humanDesc: '债券价格趋势追踪，利率下行=债券上涨', avoidNote: '央行意外加息会让策略瞬间亏损' },
  FX_CARRY: { humanLabel: '外汇利差', humanDesc: '做多高息做空低息货币赚利息', avoidNote: '新兴市场货币波动大，利息不够亏' },

  // ── Event-Driven ──
  PRE_EARNINGS_DRIFT: { humanLabel: '财报前涨', humanDesc: '财报发布前股价偷偷在涨？可能有惊喜', avoidNote: '也有可能是随机波动别过度解读' },
  POST_EARNINGS_DRIFT: { humanLabel: '财报后飘', humanDesc: '业绩超预期后股价还会继续涨几周', avoidNote: '不及预期的公司会反向漂移' },
  DIVIDEND_CAPTURE: { humanLabel: '截股利策略', humanDesc: '除息日前买入拿分红后卖出', avoidNote: '分红后股价除息下调=左口袋倒右口袋' },
  INDEX_REBALANCE: { humanLabel: '调入效应', humanDesc: '被纳入指数的股票通常会被动买盘推高', avoidNote: '预期已提前反应，调入后可能sell the news' },
  IPO_LOCKUP_EXPIRY: { humanLabel: '解禁日到', humanDesc: '原始股东锁定期到期的日期', avoidNote: '不是所有解禁都会抛售，看股东结构' },
  BUYBACK_ANNOUNCE: { humanLabel: '回购信号', humanDesc: '公司宣布回购计划=管理层认为股价被低估', avoidNote: '宣布不等于执行，很多公司宣布了不买' },
  DIV_ANNOUNCEMENT: { humanLabel: '分红消息', humanDesc: '分红公告前后的交易机会', avoidNote: '市场预期已计入，公告日波动未必大' },
  EARN_ANNOUNCEMENT: { humanLabel: '财报日', humanDesc: '财报发布日的波动率明显放大', avoidNote: '财报赌博风险高，结果不确定' },

  // ── ESG ──
  ESG_SCORE: { humanLabel: 'ESG总评分', humanDesc: '环境社会管治综合得分，越高越可持续', avoidNote: '评分标准不统一，不同机构得分差很大' },
  CARBON_INTENSITY: { humanLabel: '碳排量', humanDesc: '每百万营收碳排放，绿色投资指标', avoidNote: '高碳行业不一定就是坏生意' },
  GOVERNANCE_SCORE: { humanLabel: '治理水平', humanDesc: '董事会独立性和股东权益保护如何', avoidNote: '不同国家治理标准差异大' },
  GREEN_REVENUE: { humanLabel: '绿色收入', humanDesc: '公司营收中有多少来自环保业务', avoidNote: '企业可能虚标绿色业务比例' },
  SOCIAL_SCORE: { humanLabel: '社会责任', humanDesc: '员工待遇/社区关系/产品安全得分', avoidNote: '社交评分主观性强' },
  ESG_MOMENTUM: { humanLabel: 'ESG进步', humanDesc: 'ESG评分在改善的公司可能得到市场重估', avoidNote: '评分改善不等同股价涨' },

  // ── Commodity Futures ──
  CMD_ROLL_YIELD: { humanLabel: '展期收益', humanDesc: '换月时的差价收益，正=赚钱，负=赔钱', avoidNote: '升水市场展期成本持续侵蚀收益' },
  CMD_TERM_STRUCTURE: { humanLabel: '期现结构', humanDesc: '远月vs近月的价差方向，升水还是贴水', avoidNote: '结构可能因突发事件一天内翻转' },
  CMD_BASIS: { humanLabel: '基差', humanDesc: '现货价减去期货价，收敛机会', avoidNote: '实物商品有交割成本偏差' },
  CMD_MOMENTUM_12M: { humanLabel: '商品年动量', humanDesc: '过去一年涨最多的商品期货', avoidNote: '农产品有季节性反转，动量可能失效' },
  CMD_MOMENTUM_1M: { humanLabel: '商品月反转', humanDesc: '短期跌太猛反弹的可能', avoidNote: '趋势市反转策略亏钱' },
  CMD_VOLATILITY: { humanLabel: '商品波动率', humanDesc: '商品比股票更刺激，波动率更高', avoidNote: '低波动期后可能爆发' },
  CMD_SKEWNESS: { humanLabel: '收益偏度', humanDesc: '商品天然有正偏度', avoidNote: '做空的负偏度风险比做多更大' },
  CMD_EIA_CRUDE: { humanLabel: '美油库存', humanDesc: 'EIA每周原油库存报告=油价方向标', avoidNote: '数据漂移会让报告失真' },
  CMD_NATGAS_STORAGE: { humanLabel: '天然气库存', humanDesc: '储气量偏离正常值=气价要变天', avoidNote: '天气才是天然气短期最大变量' },
  CMD_LME_INVENTORY: { humanLabel: 'LME库存', humanDesc: '伦敦金属交易所的金属库存=供给信号', avoidNote: '场外库存不在此统计中' },
  CMD_GOLD_ETF: { humanLabel: '黄金持仓', humanDesc: '黄金ETF流入/流出=市场避嫌需求', avoidNote: 'ETF流量滞后金价，不是领先指标' },
  CMD_BALANCE_SHEET: { humanLabel: '供需表', humanDesc: '全球供需平衡预估，缺=涨，剩=跌', avoidNote: 'USDA/EIA的预测经常大幅修正' },

  // ── Green/Supplement Factors ──
  GROSS_MARGIN: { humanLabel: '毛利护城河', humanDesc: '毛利率高的公司有定价权，不怕竞争', avoidNote: '薄利多销商业模式毛利低但ROE高' },
  DEBT_TO_EQUITY: { humanLabel: '财务杠杆', humanDesc: '负债相对股东的比率，越高越激进', avoidNote: '金融机构天然高杠杆不能简单对比' },
  FUND_FLOW: { humanLabel: '资金净流', humanDesc: '资金在流入还是流出这只股票', avoidNote: '日内资金流数据噪声大' },
  ETF_FLOW: { humanLabel: 'ETF资金', humanDesc: 'ETF大额申购赎回反映市场情绪', avoidNote: '做市商申购不算真实需求' },
  DIVIDEND_CHANGE: { humanLabel: '股息变动', humanDesc: '股息提高=公司信心足，降低=小心', avoidNote: '一次性特别股息没有持续性' },
  SECTOR_STRENGTH: { humanLabel: '行业强弱', humanDesc: '哪个行业最强？资金在往哪里流', avoidNote: '行业轮动太快时此指标失效' },
  IV_RANK: { humanLabel: '期权贵贱', humanDesc: '当前期权贵还是便宜？贵=市场焦虑', avoidNote: '合理溢价由基本面决定不只是情绪' },
  CURRENCY_EFFECT: { humanLabel: '汇兑损益', humanDesc: '非本币资产因汇率变动产生的额外损益', avoidNote: '对冲成本高，散户基本不适用' },
  FREE_CASH_FLOW_YIELD: { humanLabel: '白现金流率', humanDesc: '自由现金流除以市值的比率，真金白银', avoidNote: '周期性企业高点买入时FCF率虚高' },
  EQUITY_MULTIPLIER: { humanLabel: '权益乘数', humanDesc: '总资产除以净资产，杠杆高=风险高', avoidNote: '不同行业正常杠杆水平不同' },
  DISPOSITION_EFFECT: { humanLabel: '捂亏行为', humanDesc: '散户死捂亏损股的心理偏差指标', avoidNote: '仅适用于市场恐慌期' },
  ANCHORING: { humanLabel: '锚定效应', humanDesc: '散户参考历史高/低价的非理性心理', avoidNote: '锚定价格无逻辑基础纯心理因素' },
  AH_PREMIUM_CHANGE: { humanLabel: 'AH价差动向', humanDesc: 'AH溢价在扩大还是收窄？收窄=有利', avoidNote: '价差受资本管制影响可能长期存在' },
  HSI_CONSTITUENT: { humanLabel: '恒指权重', humanDesc: '恒生指数成分股权重变化的影响', avoidNote: '被动基金调仓一次性事件' },
  HK_REIT_YIELD: { humanLabel: 'REIT收租', humanDesc: '港股REIT的股息收益率吸引力', avoidNote: '利率上升会打压REIT估值' },
  US_EARNINGS_CALENDAR: { humanLabel: '财报日历', humanDesc: '美股即将发布财报的公司和时间', avoidNote: '已预期的财报不会产生交易机会' },
  US_SECTOR_ROTATION: { humanLabel: '美股轮动', humanDesc: '美股11个板块之间的资金轮动方向', avoidNote: '宏观事件会同时影响所有板块' },
  US_SMALL_CAP_MOMENTUM: { humanLabel: '小盘股动量', humanDesc: '美股小盘股的趋势追踪', avoidNote: '小盘股流动性差，动量信号不稳定' },
  US_DIVIDEND_ARISTOCRATS: { humanLabel: '股息贵族', humanDesc: '连续25年+提高股息的美股公司', avoidNote: '费率较高，ETF管理费侵蚀收益' },
  US_SP500_EQUAL_WEIGHT: { humanLabel: '等权重指数', humanDesc: '看标普500去掉巨头加权后的真实表现', avoidNote: '等权重意味着更高的小盘敞口' },

  // ── Supplement: Cross-Market ──
  XM_MKTCAP_EXPOSURE: { humanLabel: '跨市市值', humanDesc: '不同市场的市值敞口对比，找低配高配', avoidNote: '数据滞后，市值变化已反映在价格中' },
  XM_LIQUIDITY: { humanLabel: '跨市流动', humanDesc: '各市场流动性对比，钱去哪一目了然', avoidNote: '流动性指标变化慢，可能是滞后信号' },
  XM_DIVIDEND_ARAMA: { humanLabel: '跨市股息', humanDesc: '比较各国股息率，找全球最划算的分红', avoidNote: '税率差异让名义股息没有可比性' },

  // ── Supplement: Commodity Advanced ──
  CMD_COT_LONG: { humanLabel: 'COT多头', humanDesc: '商业/非商业多头持仓变化', avoidNote: '商业持仓是套保不是投机' },
  CMD_COT_SHORT: { humanLabel: 'COT空头', humanDesc: '空头集中度极端时容易反转', avoidNote: 'COT数据周五发布，有3天滞后' },
  CMD_COT_SPREAD: { humanLabel: 'COT价差', humanDesc: '多空持仓差=极端值时市场可能反转', avoidNote: '结构市场中持仓差会持续极端' },
  CMD_REAL_GOLD: { humanLabel: '实际金价', humanDesc: '剔除通胀后的金价=真实避险需求', avoidNote: '名义金价受美元影响更大' },
  CMD_GOLD_SILVER_RATIO: { humanLabel: '金银比', humanDesc: '金比银贵多少？极端值暗示拐点', avoidNote: '比率可能在新常态维持很久' },
  CMD_OIL_VOL: { humanLabel: '原油波幅', humanDesc: '油价的隐含波动率，高=地缘风险溢价', avoidNote: '战争溢价消退时波动率会暴跌' },
  CMD_COMMODITY_CURVE: { humanLabel: '曲线形态', humanDesc: '全期限的价格曲线形态分析', avoidNote: '现货可用库存少可维持现货溢价很久' },
  CMD_SEASONAL: { humanLabel: '商品季节', humanDesc: '农产品/能源的季节性波动规律', avoidNote: '天气异常时季节性规律完全失效' },
  CMD_OPEN_INTEREST: { humanLabel: '持仓总量', humanDesc: '总持仓量增=资金在进场', avoidNote: '持仓量的变化方向比绝对值重要' },
  CMD_SPREAD_RATIO: { humanLabel: '跨品种套利', humanDesc: '相关商品之间的价差=套利机会', avoidNote: '相关不等于套利，可能价格分化有理' },
};

export default FACTOR_HUMAN_COPY;
