// R188 J1: 34 Market-Specific Yellow Factor Calculators
// HK(9) + US(12) + Crypto(13) — built on R184 templates.
// Starred factors: HK_SHORT_SELL_RATIO, US_13F_FLOW, CRYPTO_SOPR, CRYPTO_OI_QUADRANT
import { createFactorCalculator } from './factor-calculator';
import type { FactorInput, PriceSnapshot, FactorCalculator } from './factor-calculator';
import type { FactorId } from './factor-id-registry';

export function createAllMarketYellowFactorCalculators(): FactorCalculator[] {
  return [

    // ========== HK 9 ==========
createFactorCalculator({ type: 'signal', factorId: 'HK_CBBC_RATIO', level1: 'L1_HK', level2: 'L2_SENTIMENT', label: 'CBBC Ratio', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const r = input.extra?.cbbcRatio as number ?? 0.5; if (r > 0.7) return { signal: -1, strength: 0.7 }; if (r < 0.3) return { signal: 1, strength: 0.7 }; return { signal: 0 }; } }),
createFactorCalculator({ type: 'rank', factorId: 'HK_WARRANT_TURNOVER', level1: 'L1_HK', level2: 'L2_FLOW', label: 'Warrant Turnover', valueExtractor: (input: FactorInput) => (input.extra?.warrantTurnover as number) ?? 0, ascending: false }),
createFactorCalculator({ type: 'rank', factorId: 'HK_CBBC_DISTANCE', level1: 'L1_HK', level2: 'L2_RISK', label: 'CBBC Distance', valueExtractor: (input: FactorInput) => (input.extra?.cbbcDistance as number) ?? 0.1, ascending: true }),
createFactorCalculator({ type: 'signal', factorId: 'HK_SHORT_SELL_RATIO', level1: 'L1_HK', level2: 'L2_FLOW', label: 'Short Sell Ratio (star)', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const ss = input.extra?.shortSellRatio as number ?? 0.1; if (ss > 0.25) return { signal: -1, strength: 0.9 }; if (ss > 0.15) return { signal: -1, strength: 0.5 }; if (ss < 0.05) return { signal: 1, strength: 0.6 }; return { signal: 0 }; } }),
createFactorCalculator({ type: 'rank', factorId: 'HK_REIT_YIELD', level1: 'L1_HK', level2: 'L2_YIELD', label: 'REIT Yield', valueExtractor: (input: FactorInput) => (input.extra?.reitYield as number) ?? 0.04, ascending: false }),
createFactorCalculator({ type: 'rank', factorId: 'HK_HSCEI_PREMIUM', level1: 'L1_HK', level2: 'L2_PRICING', label: 'HSCEI Premium', valueExtractor: (input: FactorInput) => (input.extra?.hsceiPremium as number) ?? 0, ascending: true }),
createFactorCalculator({ type: 'signal', factorId: 'HK_ETF_FLOW', level1: 'L1_HK', level2: 'L2_FLOW', label: 'HK ETF Flow', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const f = input.extra?.hkEtfNetFlow as number ?? 0; if (f > 1e8) return { signal: 1, strength: 0.7 }; if (f < -1e8) return { signal: -1, strength: 0.7 }; return { signal: 0 }; } }),
createFactorCalculator({ type: 'rank', factorId: 'HK_DIV_TAX_ADV', level1: 'L1_HK', level2: 'L2_VALUE', label: 'Dividend Tax Advantage', valueExtractor: (input: FactorInput) => (input.extra?.divTaxAdvantage as number) ?? 0, ascending: false }),
createFactorCalculator({ type: 'rank', factorId: 'HK_BOARD_ROTATION', level1: 'L1_HK', level2: 'L2_SENTIMENT', label: 'Board Rotation', valueExtractor: (input: FactorInput) => (input.extra?.boardRotation as number) ?? 0.5, ascending: false }),

    // ========== US 12 ==========
createFactorCalculator({ type: 'rank', factorId: 'US_EARNINGS_REVISION', level1: 'L1_US', level2: 'L2_EVENT', label: 'Earnings Revision', valueExtractor: (input: FactorInput) => (input.extra?.earningsRevisionPct as number) ?? 0, ascending: false }),
createFactorCalculator({ type: 'signal', factorId: 'US_REVENUE_SURPRISE', level1: 'L1_US', level2: 'L2_EVENT', label: 'Revenue Surprise', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const s = input.extra?.revenueSurprisePct as number ?? 0; if (s > 5) return { signal: 1, strength: 0.8 }; if (s > 2) return { signal: 1, strength: 0.4 }; if (s < -5) return { signal: -1, strength: 0.8 }; if (s < -2) return { signal: -1, strength: 0.4 }; return { signal: 0 }; } }),
createFactorCalculator({ type: 'rank', factorId: 'US_OI_PUT_CALL', level1: 'L1_US', level2: 'L2_SENTIMENT', label: 'OI Put/Call', valueExtractor: (input: FactorInput) => (input.extra?.oiPutCallRatio as number) ?? 0.7, ascending: true }),
createFactorCalculator({ type: 'signal', factorId: 'US_VOLUME_PCR', level1: 'L1_US', level2: 'L2_SENTIMENT', label: 'Volume PCR', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const pcr = input.extra?.volumePcr as number ?? 0.7; if (pcr > 1.2) return { signal: -1, strength: 0.8 }; if (pcr < 0.5) return { signal: 1, strength: 0.6 }; return { signal: 0 }; } }),
createFactorCalculator({ type: 'rank', factorId: 'US_IV_RANK', level1: 'L1_US', level2: 'L2_VOLATILITY', label: 'IV Rank', valueExtractor: (input: FactorInput) => (input.extra?.ivRank as number) ?? 0.5, ascending: true }),
createFactorCalculator({ type: 'signal', factorId: 'US_13F_FLOW', level1: 'L1_US', level2: 'L2_EVENT', label: '13F Flow (star)', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const f = input.extra?.thirteenFFlow as number ?? 0; if (f > 0.05) return { signal: 1, strength: 0.9 }; if (f > 0.01) return { signal: 1, strength: 0.5 }; if (f < -0.05) return { signal: -1, strength: 0.9 }; return { signal: 0 }; } }),
createFactorCalculator({ type: 'rank', factorId: 'US_BUYBACK_YIELD', level1: 'L1_US', level2: 'L2_VALUE', label: 'Buyback Yield', valueExtractor: (input: FactorInput) => (input.extra?.buybackYield as number) ?? 0.01, ascending: false }),
createFactorCalculator({ type: 'rank', factorId: 'US_SHORT_FLOAT', level1: 'L1_US', level2: 'L2_SENTIMENT', label: 'Short Float', valueExtractor: (input: FactorInput) => (input.extra?.shortFloat as number) ?? 0.05, ascending: true }),
createFactorCalculator({ type: 'signal', factorId: 'US_RETAIL_FLOW', level1: 'L1_US', level2: 'L2_FLOW', label: 'Retail Flow', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const f = input.extra?.retailFlow as number ?? 0; if (f > 1e7) return { signal: 1, strength: 0.6 }; if (f < -1e7) return { signal: -1, strength: 0.6 }; return { signal: 0 }; } }),
createFactorCalculator({ type: 'signal', factorId: 'US_MEME_STOCK', level1: 'L1_US', level2: 'L2_SOCIAL', label: 'Meme Stock Heat', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const h = input.extra?.memeHeat as number ?? 0; if (h > 0.8) return { signal: 0, reasoning: 'meme-elevated: high volatility risk' }; if (h > 0.5) return { signal: 1, strength: 0.3 }; return { signal: 0 }; } }),
createFactorCalculator({ type: 'rank', factorId: 'US_SECTOR_ETF_FLOW', level1: 'L1_US', level2: 'L2_FLOW', label: 'Sector ETF Flow', valueExtractor: (input: FactorInput) => (input.extra?.sectorEtfFlow as number) ?? 0, ascending: false }),
createFactorCalculator({ type: 'signal', factorId: 'US_SEASONALITY', level1: 'L1_US', level2: 'L2_STATS', label: 'Seasonality', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const s = input.extra?.seasonalityScore as number ?? 0; if (s > 0.7) return { signal: 1, strength: 0.5 }; if (s < 0.3) return { signal: -1, strength: 0.5 }; return { signal: 0 }; } }),

    // ========== Crypto 13 ==========
createFactorCalculator({ type: 'signal', factorId: 'CRYPTO_SOPR', level1: 'L1_CRYPTO', level2: 'L2_ONCHAIN', label: 'SOPR (star)', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const sopr = input.extra?.sopr as number ?? 1; if (sopr > 1.05) return { signal: -1, strength: 0.7 }; if (sopr < 0.98) return { signal: 1, strength: 0.7 }; return { signal: 0 }; } }),
createFactorCalculator({ type: 'rank', factorId: 'CRYPTO_HASHRATE', level1: 'L1_CRYPTO', level2: 'L2_ONCHAIN', label: 'Hashrate Change', valueExtractor: (input: FactorInput) => (input.extra?.hashrateChange as number) ?? 0, ascending: false }),
createFactorCalculator({ type: 'rank', factorId: 'CRYPTO_L2_TVL', level1: 'L1_CRYPTO', level2: 'L2_ONCHAIN', label: 'L2 TVL', valueExtractor: (input: FactorInput) => (input.extra?.l2Tvl as number) ?? 0, ascending: false }),
createFactorCalculator({ type: 'signal', factorId: 'CRYPTO_USDT_PREMIUM', level1: 'L1_CRYPTO', level2: 'L2_PRICING', label: 'USDT Premium', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const p = input.extra?.usdtPremium as number ?? 0; if (p > 0.02) return { signal: 1, strength: 0.6 }; if (p < -0.02) return { signal: -1, strength: 0.6 }; return { signal: 0 }; } }),
createFactorCalculator({ type: 'rank', factorId: 'CRYPTO_SOCIAL_VOLUME', level1: 'L1_CRYPTO', level2: 'L2_SOCIAL', label: 'Social Volume', valueExtractor: (input: FactorInput) => (input.extra?.socialVolume as number) ?? 0, ascending: false }),
createFactorCalculator({ type: 'signal', factorId: 'CRYPTO_WHALE_MOVEMENT', level1: 'L1_CRYPTO', level2: 'L2_ONCHAIN', label: 'Whale Movement', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const w = input.extra?.whaleMovement as number ?? 0; if (w > 5000) return { signal: -1, strength: 0.8 }; if (w > 1000) return { signal: -1, strength: 0.5 }; return { signal: 0 }; } }),
createFactorCalculator({ type: 'rank', factorId: 'CRYPTO_PERP_PREMIUM', level1: 'L1_CRYPTO', level2: 'L2_DERIVATIVES', label: 'Perp Premium', valueExtractor: (input: FactorInput) => (input.extra?.perpPremium as number) ?? 0.001, ascending: true }),
createFactorCalculator({ type: 'signal', factorId: 'CRYPTO_OI_QUADRANT', level1: 'L1_CRYPTO', level2: 'L2_DERIVATIVES', label: 'OI Quadrant (star)', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const oiA = input.extra?.oiDelta as number ?? 0; const priceA = input.extra?.priceD1 as number ?? 0; if (oiA > 0.05 && priceA > 0.02) return { signal: 1, strength: 0.8 }; if (oiA > 0.05 && priceA < -0.02) return { signal: -1, strength: 0.9 }; if (oiA < -0.05 && priceA < -0.02) return { signal: 1, strength: 0.5 }; if (oiA < -0.05 && priceA > 0.02) return { signal: -1, strength: 0.5 }; return { signal: 0 }; } }),
createFactorCalculator({ type: 'rank', factorId: 'CRYPTO_GAS_TREND', level1: 'L1_CRYPTO', level2: 'L2_ONCHAIN', label: 'Gas Trend', valueExtractor: (input: FactorInput) => (input.extra?.gasTrend as number) ?? 0, ascending: true }),
createFactorCalculator({ type: 'rank', factorId: 'CRYPTO_BTC_DOM_CHANGE', level1: 'L1_CRYPTO', level2: 'L2_CORRELATION', label: 'BTC Dominance Change', valueExtractor: (input: FactorInput) => (input.extra?.btcDomChange as number) ?? 0, ascending: false }),
createFactorCalculator({ type: 'rank', factorId: 'CRYPTO_PERP_BASIS', level1: 'L1_CRYPTO', level2: 'L2_DERIVATIVES', label: 'Perp Basis', valueExtractor: (input: FactorInput) => (input.extra?.perpBasis as number) ?? 0, ascending: false }),
createFactorCalculator({ type: 'signal', factorId: 'CRYPTO_TAKER_RATIO', level1: 'L1_CRYPTO', level2: 'L2_SENTIMENT', label: 'Taker Ratio', signalFn: (input: FactorInput, _h: PriceSnapshot[]) => { const t = input.extra?.takerRatio as number ?? 1; if (t > 1.2) return { signal: 1, strength: 0.7 }; if (t < 0.8) return { signal: -1, strength: 0.7 }; return { signal: 0 }; } }),
createFactorCalculator({ type: 'rank', factorId: 'CRYPTO_DEV_ACTIVITY', level1: 'L1_CRYPTO', level2: 'L2_ONCHAIN', label: 'Dev Activity', valueExtractor: (input: FactorInput) => (input.extra?.devActivity as number) ?? 0, ascending: false }),
createFactorCalculator({ type: 'rank', factorId: 'CRYPTO_INFLATION', level1: 'L1_CRYPTO', level2: 'L2_ONCHAIN', label: 'Crypto Inflation', valueExtractor: (input: FactorInput) => (input.extra?.cryptoInflation as number) ?? 0.05, ascending: true }),
  ];
}

export function getMarketYellowFactorCount(): number {
  return createAllMarketYellowFactorCalculators().length;
}