// R187 J1: 34 Yellow Factor Calculators
// Built on R184 templates (RatioCalculator/RankCalculator/SignalCalculator).
// Includes 4 downgraded from Phase 1 green level.
import { createFactorCalculator } from './factor-calculator';
import type { FactorInput, PriceSnapshot, FactorCrossSectionResult, FactorCalculator } from './factor-calculator';
import type { FactorId } from './factor-id-registry';

export function createAllYellowFactorCalculators(): FactorCalculator[] {
  return [
    // === A1 Value (3) ===
    createFactorCalculator({ type: 'ratio', factorId: 'SALES_TO_PRICE', level1: 'L1_CLASSIC', level2: 'L2_VALUE', label: 'Sales to Price', numerator: 'revenue', denominator: 'close', invert: true, denominatorFloor: 1e-10 }),
    createFactorCalculator({ type: 'ratio', factorId: 'CASH_FLOW_YIELD', level1: 'L1_CLASSIC', level2: 'L2_VALUE', label: 'Cash Flow Yield', numerator: 'operatingCashFlow', denominator: 'close', invert: true, denominatorFloor: 1e-10 }),
    createFactorCalculator({ type: 'rank', factorId: 'PEG_RATIO', level1: 'L1_CLASSIC', level2: 'L2_GROWTH', label: 'PEG Ratio', valueExtractor: (input: FactorInput) => { const pe = (input.fundamental?.eps && input.fundamental.eps > 0) ? input.priceData.close / input.fundamental.eps : 0; const g = (input.extra?.earningsGrowth as number) ?? 0.05; return (g > 0 && pe > 0) ? pe / g : 999; }, ascending: true }),
    // === A2 Quality (3) ===
    createFactorCalculator({ type: 'ratio', factorId: 'ROIC', level1: 'L1_FUNDAMENTAL', level2: 'L2_PROFIT_QUALITY', label: 'ROIC', numerator: 'netIncome', denominator: 'totalAssets', invert: false, denominatorFloor: 1 }),
    createFactorCalculator({ type: 'rank', factorId: 'ASSET_TURNOVER', level1: 'L1_FUNDAMENTAL', level2: 'L2_EFFICIENCY', label: 'Asset Turnover', valueExtractor: (input: FactorInput) => { const rev = input.fundamental?.revenue; const ta = input.fundamental?.totalAssets; return (rev && ta && ta > 0) ? rev / ta : 0; }, ascending: false }),
    createFactorCalculator({ type: 'signal', factorId: 'PIOTROSKI_F', level1: 'L1_FUNDAMENTAL', level2: 'L2_HEALTH', label: 'Piotroski F-Score', signalFn: (input: FactorInput, _history: PriceSnapshot[]) => { const f = input.fundamental?.fScore; if (f === undefined) return { signal: 0 }; if (f >= 7) return { signal: 1, strength: 0.9 }; if (f >= 5) return { signal: 1, strength: 0.5 }; if (f <= 2) return { signal: -1, strength: 0.8 }; if (f <= 4) return { signal: -1, strength: 0.4 }; return { signal: 0 }; } }),
    // === A3 Low Vol (2) ===
    createFactorCalculator({ type: 'rank', factorId: 'IDIO_VOL', level1: 'L1_RISK', level2: 'L2_VOLATILITY', label: 'Idiosyncratic Volatility', valueExtractor: (input: FactorInput) => { return (input.extra?.idiosyncraticVol as number) ?? 0.25; }, ascending: true }),
    createFactorCalculator({ type: 'rank', factorId: 'DOWNSIDE_VOL', level1: 'L1_RISK', level2: 'L2_DOWNSIDE', label: 'Downside Volatility', valueExtractor: (input: FactorInput) => (input.extra?.downsideVol as number) ?? 0.20, ascending: true }),
    // === A4 Sentiment (3) ===
    createFactorCalculator({ type: 'signal', factorId: 'ANALYST_REVISION', level1: 'L1_SENTIMENT', level2: 'L2_FORECAST', label: 'Analyst Revision', signalFn: (input: FactorInput, _history: PriceSnapshot[]) => { const rev = input.extra?.analystRevisionPct as number; if (rev === undefined) return { signal: 0 }; if (rev > 5) return { signal: 1, strength: 0.8 }; if (rev > 0) return { signal: 1, strength: 0.4 }; if (rev < -5) return { signal: -1, strength: 0.8 }; if (rev < 0) return { signal: -1, strength: 0.4 }; return { signal: 0 }; } }),
    createFactorCalculator({ type: 'signal', factorId: 'SHORT_INTEREST', level1: 'L1_SENTIMENT', level2: 'L2_FLOW', label: 'Short Interest', signalFn: (input: FactorInput, _history: PriceSnapshot[]) => { const si = input.extra?.shortInterestPct as number; if (si === undefined) return { signal: 0 }; if (si > 20) return { signal: -1, strength: 0.9 }; if (si > 10) return { signal: -1, strength: 0.5 }; if (si < 2) return { signal: 1, strength: 0.6 }; return { signal: 0 }; } }),
    createFactorCalculator({ type: 'signal', factorId: 'ETF_FLOW_ADVANCED', level1: 'L1_SENTIMENT', level2: 'L2_FLOW', label: 'ETF Flow Advanced', signalFn: (input: FactorInput, _history: PriceSnapshot[]) => { const flow = input.extra?.etfNetFlow as number; const mcap = input.fundamental?.marketCap ?? 1e9; if (flow === undefined || mcap <= 0) return { signal: 0 }; const ratio = flow / mcap; if (ratio > 0.02) return { signal: 1, strength: 0.9 }; if (ratio > 0.005) return { signal: 1, strength: 0.5 }; if (ratio < -0.02) return { signal: -1, strength: 0.8 }; if (ratio < -0.005) return { signal: -1, strength: 0.4 }; return { signal: 0 }; } }),
    // === A5 Macro (2) ===
    createFactorCalculator({ type: 'rank', factorId: 'INFLATION_BETA', level1: 'L1_MACRO', level2: 'L2_SENSITIVITY', label: 'Inflation Beta', valueExtractor: (input: FactorInput) => (input.extra?.inflationBeta as number) ?? 0, ascending: false }),
    createFactorCalculator({ type: 'rank', factorId: 'RATE_SENSITIVITY', level1: 'L1_MACRO', level2: 'L2_SENSITIVITY', label: 'Rate Sensitivity', valueExtractor: (input: FactorInput) => (input.extra?.rateSensitivity as number) ?? 0, ascending: true }),
    // === A6 Theme (3) ===
    createFactorCalculator({ type: 'rank', factorId: 'THEME_AI', level1: 'L1_EVENT', level2: 'L2_CORPORATE', label: 'AI Theme Exposure', valueExtractor: (input: FactorInput) => (input.extra?.aiThemeExposure as number) ?? 0, ascending: false }),
    createFactorCalculator({ type: 'rank', factorId: 'THEME_GREEN', level1: 'L1_EVENT', level2: 'L2_ENVIRONMENT', label: 'Green Theme Exposure', valueExtractor: (input: FactorInput) => (input.extra?.greenThemeExposure as number) ?? 0, ascending: false }),
    createFactorCalculator({ type: 'rank', factorId: 'THEME_CONSUMPTION', level1: 'L1_EVENT', level2: 'L2_CORPORATE', label: 'Consumption Theme Exposure', valueExtractor: (input: FactorInput) => (input.extra?.consumptionThemeExposure as number) ?? 0, ascending: false }),
    // === A7 Options (3) ===
    createFactorCalculator({ type: 'rank', factorId: 'IV_SKEW', level1: 'L1_SENTIMENT', level2: 'L2_OPTIONS', label: 'IV Skew', valueExtractor: (input: FactorInput) => (input.extra?.ivSkew as number) ?? 0, ascending: true }),
    createFactorCalculator({ type: 'rank', factorId: 'IV_RANK_ADVANCED', level1: 'L1_SENTIMENT', level2: 'L2_OPTIONS', label: 'IV Rank Advanced', valueExtractor: (input: FactorInput) => { const ivRank = (input.extra?.ivRank as number) ?? 0.5; const ivSkew = (input.extra?.ivSkew as number) ?? 0; return ivRank * 0.7 + Math.abs(ivSkew) * 0.3; }, ascending: true }),
    createFactorCalculator({ type: 'signal', factorId: 'PUT_CALL_RATIO', level1: 'L1_SENTIMENT', level2: 'L2_OPTIONS', label: 'Put/Call Ratio', signalFn: (input: FactorInput, _history: PriceSnapshot[]) => { const pcr = input.extra?.putCallRatio as number; if (pcr === undefined) return { signal: 0 }; if (pcr > 1.5) return { signal: -1, strength: 0.9 }; if (pcr > 1.0) return { signal: -1, strength: 0.5 }; if (pcr < 0.5) return { signal: 1, strength: 0.7 }; if (pcr < 0.7) return { signal: 1, strength: 0.4 }; return { signal: 0 }; } }),
    // === A8 Event (3) ===
    createFactorCalculator({ type: 'signal', factorId: 'EARNINGS_ESTIMATE', level1: 'L1_FUNDAMENTAL', level2: 'L2_EVENT', label: 'Earnings Estimate Trend', signalFn: (input: FactorInput, _history: PriceSnapshot[]) => { const trend = input.extra?.earningsEstimateTrend as number; if (trend === undefined) return { signal: 0 }; if (trend > 0.1) return { signal: 1, strength: 0.8 }; if (trend > 0) return { signal: 1, strength: 0.4 }; if (trend < -0.1) return { signal: -1, strength: 0.8 }; if (trend < 0) return { signal: -1, strength: 0.4 }; return { signal: 0 }; } }),
    createFactorCalculator({ type: 'signal', factorId: 'PRE_EARNINGS_IV', level1: 'L1_FUNDAMENTAL', level2: 'L2_EVENT', label: 'Pre-Earnings IV Crush', signalFn: (input: FactorInput, _history: PriceSnapshot[]) => { const days = input.extra?.daysToEarnings as number; const iv = input.extra?.ivRank as number ?? 0.5; if (days === undefined || iv === undefined) return { signal: 0 }; if (days <= 2 && iv > 0.8) return { signal: -1, strength: 0.8 }; if (days <= 5 && iv > 0.7) return { signal: -1, strength: 0.5 }; if (days > 20) return { signal: 0 }; return { signal: 0 }; } }),
    createFactorCalculator({ type: 'signal', factorId: 'INDEX_REBALANCE', level1: 'L1_EVENT', level2: 'L2_REBALANCE', label: 'Index Rebalance', signalFn: (input: FactorInput, _history: PriceSnapshot[]) => { const days = input.extra?.daysToRebalance as number; const direction = input.extra?.rebalanceDirection as string; if (days === undefined) return { signal: 0 }; if (days <= 3 && direction === 'add') return { signal: 1, strength: 0.9 }; if (days <= 3 && direction === 'remove') return { signal: -1, strength: 0.9 }; if (days <= 14 && direction === 'add') return { signal: 1, strength: 0.5 }; return { signal: 0 }; } }),
    // === A9 Fundamental Deep (5) ===
    createFactorCalculator({ type: 'ratio', factorId: 'FREE_CASH_FLOW', level1: 'L1_FUNDAMENTAL', level2: 'L2_VALUE_DEEP', label: 'Price to Free Cash Flow', numerator: 'close', denominator: 'freeCashFlow', invert: false, denominatorFloor: 1e-10 }),
    createFactorCalculator({ type: 'rank', factorId: 'OPERATING_MARGIN', level1: 'L1_FUNDAMENTAL', level2: 'L2_PROFIT_QUALITY', label: 'Operating Margin', valueExtractor: (input: FactorInput) => { const ocf = input.fundamental?.operatingCashFlow; const rev = input.fundamental?.revenue; return (ocf && rev && rev > 0) ? ocf / rev : 0; }, ascending: false }),
    createFactorCalculator({ type: 'rank', factorId: 'NET_MARGIN_STABILITY', level1: 'L1_FUNDAMENTAL', level2: 'L2_RISK_ADJUSTED', label: 'Net Margin Stability', valueExtractor: (input: FactorInput) => (input.extra?.netMarginStability as number) ?? 1, ascending: true }),
    createFactorCalculator({ type: 'rank', factorId: 'SALES_GROWTH_CONSISTENCY', level1: 'L1_FUNDAMENTAL', level2: 'L2_GROWTH', label: 'Sales Growth Consistency', valueExtractor: (input: FactorInput) => (input.extra?.salesGrowthConsistency as number) ?? 0.5, ascending: false }),
    createFactorCalculator({ type: 'rank', factorId: 'INVENTORY_TURNOVER', level1: 'L1_FUNDAMENTAL', level2: 'L2_EFFICIENCY', label: 'Inventory Turnover', valueExtractor: (input: FactorInput) => (input.extra?.inventoryTurnover as number) ?? 5, ascending: false }),
    // === A10 Behavioral (2) — downgraded from Green ===
    createFactorCalculator({ type: 'signal', factorId: 'DISPOSITION_EFFECT', level1: 'L1_SENTIMENT', level2: 'L2_SOCIAL', label: 'Disposition Effect', signalFn: (input: FactorInput, history: PriceSnapshot[]) => { if (history.length < 20) return { signal: 0 }; const cur = input.priceData.close; const p20 = history[history.length - 20]?.close ?? cur; const pct = (cur - p20) / p20; const volRecent = history.slice(-5).reduce((s, h) => s + (h.volume || 0), 0) / 5; const volPrev = history.slice(-20, -5).reduce((s, h) => s + (h.volume || 0), 0) / 15; const vr = volPrev > 0 ? volRecent / volPrev : 1; if (pct < -0.1 && vr > 1.5) return { signal: 1, strength: 0.7 }; if (pct > 0.1 && vr > 1.5) return { signal: -1, strength: 0.5 }; return { signal: 0 }; }, lookbackDays: 30 }),
    createFactorCalculator({ type: 'signal', factorId: 'ANCHORING', level1: 'L1_SENTIMENT', level2: 'L2_SOCIAL', label: 'Anchoring Effect', signalFn: (input: FactorInput, history: PriceSnapshot[]) => { if (history.length < 60) return { signal: 0 }; const h52 = Math.max(...history.slice(-252).map(h => h.high)); const l52 = Math.min(...history.slice(-252).map(h => h.low)); const cur = input.priceData.close; if ((cur - l52) / l52 < 0.05) return { signal: 1, strength: 0.6 }; if ((h52 - cur) / h52 < 0.05) return { signal: -1, strength: 0.6 }; return { signal: 0 }; }, lookbackDays: 252 }),
    // === A9-extra (1) — downgraded from Green ===
    createFactorCalculator({ type: 'rank', factorId: 'EQUITY_MULTIPLIER', level1: 'L1_FUNDAMENTAL', level2: 'L2_RISK_STRUCTURE', label: 'Equity Multiplier', valueExtractor: (input: FactorInput) => { const ta = input.fundamental?.totalAssets; const bv = input.fundamental?.bookValuePerShare; return (ta && bv && bv > 0) ? ta / bv : 0; }, ascending: false }),
    // === HK (1) — downgraded from Green ===
    createFactorCalculator({ type: 'signal', factorId: 'AH_PREMIUM_CHANGE', level1: 'L1_HK', level2: 'L2_PRICING', label: 'AH Premium Change', signalFn: (input: FactorInput, _history: PriceSnapshot[]) => { const pc = input.extra?.ahPremiumChange as number; if (pc === undefined) return { signal: 0 }; if (pc < -0.05) return { signal: 1, strength: 0.7 }; if (pc > 0.05) return { signal: -1, strength: 0.7 }; return { signal: 0 }; } }),
  ];
}

export function computeAllYellowFactors(inputs: FactorInput[]): FactorCrossSectionResult[] {
  const calculators = createAllYellowFactorCalculators();
  return calculators.map(calc => calc.computeCrossSection(inputs));
}

export function getYellowFactorCount(): number {
  return createAllYellowFactorCalculators().length;
}