// ── Generated by R184 generate-factor-i18n-batch.ts ──────────────────────
// Auto-generated locale index. Do not edit manually.
// Regenerate: npx ts-node scripts/generate-factor-i18n-batch.ts

import zh_CN from './factor-locale-zh-CN.json';
import zh_TW from './factor-locale-zh-TW.json';
import en from './factor-locale-en.json';
import ja from './factor-locale-ja.json';
import ko from './factor-locale-ko.json';
import fr from './factor-locale-fr.json';
import it from './factor-locale-it.json';
import de from './factor-locale-de.json';

export const FACTOR_LOCALES: Record<string, Record<string, unknown>> = {
  'zh-CN': zh_CN,
  'zh-TW': zh_TW,
  'en': en,
  'ja': ja,
  'ko': ko,
  'fr': fr,
  'it': it,
  'de': de,
};

export type FactorLocaleCode = 'zh-CN' | 'zh-TW' | 'en' | 'ja' | 'ko' | 'fr' | 'it' | 'de';

export interface FactorLocaleEntry {
  name: string;
  category: string;
  level: number;
  levelLabel: string;
  oneLine: string;
  description: string;
  highMeaning: string;
  lowMeaning: string;
  story: string;
  signaldesc: string;
}

export function getFactorLocale(
  factorId: string,
  lang: FactorLocaleCode,
): FactorLocaleEntry | undefined {
  const locale = FACTOR_LOCALES[lang] as Record<string, FactorLocaleEntry> | undefined;
  return locale?.[factorPrefix + factorId];
}

const factorPrefix = "factor.";

export function getFactorLocaleEntries(lang: FactorLocaleCode): Record<string, FactorLocaleEntry> {
  const locale = FACTOR_LOCALES[lang] as Record<string, FactorLocaleEntry>;
  const entries: Record<string, FactorLocaleEntry> = {};
  for (const [key, value] of Object.entries(locale)) {
    if (key.startsWith(factorPrefix)) {
      entries[key.replace(factorPrefix, "")] = value;
    }
  }
  return entries;
}
