// @ts-nocheck
// R236 ML#1: CompareExportUtils — CSV export + clipboard snapshot for strategy comparison

import type { StrategyCompareData } from './StrategyComparePanel';

// ── Export to CSV ────────────────────────────────────────────────────
export function exportCompareCSV(strategies: StrategyCompareData[]): string {
  const headers = [
    'Metric',
    ...strategies.map(s => s.name),
  ];
  
  const rows = [
    ['Annual Return (%)', ...strategies.map(s => s.annualReturn.toFixed(2))],
    ['Total Return (%)', ...strategies.map(s => s.totalReturn.toFixed(2))],
    ['Sharpe Ratio', ...strategies.map(s => s.sharpe.toFixed(3))],
    ['Sortino Ratio', ...strategies.map(s => s.sortino.toFixed(3))],
    ['Calmar Ratio', ...strategies.map(s => s.calmar.toFixed(3))],
    ['Max Drawdown (%)', ...strategies.map(s => s.maxDrawdown.toFixed(2))],
    ['Win Rate (%)', ...strategies.map(s => s.winRate.toFixed(2))],
    ['Volatility (%)', ...strategies.map(s => s.volatility.toFixed(2))],
    ['Beta', ...strategies.map(s => s.beta.toFixed(3))],
    ['Alpha (%)', ...strategies.map(s => s.alpha.toFixed(2))],
    ['VaR 95%', ...strategies.map(s => s.var95.toFixed(2))],
    ['CVaR 95%', ...strategies.map(s => s.cvar95.toFixed(2))],
    ['Profit Factor', ...strategies.map(s => s.profitFactor.toFixed(3))],
    ['Total Trades', ...strategies.map(s => s.trades.toString())],
    ['Avg Holding Days', ...strategies.map(s => s.avgHoldingDays.toString())],
    ['Market', ...strategies.map(s => s.market)],
    ['Style', ...strategies.map(s => s.style)],
  ];
  
  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  return csv;
}

export function downloadCompareCSV(strategies: StrategyCompareData[], filename?: string) {
  const csv = exportCompareCSV(strategies);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || `strategy-compare-${Date.now()}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// ── Copy to clipboard ────────────────────────────────────────────────
export async function copyCompareSnapshot(strategies: StrategyCompareData[]): Promise<boolean> {
  const lines = [
    '═══ Strategy Comparison Snapshot ═══',
    `Generated: ${new Date().toLocaleString()}`,
    '',
    ...strategies.map((s, i) => [
      `── ${i + 1}. ${s.name} (${s.market} · ${s.style}) ──`,
      `  Annual Return: ${s.annualReturn.toFixed(2)}%`,
      `  Sharpe: ${s.sharpe.toFixed(3)} | Sortino: ${s.sortino.toFixed(3)}`,
      `  Max DD: ${s.maxDrawdown.toFixed(2)}% | Win Rate: ${s.winRate.toFixed(1)}%`,
      `  Beta: ${s.beta.toFixed(2)} | Alpha: ${s.alpha.toFixed(2)}%`,
      `  Profit Factor: ${s.profitFactor.toFixed(2)}`,
      `  Factors: ${s.factors.map(f => `${f.name}(${f.weight}%)`).join(', ')}`,
      '',
    ].join('\n')),
    '═══ End Snapshot ═══',
  ].join('\n');
  
  try {
    await navigator.clipboard.writeText(lines);
    return true;
  } catch {
    return false;
  }
}

// ── Share as text ─────────────────────────────────────────────────────
export function shareCompareAsText(strategies: StrategyCompareData[]): string {
  const emoji = ['🥇', '🥈', '🥉'];
  const lines = [
    '📊 *Strategy Comparison*',
    '',
    ...strategies.map((s, i) =>
      `${emoji[i] || '•'} *${s.name}* (${s.market} | ${s.style})\n` +
      `   Return: ${s.annualReturn.toFixed(1)}% · Sharpe: ${s.sharpe.toFixed(2)} · Win: ${s.winRate.toFixed(0)}%\n` +
      `   MaxDD: ${s.maxDrawdown.toFixed(1)}% · Trades: ${s.trades} · PF: ${s.profitFactor.toFixed(2)}`
    ),
    '',
    '_Generated by quant-moo_',
  ];
  return lines.join('\n');
}
