// ══ R282 QClaw Task 1+2: 全量因子人话化文案 (6h+2h) ══
// 交付: src/lib/factor/factor-humanize-complete-r282.ts
//
// 覆盖: 320 核心因子 + 200 学术因子 + ESG70 + 全球96 = ~620+ 因子
// 每个因子含: label(≤15字) + desc(≤50字可操作) + dontUseWhen + 3秒摘要
// 3级折叠: L1=摘要信号 | L2=label+desc | L3=完整(desc+dontUseWhen+IC)
//
// 配合: ML R282 因子卡片折叠3级UI + youdao R282 人话化准确率验证

export interface FactorHumanized {
  id: string;
  nameEn: string;
  nameCn: string;
  /** ≤15字一句话标签 — 人类秒懂 */
  humanLabel: string;
  /** ≤50字使用建议 — 可操作 */
  humanDesc: string;
  /** ≤30字 — 什么时候别信这个因子 */
  dontUseWhen: string;
  /** 3秒摘要 — 因子卡折叠L1展示 */
  threeSecSummary: string;
  /** 3秒摘要的emoji */
  emoji: string;
  /** 折叠层级建议 */
  foldLevel: 'L1_only' | 'L2_label_desc' | 'L3_full';
}

// ═══════════ 核心因子人话化数据 ═══════════
// 按 L1 大类分组，每个条目严格遵照 Registry 的因子 ID

const CORE_FACTOR_HUMANIZE: Record<string, FactorHumanized[]> = {

  // ════════════════════════ 1. Classic Factor (Fama-French + Carhart) ════════════════════════
  L1_CLASSIC: [
    {
      id: 'MKT', nameEn: 'MarketBeta', nameCn: '市场Beta',
      humanLabel: '跟着大盘走多深',
      humanDesc: 'Beta高=涨跌都放大，牛市加仓用高Beta，熊市换低Beta防守。',
      dontUseWhen: '震荡市Beta没方向性，高和低都不准。',
      threeSecSummary: '你的股票波动比大盘大还是小',
      emoji: '📈', foldLevel: 'L2_label_desc',
    },
    {
      id: 'SIZE', nameEn: 'Size', nameCn: '规模效应',
      humanLabel: '小票有大机会吗',
      humanDesc: '历史上下盘股长期跑赢大盘。牛市后半段小票补涨最明显。',
      dontUseWhen: '资金收紧时小票最先被抛，别在加息周期重仓小票。',
      threeSecSummary: '公司越大越好还是越小越赚',
      emoji: '🐟', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HML', nameEn: 'BookToMarket', nameCn: '市净率估值',
      humanLabel: '便宜货是真的便宜吗',
      humanDesc: '低PB的股票如果资产质量不差往往被低估，价值投资者的筛子。',
      dontUseWhen: '金融/地产的PB天然低，跨行业比会错过真赚钱的公司。',
      threeSecSummary: '你买的是净资产打折还是价值陷阱',
      emoji: '🏷️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'EP_RATIO', nameEn: 'EarningsYield', nameCn: '市盈率倒数',
      humanLabel: '每块钱投资赚多少',
      humanDesc: 'E/P越高越有投资价值，可直接和国债收益率比——高了就划算。',
      dontUseWhen: '周期股盈利高时E/P反而低，别在顶点买入。',
      threeSecSummary: '你投的每一块钱一年能赚回多少',
      emoji: '💵', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CFP_RATIO', nameEn: 'CashFlowPrice', nameCn: '现金收益率',
      humanLabel: '赚的不是白条是现金',
      humanDesc: '现金流/股价 — 看公司赚的是真钱还是账面数字，比PE更诚实。',
      dontUseWhen: '重资产行业现金流天然高，不比轻资产公司直接判定优劣。',
      threeSecSummary: '公司赚的钱有多少真金白银',
      emoji: '💰', foldLevel: 'L3_full',
    },
    {
      id: 'MOM_12M', nameEn: 'Momentum12M', nameCn: '12月动量',
      humanLabel: '过去一年最强王者',
      humanDesc: '过去12个月涨最多的股票通常未来1-3个月还能领跑。牛市最强因子。',
      dontUseWhen: '市场风格切换时动量会反噬，历史回调平均-15%。',
      threeSecSummary: '追涨一年最强的 — 牛市的秘密武器',
      emoji: '🚀', foldLevel: 'L2_label_desc',
    },
    {
      id: 'MOM_6M', nameEn: 'Momentum6M', nameCn: '6月动量',
      humanLabel: '半年强势股追不追',
      humanDesc: '6个月涨幅靠前的股票中期趋势惯性最强，比12月动量换手更积极。',
      dontUseWhen: '财报季前动量会被打乱，持有到季末前减仓。',
      threeSecSummary: '半年冠军还能继续赢吗',
      emoji: '⚡', foldLevel: 'L2_label_desc',
    },
    {
      id: 'MOM_1M', nameEn: 'Momentum1M', nameCn: '1月动量',
      humanLabel: '追最近一个月跑得快的',
      humanDesc: '最近1个月强势的股票短期还有冲劲。超短线交易用，持3-5天。',
      dontUseWhen: '财报季前消息面多，会打乱短期动量。',
      threeSecSummary: '最近急涨的股票还会涨吗',
      emoji: '🔥', foldLevel: 'L2_label_desc',
    },
    {
      id: 'MOM_6_1', nameEn: 'Momentum6Minus1', nameCn: '6-1月动量',
      humanLabel: '涨了半年但最近歇了',
      humanDesc: '6月强势但1月走平的股票可能正在蓄力。中长线布局的最佳时机。',
      dontUseWhen: '如果1月在放量下跌，不是歇了是在出货，别接盘。',
      threeSecSummary: '长线看涨但短线在休息 — 上车机会？',
      emoji: '⏸️', foldLevel: 'L3_full',
    },
    {
      id: 'RMW', nameEn: 'RobustMinusWeak', nameCn: '盈利能力',
      humanLabel: '赚钱能力强的公司更稳',
      humanDesc: '高毛利/高利润率的公司长期跑赢。筛选「真赚钱」不是「看起来赚」。',
      dontUseWhen: '周期顶部时超强盈利可能是虚假的高点。',
      threeSecSummary: '公司赚钱的本事到底有多硬',
      emoji: '💪', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMA', nameEn: 'ConservativeMinusAggressive', nameCn: '投资风格',
      humanLabel: '保守扩张还是激进借钱',
      humanDesc: '资产扩张保守的公司长期比激进借钱的公司回报好，尤其在利率上升期。',
      dontUseWhen: '成长公司高资产增长是好事，不能一律否定。',
      threeSecSummary: '公司花钱的节奏告诉你长期风险',
      emoji: '🛡️', foldLevel: 'L3_full',
    },
    {
      id: 'QUAL', nameEn: 'Quality', nameCn: '质量综合',
      humanLabel: '看得见的优质公司',
      humanDesc: '综合ROE/利润率/低杠杆/稳定盈利，选「让人睡得着觉」的股票。',
      dontUseWhen: '极端牛市时垃圾股也涨，Quality因子会暂时落后。',
      threeSecSummary: '你买的是优质公司还是概念故事',
      emoji: '⭐', foldLevel: 'L2_label_desc',
    },
    {
      id: 'GROWTH', nameEn: 'Growth', nameCn: '成长性',
      humanLabel: '营收利润持续在涨吗',
      humanDesc: '收入/利润增速超过同行的公司有复利效应。买成长=买未来的盈利。',
      dontUseWhen: '高增长≠高回报——如果增速在变慢，股价会跌得更快。',
      threeSecSummary: '这家公司未来的赚钱速度会不会更快',
      emoji: '🌱', foldLevel: 'L2_label_desc',
    },
    {
      id: 'YIELD', nameEn: 'DividendYield', nameCn: '股息率',
      humanLabel: '躺着收分红的好公司',
      humanDesc: '股息率>4%是现金奶牛，熊市持有比银行利息好。适合稳健投资者。',
      dontUseWhen: '股息率突然变高可能是因为股价暴跌——那不是红利是陷阱。',
      threeSecSummary: '你每年靠分红收回多少本金',
      emoji: '💸', foldLevel: 'L2_label_desc',
    },
    {
      id: 'DIV_YIELD_12M', nameEn: 'DividendYield12M', nameCn: '12月股息率',
      humanLabel: '过去一年分红多少',
      humanDesc: '12个月累计股息率稳定在3%以上=财务健康且有回报意愿的好公司。',
      dontUseWhen: '一次性特别分红不能算进常规股息，别被一次大分红骗了。',
      threeSecSummary: '最近12个月公司给你分了多少钱',
      emoji: '📅', foldLevel: 'L2_label_desc',
    },
    {
      id: 'EBITDA_EV', nameEn: 'EBITDAtoEV', nameCn: 'EBITDA/企业价值',
      humanLabel: '看真实赚钱能力值不值',
      humanDesc: '比PE更诚实——不受资本结构和折旧方法影响，跨公司比较更公平。',
      dontUseWhen: '重资产公司折旧假不了，轻资产公司 EBITDA 虚高别被骗。',
      threeSecSummary: '把不同公司拉到同一标尺比赚钱能力',
      emoji: '⚖️', foldLevel: 'L3_full',
    },
    {
      id: 'GRAHAM_NET', nameEn: 'GrahamNetNet', nameCn: '格雷厄姆净净值',
      humanLabel: '低于清算价值的便宜货',
      humanDesc: '股价低于净流动资产=极端低估。巴菲特早年最喜欢的捡烟蒂策略。',
      dontUseWhen: '现在很少见，见到了往往真有坑——不是低估是等死。',
      threeSecSummary: '如果现在就清算，你买的价格比残值还低',
      emoji: '🔍', foldLevel: 'L3_full',
    },
  ],

  // ════════════════════════ 2. Fundamental Deep-Dive ════════════════════════
  L1_FUNDAMENTAL: [
    {
      id: 'ACCRUALS', nameEn: 'Accruals', nameCn: '应计利润',
      humanLabel: '赚的是真钱还是纸上富贵',
      humanDesc: '净利润偏离经营现金流越多=盈利质量越差。应计利润高的公司慎买。',
      dontUseWhen: '快速扩张期应计利润天然高，要结合行业阶段判断。',
      threeSecSummary: '公司账上赚钱但口袋里真有钱吗',
      emoji: '📋', foldLevel: 'L2_label_desc',
    },
    {
      id: 'EARNINGS_VARIABILITY', nameEn: 'EarningsVariability', nameCn: '盈利波动率',
      humanLabel: '赚钱忽高忽低的不敢拿',
      humanDesc: '盈利大幅波动的公司风险高。选盈利稳定的，比选盈利最高的更安全。',
      dontUseWhen: '初创公司盈利波动大是正常的，用这个筛会错过成长股。',
      threeSecSummary: '公司赚钱稳不稳 — 大起大落就是不靠谱',
      emoji: '🎢', foldLevel: 'L2_label_desc',
    },
    {
      id: 'GROSS_PROFITABILITY', nameEn: 'GrossProfitability', nameCn: '毛利润率',
      humanLabel: '卖的东西有多赚钱',
      humanDesc: '毛利率高的公司有护城河、定价权。持续>40%的值得长期持有。',
      dontUseWhen: '不同行业毛利率没有可比性，零售10%vs软件80%都正常。',
      threeSecSummary: '卖一块钱的东西，公司能赚几毛',
      emoji: '🏭', foldLevel: 'L2_label_desc',
    },
    {
      id: 'NET_PAYOUT', nameEn: 'NetPayout', nameCn: '净派息率',
      humanLabel: '真金白银还给股东多少',
      humanDesc: '分红+回购-再融资=股东真拿到手的钱。高净派息=管理层站在你这边。',
      dontUseWhen: '借债回购的净派息是虚的，要用自由现金流覆盖。',
      threeSecSummary: '管理层是真的在回馈你还是做样子',
      emoji: '🎁', foldLevel: 'L3_full',
    },
    {
      id: 'OPERATING_LEVERAGE', nameEn: 'OperatingLeverage', nameCn: '经营杠杆',
      humanLabel: '收入涨1%利润涨多少',
      humanDesc: '固定成本高的公司收入涨1%利润能涨3-5%。经济好时选高者，差时避开。',
      dontUseWhen: '收入下滑时杠杆反向放大——亏得更快。',
      threeSecSummary: '公司赚钱的弹性有多大',
      emoji: '🔧', foldLevel: 'L3_full',
    },
    {
      id: 'ASSET_TURNOVER', nameEn: 'AssetTurnover', nameCn: '资产周转率',
      humanLabel: '用资产有效率吗',
      humanDesc: '同样资产谁的营收更高。周转快=效率高，适合对比同行业公司。',
      dontUseWhen: '跨行业比较没意义，科技和制造不是一码事。',
      threeSecSummary: '一块钱资产一年能产生多少营收',
      emoji: '🔄', foldLevel: 'L3_full',
    },
    {
      id: 'CASH_FLOW_YIELD', nameEn: 'CashFlowYield', nameCn: '自由现金流收益率',
      humanLabel: '真正可支配的钱有多少',
      humanDesc: 'FCF/市值 >5%=公司有大量真钱可以分红/回购/再投资。比PE靠谱。',
      dontUseWhen: '周期性行业高点FCF虚高，低点时才是真正的买入窗口。',
      threeSecSummary: '公司真正能掏出来花的钱占你投入的多少',
      emoji: '🏦', foldLevel: 'L2_label_desc',
    },
    {
      id: 'DEBT_COVERAGE', nameEn: 'DebtCoverage', nameCn: '利息覆盖倍数',
      humanLabel: '欠的债能还得起吗',
      humanDesc: '营业利润/利息费用 >3倍=安全。越低越危险，高负债公司利息涨就完了。',
      dontUseWhen: '科技公司轻负债，利息覆盖倍数再高也不说明什么。',
      threeSecSummary: '公司赚的钱够还利息的几倍',
      emoji: '🏗️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'EARNINGS_SURPRISE', nameEn: 'EarningsSurprise', nameCn: '盈利超预期',
      humanLabel: '连续超预期才是真牛',
      humanDesc: '连续3季超预期的公司市场信心在上升。单次超预期可能是会计技巧。',
      dontUseWhen: '一次大幅超预期可能是财技处理，连续观察至少3季。',
      threeSecSummary: '公司报出来的业绩比大家想的更好还是更差',
      emoji: '🎯', foldLevel: 'L2_label_desc',
    },
    {
      id: 'EARN_QUALITY', nameEn: 'EarningsQuality', nameCn: '盈利质量',
      humanLabel: '利润来源干净吗',
      humanDesc: '综合现金含量/持续性/真实性。利润来源干净的公司在熊市回调小。',
      dontUseWhen: '不要过度依赖模型分数，要配合阅读财务报表。',
      threeSecSummary: '公司赚的利润是实打实还是靠做账',
      emoji: '🔬', foldLevel: 'L3_full',
    },
    {
      id: 'GROSS_MARGIN_TREND', nameEn: 'GrossMarginTrend', nameCn: '毛利率趋势',
      humanLabel: '赚钱能力是在变强吗',
      humanDesc: '毛利率持续上升=竞争力在加强，拐头向下是红色警报。趋势比绝对值重要。',
      dontUseWhen: '季节性波动不是趋势，别把Q4的环比错当恶化。',
      threeSecSummary: '公司卖东西的利润越来越高还是越来越薄',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'F_SCORE', nameEn: 'PiotroskiFScore', nameCn: 'F分数财务健康',
      humanLabel: '9道体检防踩雷',
      humanDesc: '盈利能力+杠杆+效率 9项检查。≥7分=财务健康，≤2分=高风险避雷。',
      dontUseWhen: 'F分数低但可能正在反转，这恰恰是价值投资的机会。',
      threeSecSummary: '公司财务体检9项 — 扫雷利器',
      emoji: '🩺', foldLevel: 'L2_label_desc',
    },
    {
      id: 'ROE_STABILITY', nameEn: 'RoeStability', nameCn: 'ROE稳定性',
      humanLabel: '股东回报稳不稳',
      humanDesc: 'ROE 5年稳定在15%以上=管理层靠谱。忽高忽低可能是财技操纵。',
      dontUseWhen: '新兴行业ROE刚开始低是正常的，不能用绝对数否决。',
      threeSecSummary: '老板帮你赚的钱每年稳定吗',
      emoji: '📏', foldLevel: 'L2_label_desc',
    },
    {
      id: 'INVENTORY_TURNOVER', nameEn: 'InventoryTurnover', nameCn: '存货周转率',
      humanLabel: '货卖得快不快',
      humanDesc: '库存周转加快=产品畅销或管理提升。转慢=可能滞销或积压。',
      dontUseWhen: '服务业没有存货，这个因子不适用。',
      threeSecSummary: '公司仓库里的货多久卖完一轮',
      emoji: '📦', foldLevel: 'L3_full',
    },
    {
      id: 'RECEIVABLE_TURNOVER', nameEn: 'ReceivableTurnover', nameCn: '应收账款周转',
      humanLabel: '客户有没有按时给钱',
      humanDesc: '应收账周转越慢说明客户拖欠越多。突然变慢可能是渠道压货或客户没钱。',
      dontUseWhen: '大项目制的公司应收周期长是正常的，不必过度解读。',
      threeSecSummary: '卖出去的东西，钱收回来了吗',
      emoji: '📬', foldLevel: 'L3_full',
    },
    {
      id: 'FREE_CASH_FLOW', nameEn: 'FreeCashFlow', nameCn: '自由现金流',
      humanLabel: '经营到手剩多少钱',
      humanDesc: '经营现金流-资本支出=公司能自由支配的钱。持续为正=健康。',
      dontUseWhen: '高增长公司FCF可以阶段性为负（投资扩张），不是卖出理由。',
      threeSecSummary: '公司把该花的都花了还剩多少钱',
      emoji: '💎', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CURRENT_RATIO', nameEn: 'CurrentRatio', nameCn: '流动比率',
      humanLabel: '短期还债能力够不够',
      humanDesc: '流动资产/流动负债 >2=安全。低于1=现金流紧张，可能短期要融资。',
      dontUseWhen: '超市/电商流动比率<1是正常的（快消模式），别误判。',
      threeSecSummary: '一年内要还的债，公司手里有没有足够的钱',
      emoji: '🧮', foldLevel: 'L3_full',
    },
    {
      id: 'INTEREST_COVERAGE', nameEn: 'InterestCoverage', nameCn: '利息覆盖',
      humanLabel: '赚的够不够付利息',
      humanDesc: 'EBIT/利息。>3安全，<1.5利息压力大债务可能滚雪球。',
      dontUseWhen: '零负债的公司这个数没意义，不代表就比有杠杆的好。',
      threeSecSummary: '赚的利润能覆盖利息几次',
      emoji: '📉', foldLevel: 'L3_full',
    },
    {
      id: 'ROA', nameEn: 'ROA', nameCn: '总资产回报率',
      humanLabel: '用全部资产的赚钱效率',
      humanDesc: '净利润/总资产。越高越好，说明了每块资产都能产生多少利润。',
      dontUseWhen: '不同行业ROA天然差异大，银行2%可能比科技20%还健康。',
      threeSecSummary: '公司把全部家当用到了会赚钱的地方吗',
      emoji: '🏢', foldLevel: 'L2_label_desc',
    },
    {
      id: 'DEBT_TO_EQUITY', nameEn: 'DebtToEquity', nameCn: '负债权益比',
      humanLabel: '借了多少倍自有资金',
      humanDesc: '负债/权益>2=激进借钱。经济好时放大回报，经济差时加倍亏损。',
      dontUseWhen: '金融行业高杠杆是商业模式，不能简单说危险。',
      threeSecSummary: '借的钱是自有资金的几倍',
      emoji: '⚡', foldLevel: 'L2_label_desc',
    },
    {
      id: 'GROSS_MARGIN', nameEn: 'GrossMargin', nameCn: '毛利率',
      humanLabel: '产品本身的赚钱率',
      humanDesc: '高毛利率=有定价权有壁垒。稳定在40%以上就是好生意。',
      dontUseWhen: '不同行业毛利率不可比，别拿苹果和沃尔玛比。',
      threeSecSummary: '卖产品的利润空间有多大',
      emoji: '🍎', foldLevel: 'L2_label_desc',
    },
    {
      id: 'DIVIDEND_CHANGE', nameEn: 'DividendChange', nameCn: '股息变化方向',
      humanLabel: '分红是在涨还是在降',
      humanDesc: '连续3年提高分红=管理层有信心。削减分红=最高级预警信号。',
      dontUseWhen: '一次性特别分红不算趋势，要剔除后再判断。',
      threeSecSummary: '给你的分红是越来越多还是越来越少',
      emoji: '📈', foldLevel: 'L2_label_desc',
    },
    {
      id: 'FREE_CASH_FLOW_YIELD', nameEn: 'FreeCashFlowYield', nameCn: '自由现金流收益率',
      humanLabel: '掏出来的真钱占多少',
      humanDesc: 'FCF/股价越高越好>10%很便宜。比PE诚实——现金流不容易造假。',
      dontUseWhen: '季度FCF波动大用TTM（滚动12个月）看，不要看单季。',
      threeSecSummary: '真钱收益 vs 账面收益 — 现金流不骗人',
      emoji: '💧', foldLevel: 'L2_label_desc',
    },
    {
      id: 'EQUITY_MULTIPLIER', nameEn: 'EquityMultiplier', nameCn: '权益乘数',
      humanLabel: '杠杆玩多大',
      humanDesc: '总资产/净资产。>3=高杠杆=高风险高回报。熊市选乘数低的。',
      dontUseWhen: '银行天然高杠杆，是商业模式决定的，不是不健康。',
      threeSecSummary: '公司用1块钱自有资金撬动了多大生意',
      emoji: '🎰', foldLevel: 'L3_full',
    },
    {
      id: 'ALTMAN_Z', nameEn: 'AltmanZScore', nameCn: 'Altman Z-score破产预测',
      humanLabel: '破产风险有多高',
      humanDesc: 'Z<1.8=破产风险区。经典模型，制造业准确率高。低于1.1赶紧跑。',
      dontUseWhen: '科技/服务公司不适用，Z-score是为制造业设计的。',
      threeSecSummary: '公司会不会倒闭 — 一个经典公式告诉你',
      emoji: '⚠️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CAPEX_INTENSITY', nameEn: 'CapexIntensity', nameCn: '资本支出强度',
      humanLabel: '赚钱要砸多少钱进去',
      humanDesc: 'CAPEX/营收高=烧钱维持。轻资产公司CAPEX低=赚得多留得住。',
      dontUseWhen: '刚起步的重资产公司CAPEX高是必要的，不是坏信号。',
      threeSecSummary: '公司每赚一块钱要投入多少钱维持',
      emoji: '🛠️', foldLevel: 'L3_full',
    },
    {
      id: 'DEBT_MATURITY', nameEn: 'DebtMaturityRisk', nameCn: '债务期限风险',
      humanLabel: '短期要还的钱多不多',
      humanDesc: '一年内到期债务占比高=再融资风险。利率上升期是定时炸弹。',
      dontUseWhen: '有强现金流/信贷额度的公司不怕短期债务到期。',
      threeSecSummary: '借钱会不会集中到期还不上',
      emoji: '⏰', foldLevel: 'L3_full',
    },
    {
      id: 'NET_MARGIN_STABILITY', nameEn: 'NetMarginStability', nameCn: '净利润率稳定性',
      humanLabel: '最近赚钱能力没变差吧',
      humanDesc: '净利率越稳定越可信。突然暴跌=竞争加剧或成本失控。',
      dontUseWhen: '一次性支出造成的净利率暴跌不是趋势性问题。',
      threeSecSummary: '公司的利润有没有大起大落',
      emoji: '📏', foldLevel: 'L2_label_desc',
    },
    {
      id: 'OPERATING_MARGIN', nameEn: 'OperatingMargin', nameCn: '营业利润率',
      humanLabel: '主营赚不赚钱',
      humanDesc: '营收中真正能留下的部分。持续上升=议价能力增强，下降=竞争在蚕食。',
      dontUseWhen: '周期性行业营业利润率波动大，不要用高点数据做判断。',
      threeSecSummary: '公司的主营业务到底能不能赚钱',
      emoji: '🎯', foldLevel: 'L2_label_desc',
    },
    {
      id: 'ROIC', nameEn: 'ReturnOnInvestedCapital', nameCn: '投资资本回报率',
      humanLabel: '投入的每一块赚多少',
      humanDesc: 'ROIC>WACC说明创造价值，>15%是优质公司。巴菲特最看重的指标。',
      dontUseWhen: 'ROIC是优势，但高ROIC的公司往往贵——要配合估值看。',
      threeSecSummary: '公司用股东和债主的钱赚到了足够的回报吗',
      emoji: '🧠', foldLevel: 'L2_label_desc',
    },
    {
      id: 'SALES_GROWTH_CONSISTENCY', nameEn: 'SalesGrowthConsistency', nameCn: '营收增长稳定性',
      humanLabel: '增长是不是每年都有',
      humanDesc: '连续5年正增长=公司找到了可复制的增长模式。忽高忽低=运气成分。',
      dontUseWhen: '成熟型公司增速低但股息高，不能一味追求增长稳定性。',
      threeSecSummary: '公司是不是每年都在变大',
      emoji: '🎢', foldLevel: 'L2_label_desc',
    },
  ],

  // ════════════════════════ 3. Analyst Sentiment ════════════════════════
  L1_ANALYST: [
    {
      id: 'ANALYST_MOMENTUM', nameEn: 'AnalystMomentum', nameCn: '分析师动量',
      humanLabel: '分析师的预测在变好吗',
      humanDesc: '分析师集体上修预测→市场还没充分反映→机会窗口。下修→快跑。',
      dontUseWhen: '出货前分析师也会集体唱多，要配合机构资金流验证。',
      threeSecSummary: '专业分析师的预测是在变好还是变坏',
      emoji: '👨‍💼', foldLevel: 'L2_label_desc',
    },
    {
      id: 'EARNINGS_REVISION', nameEn: 'EarningsRevision', nameCn: '盈利修正',
      humanLabel: '分析师在调高还是调低',
      humanDesc: '盈利预测被上调的股票短期有alpha。正向修正率>50%就是好信号。',
      dontUseWhen: '季报后修正最密集但也最容易扎堆犯错。',
      threeSecSummary: '有没有更多分析师觉得公司能赚更多',
      emoji: '✏️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'TARGET_PRICE_IMPLIED', nameEn: 'TargetPriceImplied', nameCn: '目标价隐含空间',
      humanLabel: '分析师觉得还能涨多少',
      humanDesc: '一致目标价/现价-1=潜在空间。>20%=有共识上涨空间。<5%=满仓了。',
      dontUseWhen: '目标价有滞后——股价跌了目标价不会立即调整。',
      threeSecSummary: '按分析师的目标你现在买还能赚多少',
      emoji: '🎯', foldLevel: 'L2_label_desc',
    },
    {
      id: 'ANALYST_DISPERSION', nameEn: 'AnalystDispersion', nameCn: '分析师分歧度',
      humanLabel: '专家们吵得凶不凶',
      humanDesc: '分歧小=确定性高。分歧突然变大=风险来了，可能有人先知道坏消息。',
      dontUseWhen: '新型行业天然分歧大不是坏信号，是行业本身不确定性高。',
      threeSecSummary: '分析师之间是在开会还是在吵架',
      emoji: '🤔', foldLevel: 'L3_full',
    },
    {
      id: 'RECOMMENDATION_CHANGE', nameEn: 'RecommendationChange', nameCn: '评级变化方向',
      humanLabel: '评级在升级还是降级',
      humanDesc: '近期有评级上调的股票后续有超额。连降两级的要马上关注基本面风险。',
      dontUseWhen: '评级变化反应慢（报告要写很久），已经发生的事。',
      threeSecSummary: '券商给你的股票打分高了还是低了',
      emoji: '📝', foldLevel: 'L2_label_desc',
    },
    {
      id: 'REVISION_RATIO', nameEn: 'RevisionRatio', nameCn: '上调下调比',
      humanLabel: '唱多vs唱空谁占上风',
      humanDesc: '上调次数/下调次数>2=多头占优显著。=0.5=空头主导，要小心。',
      dontUseWhen: '极度单边乐观时要警惕——所有人都看好了反而没空间了。',
      threeSecSummary: '看好的人多还是不看好的人多',
      emoji: '⚔️', foldLevel: 'L3_full',
    },
    {
      id: 'ANALYST_REVISION', nameEn: 'AnalystRevision', nameCn: '分析师盈利修正',
      humanLabel: '分析师刚刚改了什么',
      humanDesc: '最近30天内分析师修正盈利预测的方向和幅度。看修正速度看信心。',
      dontUseWhen: '单次大幅修正可能是偶发事件触发，要看连续修正方向。',
      threeSecSummary: '分析师最新的动作 — 改预测就是信号',
      emoji: '🔔', foldLevel: 'L2_label_desc',
    },
    {
      id: 'EARNINGS_ESTIMATE', nameEn: 'EarningsEstimateTrend', nameCn: '盈利预测趋势',
      humanLabel: '盈利预期总趋势往哪走',
      humanDesc: '未来12个月盈利预期的斜率。上坡=分析师在加码信任，下坡=疑虑。',
      dontUseWhen: '宏观系统性事件会让所有股票预期同时下调，不反映个股优劣。',
      threeSecSummary: '市场对这家公司赚钱能力越来越有信心还是越来越没',
      emoji: '📈', foldLevel: 'L2_label_desc',
    },
  ],

  // ════════════════════════ 4. Market Sentiment & Behavioral ════════════════════════
  L1_SENTIMENT: [
    // Fear Greed + Options
    {
      id: 'FEAR_GREED_INDEX', nameEn: 'FearGreedIndex', nameCn: '恐惧贪婪指数',
      humanLabel: '市场在恐慌还是狂欢',
      humanDesc: '<25=极度恐惧是买点，>75=极度贪婪是卖点。巴菲特：别人恐惧我贪婪。',
      dontUseWhen: '极端值可以持续很久，不要精准抄底——分步进场。',
      threeSecSummary: '全市场情绪计 — 别人怕的时候你该买',
      emoji: '😱', foldLevel: 'L2_label_desc',
    },
    {
      id: 'PUT_CALL_SKEW', nameEn: 'PutCallSkew', nameCn: '期权偏度',
      humanLabel: '大户在偷偷买保险吗',
      humanDesc: 'Put比Call贵=聪明钱在买保险防暴跌。偏度极端时市场即将反转。',
      dontUseWhen: '偏度是辅助信号，不能单独做交易决策。',
      threeSecSummary: '知道内幕的人在买Put护着吗',
      emoji: '📐', foldLevel: 'L3_full',
    },
    {
      id: 'HIGH_LOW_RATIO', nameEn: 'HighLowRatio', nameCn: '新高新低比',
      humanLabel: '创新高的多还是新低的多',
      humanDesc: '新高股票数>新低股票数=市场健康，反之=危险。>2.5:1=强势。',
      dontUseWhen: '指数上涨但新高数在降=虚涨，要提高警惕。',
      threeSecSummary: '市场是普涨还是少数撑着',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'ADVANCE_DECLINE', nameEn: 'AdvanceDecline', nameCn: '涨跌比',
      humanLabel: '涨的多还是跌的多',
      humanDesc: '涨跌股票数比值。>3:1=普涨行情，<1:3=普跌。看广度看健康度。',
      dontUseWhen: '市值大的股票不涨指数涨，涨跌比会欺骗你——看加权和等权两种。',
      threeSecSummary: '今天涨的股票多还是跌的多',
      emoji: '⬆️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'OPTION_PCR', nameEn: 'OptionPCR', nameCn: 'Put/Call比率',
      humanLabel: '做空的人多于做多的吗',
      humanDesc: 'PCR>1=恐惧过度可能反弹，<0.5=过于乐观可能回调。反向指标。',
      dontUseWhen: '重大事件前PCR会飙升但不代表方向——只是对冲需求。',
      threeSecSummary: '市场上押跌的人多还是押涨的人多',
      emoji: '📉', foldLevel: 'L2_label_desc',
    },
    {
      id: 'SOCIAL_SENTIMENT', nameEn: 'SocialSentiment', nameCn: '社交情绪',
      humanLabel: '网上的人都在聊什么',
      humanDesc: '社交媒体的情绪可以领先股价24-48小时。突然沉默比讨论更有信号。',
      dontUseWhen: '机器人水军刷出来的情绪是噪音，看讨论质量不看量。',
      threeSecSummary: '散户们在小红书和微博上是兴奋还是沉默',
      emoji: '💬', foldLevel: 'L2_label_desc',
    },
    {
      id: 'MEDIA_ATTENTION', nameEn: 'MediaAttention', nameCn: '媒体关注度',
      humanLabel: '新闻在猛吹还是冷处理',
      humanDesc: '媒体关注度突然飙升=短期见顶概率大。冷清时布局比热闹时追。',
      dontUseWhen: '正面新闻可能是付费发的，结合新闻来源可信度判断。',
      threeSecSummary: '财经媒体在反复报道还是没人提',
      emoji: '📰', foldLevel: 'L2_label_desc',
    },
    {
      id: 'INSIDER_TRADING', nameEn: 'InsiderTrading', nameCn: '内部交易信号',
      humanLabel: '老板自己买还是卖',
      humanDesc: '多个高管同时买入>信心最强信号。高管密集卖出=快跑。最准的内部消息。',
      dontUseWhen: '高管卖股理由很多（买房交税），但密集卖是要警惕的。',
      threeSecSummary: '知道最多内幕的人 — 老板们 — 在买还是卖',
      emoji: '🕵️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'SHORT_COVERING', nameEn: 'ShortCovering', nameCn: '逼空压力',
      humanLabel: '空头被逼到墙角了吗',
      humanDesc: '做空比例>20%+股价不跌=逼空蓄力中。爆发时能1天涨30-100%。',
      dontUseWhen: '逼空只是反弹不是反转，空头败退后股价会回落——见好就收。',
      threeSecSummary: '做空的人快扛不住了 — 火箭发射倒计时',
      emoji: '🍿', foldLevel: 'L2_label_desc',
    },
    {
      id: 'NEWS_SENTIMENT', nameEn: 'NewsSentiment', nameCn: '新闻情绪',
      humanLabel: '最近新闻是好事多坏事多',
      humanDesc: '新闻情绪正面偏多=短期有动量。负面突增但股价不跌=利空出尽。',
      dontUseWhen: '流量媒体有标题党倾向，情绪得分可能被极端化。',
      threeSecSummary: '最近关于这家公司的新闻是夸的多还是骂的多',
      emoji: '📡', foldLevel: 'L2_label_desc',
    },
    {
      id: 'INSTITUTIONAL_FLOW', nameEn: 'InstitutionalFlow', nameCn: '机构资金流',
      humanLabel: '大机构在进还是出',
      humanDesc: '机构净买入的股票有3-15天延续性。连续流入=主力建仓，值得跟。',
      dontUseWhen: '机构也有被迫卖的时候（赎回压力），流出不一定是看空。',
      threeSecSummary: '管几百亿的人在偷偷买什么',
      emoji: '🐋', foldLevel: 'L2_label_desc',
    },
    {
      id: 'INSIDER_BUYING', nameEn: 'InsiderBuying', nameCn: '内部人买入信号',
      humanLabel: '高管自己掏钱在买吗',
      humanDesc: '高管用自有资金买入（非期权行权）是最强的价值信号。买得越多越可信。',
      dontUseWhen: '看「真的在花钱买」和「免费拿的期权」的区别——后者无信号价值。',
      threeSecSummary: 'CEO能不能自己垫钱来支持他的信心',
      emoji: '💪', foldLevel: 'L2_label_desc',
    },
    {
      id: 'FUND_FLOW', nameEn: 'FundFlow', nameCn: '资金净流入',
      humanLabel: '聪明钱天天在买什么',
      humanDesc: '资金持续的净流入方向就是主力方向。三日累计流入最可信。',
      dontUseWhen: '单日大额净流入可能是对倒（左手倒右手），看至少三日。',
      threeSecSummary: '大资金每天都在往哪个方向砸',
      emoji: '🌊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'ETF_FLOW', nameEn: 'ETFFlow', nameCn: 'ETF资金流',
      humanLabel: 'ETF资金在进还是跑',
      humanDesc: 'ETF大额净申购=被动资金进场，大额净赎回=资金撤退预警。',
      dontUseWhen: 'ETF资金流不区分择时和配置，长线配置资金流入不代表短期看涨。',
      threeSecSummary: '指数基金的钱在进还是出',
      emoji: '🧺', foldLevel: 'L2_label_desc',
    },
    {
      id: 'IV_RANK', nameEn: 'IVRank', nameCn: '隐含波动率排名',
      humanLabel: '期权隐含的波动率多高',
      humanDesc: 'IV Rank>70=期权贵，卖权有利。<30=期权便宜，买权有利。',
      dontUseWhen: 'IV高可能是因为要有大事发生，不是必然回归。',
      threeSecSummary: '现在买期权贵不贵 — 同样的波动率在历史排第几',
      emoji: '🎰', foldLevel: 'L2_label_desc',
    },
    {
      id: 'DISPOSITION_EFFECT', nameEn: 'DispositionEffect', nameCn: '处置效应',
      humanLabel: '散户在拿着亏的不肯割吗',
      humanDesc: '散户不割的跌股票可能还要跌。处置效应高=套牢盘多=反弹难。',
      dontUseWhen: '这个因子是从行为推导不是从数据直接观测，置信度较低。',
      threeSecSummary: '套住的人太多 — 涨回去先要让他们肯卖',
      emoji: '🤲', foldLevel: 'L3_full',
    },
    {
      id: 'ANCHORING', nameEn: 'Anchoring', nameCn: '锚定效应',
      humanLabel: '大家还在惦记历史高点吗',
      humanDesc: '股价远离历史高点时散户锚定心理会错过买入机会——你正处在锚中。',
      dontUseWhen: '基本面变了的话锚定值没参考意义：跌了50%还能再跌50%。',
      threeSecSummary: '人们还念念不忘它曾经有多贵',
      emoji: '⚓', foldLevel: 'L3_full',
    },
    {
      id: 'APP_DOWNLOADS', nameEn: 'AppDownloads', nameCn: 'App下载量变化',
      humanLabel: 'App下载量增速在变快吗',
      humanDesc: '产品/服务App下载量增速领先营收1-2季度，是最早的增长信号。',
      dontUseWhen: '没有对应App的公司不能用，新增下载不代表付费转化。',
      threeSecSummary: '手机App的热度在上升还是下降',
      emoji: '📱', foldLevel: 'L3_full',
    },
    {
      id: 'GAMMA_EXPOSURE', nameEn: 'GammaExposure', nameCn: 'Gamma暴露',
      humanLabel: '做市商在买还是卖',
      humanDesc: '做市商正Gamma=市场稳定，负Gamma=市场加速——无论涨跌都更猛。',
      dontUseWhen: '零Gamma日（结算日）会有异常波动，不能当长期参考。',
      threeSecSummary: '期权做市商是在稳住市场还是火上加油',
      emoji: '🧲', foldLevel: 'L3_full',
    },
    {
      id: 'IMPLIED_CORRELATION', nameEn: 'ImpliedCorrelation', nameCn: '隐含相关性',
      humanLabel: '市场在齐涨齐跌还是各自走',
      humanDesc: 'IMCR高=所有股票一起涨跌=系统性风险高。低=分散投资有意义。',
      dontUseWhen: '恐慌时IMCR会飙升，是暂时的不是长期的。',
      threeSecSummary: '现在选股有意义吗：股票是在各自走还是一锅粥',
      emoji: '🔗', foldLevel: 'L3_full',
    },
    {
      id: 'IV_TERM_STRUCT', nameEn: 'IVTermStructure', nameCn: 'IV期限结构',
      humanLabel: '期权短期贵还是长期贵',
      humanDesc: '近月IV>远月IV=倒挂=短期有大事。正常=远高近低，倒挂=有大事。',
      dontUseWhen: '结算周MV IV会异常偏高，不是真正的倒挂信号。',
      threeSecSummary: '期权市场认为最近有事还是慢慢的',
      emoji: '📅', foldLevel: 'L3_full',
    },
    {
      id: 'JOB_POSTINGS', nameEn: 'JobPostings', nameCn: '招聘活跃度',
      humanLabel: '公司在疯狂招人还是停招',
      humanDesc: '招聘量递增=扩张信号、领先营收。突然停止招聘=裁员前兆。',
      dontUseWhen: '季节性波动（校招季/年末冻结）不是趋势变化。',
      threeSecSummary: '公司门口排队面试的人多了还是没人来',
      emoji: '👔', foldLevel: 'L3_full',
    },
    {
      id: 'OPTION_FLOW', nameEn: 'OptionFlow', nameCn: '期权资金流',
      humanLabel: '大单期权在买涨还是买跌',
      humanDesc: '异常大单期权开了什么方向=聪明钱投票。非对冲的裸买是定价信号。',
      dontUseWhen: '大单可能是对冲而不是方向性，看单子还要看持仓结构。',
      threeSecSummary: '有人花大钱在赌涨还是赌跌',
      emoji: '🎲', foldLevel: 'L2_label_desc',
    },
    {
      id: 'OPTION_SKEW', nameEn: 'OptionSkew', nameCn: '期权偏斜(25Delta)',
      humanLabel: 'OTM Put 比 ATM 贵吗',
      humanDesc: '25Delta Skew高=有人在买尾端保护。极端偏斜预示市场走向的押注。',
      dontUseWhen: '偏斜可以维持在高位几周——需要耐心等释放。',
      threeSecSummary: '期权的定价曲线在告诉你什么秘密',
      emoji: '📐', foldLevel: 'L3_full',
    },
    {
      id: 'PINCH_RISK', nameEn: 'PinchRisk', nameCn: '期权逼仓风险',
      humanLabel: '期权到期会不会出事',
      humanDesc: '大量期权集中在某个行权价附近=到期日有磁吸效应。可以做Gamma Scalp。',
      dontUseWhen: '到期的磁吸效应只在结算日附近有效，不要当成长期趋势。',
      threeSecSummary: '快要到期的期权会不会把股价吸过来',
      emoji: '🧲', foldLevel: 'L3_full',
    },
    {
      id: 'SHORT_CROWDING', nameEn: 'ShortCrowding', nameCn: '空头拥挤',
      humanLabel: '做空的人太多了小心反弹',
      humanDesc: '做空比例高+交易量增加=空头在自相踩踏的风险。可以做多逼空。',
      dontUseWhen: '有基本面问题（欺诈/破产）的公司做空多不是机会。',
      threeSecSummary: '大家都在做空 — 问题是他们是聪明还是跟风',
      emoji: '🐑', foldLevel: 'L2_label_desc',
    },
    {
      id: 'SHORT_SQUEEZE', nameEn: 'ShortSqueezeRisk', nameCn: '逼空风险信号',
      humanLabel: '空头就要被炸了',
      humanDesc: '高做空比例+不利消息出尽+资金开始流入=逼空条件就绪。潜在暴涨。',
      dontUseWhen: '逼空后股价会跌回来——见好就收，不要追涨。',
      threeSecSummary: '空头要被打爆了吗 — 炸空的核弹已经就位',
      emoji: '💥', foldLevel: 'L2_label_desc',
    },
    {
      id: 'SUPPLY_CHAIN', nameEn: 'SupplyChainRisk', nameCn: '供应链风险',
      humanLabel: '供应商在出问题吗',
      humanDesc: '供应链相关新闻频率上升=营收中断风险。集中在某市场=脆弱。',
      dontUseWhen: '有替代供应商的公司受供应链影响小——要看供应商集中度。',
      threeSecSummary: '公司的供应管道有没有被堵',
      emoji: '🔗', foldLevel: 'L3_full',
    },
    {
      id: 'VRP', nameEn: 'VolatilityRiskPremium', nameCn: '波动率风险溢价',
      humanLabel: '期权价格里的恐慌溢价',
      humanDesc: '隐含波动率减实现波动率=恐慌程度。IV>RV时卖权有利可图。',
      dontUseWhen: '发生危机时IV>RV是合理反应，不是一定会回归的。',
      threeSecSummary: '市场对未来波动的恐惧比实际多了多少',
      emoji: '🫧', foldLevel: 'L3_full',
    },
    {
      id: 'ETF_FLOW_ADVANCED', nameEn: 'ETFFlowAdvanced', nameCn: 'ETF资金流(进阶)',
      humanLabel: 'ETF资金按行业分',
      humanDesc: '拆解到行业ETF净流入=资金在往哪个赛道走。领先股价1-2周。',
      dontUseWhen: 'ETF资金流有滞后——看到的时候可能已经在跑了。',
      threeSecSummary: '哪些行业的ETF在被人买爆',
      emoji: '💰', foldLevel: 'L2_label_desc',
    },
    {
      id: 'PUT_CALL_RATIO', nameEn: 'PutCallRatio', nameCn: 'Put/Call比率',
      humanLabel: '做空的比做多的多吗',
      humanDesc: '个股PCR突然飙升>1.5可能是一个恐慌底。<0.4可能是乐观顶。',
      dontUseWhen: '做空保护性Put不代表看空，要看裸Put和大单Call为主。',
      threeSecSummary: '赌跌的筹码：赌涨的筹码 — 此刻谁多',
      emoji: '⚖️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'SHORT_INTEREST', nameEn: 'ShortInterest', nameCn: '空头持仓比例',
      humanLabel: '多少人赌它会跌',
      humanDesc: '>20%做空比例=高争议股。>30%+股价不跌=逼空能量在积累。',
      dontUseWhen: '做空高但盈利好的股票可能是价值错杀，要具体分析。',
      threeSecSummary: '市场上有多少人不看好这只股票',
      emoji: '📉', foldLevel: 'L2_label_desc',
    },
  ],

  // ════════════════════════ 5. Technical Indicators ════════════════════════
  L1_TECHNICAL: [
    {
      id: 'MA_20_60', nameEn: 'MA2060', nameCn: '均线交叉',
      humanLabel: '金叉买死叉卖',
      humanDesc: '20日均线上穿60日=趋势转强，买入；下穿=趋势转弱，卖出。',
      dontUseWhen: '震荡市中频繁金叉死叉=频繁止损坑，别信。',
      threeSecSummary: '短线均线和长线均线的方向决定买卖',
      emoji: '📈', foldLevel: 'L2_label_desc',
    },
    {
      id: 'EMA_12_26', nameEn: 'EMA1226', nameCn: 'MACD',
      humanLabel: 'MACD金叉死叉',
      humanDesc: 'DIF线上穿DEA=买入；下穿=卖出。最经典的趋势跟踪指标。',
      dontUseWhen: '盘整时MACD反复金叉死叉，会频繁假信号。结合趋势方向用。',
      threeSecSummary: '快线和慢线的距离告诉你趋势强不强',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'RSI_14', nameEn: 'RSI14', nameCn: '相对强弱',
      humanLabel: '现在是超买还是超卖',
      humanDesc: 'RSI<30=超卖可能反弹，>70=超买可能回调。趋势市会长期超买/超卖。',
      dontUseWhen: '强势上涨中RSI可以持续>70好几周，别一见超买就卖。',
      threeSecSummary: '涨得过猛还是跌得过头了',
      emoji: '📉', foldLevel: 'L2_label_desc',
    },
    {
      id: 'KDJ', nameEn: 'KDJ', nameCn: 'KDJ随机',
      humanLabel: '短线多空转换灵敏指标',
      humanDesc: 'K线从下穿D线=卖，上穿=买。适合短线波段。J>100=极度超买。',
      dontUseWhen: '单边市中KDJ极值会成为常态，反着做会亏死。',
      threeSecSummary: '比RSI更灵敏的短线指标',
      emoji: '⚡', foldLevel: 'L2_label_desc',
    },
    {
      id: 'BOLL', nameEn: 'Bollinger', nameCn: '布林带',
      humanLabel: '股价在通道里乱晃',
      humanDesc: '触及下轨且带宽收窄后反弹概率高。上轨附近卖，下轨附近买，中轨是支撑。',
      dontUseWhen: '布林带是概率区间不是固定边界——强势突破后带子会扩张。',
      threeSecSummary: '股价被自然的力量弹回来——布林带收窄就快变盘了',
      emoji: '📐', foldLevel: 'L2_label_desc',
    },
    {
      id: 'ATR_14', nameEn: 'ATR14', nameCn: '真实波幅',
      humanLabel: '每天波动有多大',
      humanDesc: '用ATR算止损位置：跌过2倍ATR就走。不看百分比——看实际波幅。',
      dontUseWhen: '突发消息后ATR会飙升，浮亏可能远超ATR预设的止损。',
      threeSecSummary: '这只股票每天跳动的幅度是多少',
      emoji: '📏', foldLevel: 'L3_full',
    },
    {
      id: 'ADX', nameEn: 'ADX', nameCn: '趋向指标',
      humanLabel: '趋势强不强不看方向',
      humanDesc: 'ADX>25=有趋势（不管涨跌），>40=超强趋势。低ADX=别用趋势策略。',
      dontUseWhen: 'ADX只告诉你趋势强度不告诉你方向——还要看DMI+/-或价格。',
      threeSecSummary: '现在的行情是有方向还是方向不明',
      emoji: '🧭', foldLevel: 'L2_label_desc',
    },
    {
      id: 'OBV', nameEn: 'OBV', nameCn: '能量潮',
      humanLabel: '量和价同不同步',
      humanDesc: '价涨量涨OBV升=真实上涨。价涨量缩OBV平=虚涨，可能回调。',
      dontUseWhen: '单日OBV波动意义不大，看的是趋势不是单点。',
      threeSecSummary: '成交量和价格是不是同一方向',
      emoji: '🌊', foldLevel: 'L3_full',
    },
    {
      id: 'CMF', nameEn: 'CMF', nameCn: '资金流量',
      humanLabel: '聪明钱真的在买吗',
      humanDesc: 'CMF>0=资金在流入，<0=在流出。连续>5天的方向可信度高。',
      dontUseWhen: '跳空缺口时CMF会失真——收盘离开盘太远。',
      threeSecSummary: '量价关系告诉你：大资金实在买入还是只是在兜售',
      emoji: '💧', foldLevel: 'L2_label_desc',
    },
    {
      id: 'ICHIMOKU', nameEn: 'Ichimoku', nameCn: '一目均衡',
      humanLabel: '一眼看全趋势支撑阻力',
      humanDesc: 'K线在云上=多头，云下=空头。云变厚变薄=支撑阻力在变。',
      dontUseWhen: '云的颜色反转有滞后——穿越已经发生了的信号不是预测。',
      threeSecSummary: '五条线一块看 — 一个指标顶五个',
      emoji: '☁️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'VWAP', nameEn: 'VWAP', nameCn: '成交量加权均价',
      humanLabel: '机构平均进货价是多少',
      humanDesc: '价格在VWAP之上=机构浮盈，之下=机构被套。是当日的关键支撑/阻力。',
      dontUseWhen: 'VWAP只对当日有意义，隔日要重新看。短期交易用。',
      threeSecSummary: '今天所有人都在这条线上成交',
      emoji: '🎯', foldLevel: 'L2_label_desc',
    },
  ],

  // ════════════════════════ 6. Risk & Tail ════════════════════════
  L1_RISK: [
    {
      id: 'VOL_60D', nameEn: 'Volatility60D', nameCn: '60日波动率',
      humanLabel: '最近俩月有多刺激',
      humanDesc: '60日波动率>40%=高波动股。喜欢刺激的选它，要安稳的避开它。',
      dontUseWhen: '波动率只讲过去不讲未来——平静期后会突然爆发。',
      threeSecSummary: '这只股票坐过山车的激烈程度',
      emoji: '🎢', foldLevel: 'L2_label_desc',
    },
    {
      id: 'LIQ', nameEn: 'Liquidity', nameCn: '流动性',
      humanLabel: '卖的时候买得到接盘吗',
      humanDesc: '日均成交额>1亿=流动性好。小盘股要关注买卖价差和滑点。',
      dontUseWhen: '流动性好不代表不会跌——该跌照样跌，只是有人接盘。',
      threeSecSummary: '你想卖的时候有没有人愿意买',
      emoji: '💧', foldLevel: 'L2_label_desc',
    },
    {
      id: 'MAX_DRAWDOWN', nameEn: 'MaxDrawdown', nameCn: '最大回撤',
      humanLabel: '从顶到底最惨跌过多少',
      humanDesc: '历史最大回撤就是你未来可能要承受的最大痛苦。选能睡得着的。',
      dontUseWhen: '过去最大回撤不一定等于未来最大回撤——黑天鹅能轻易打破纪录。',
      threeSecSummary: '这只股票历史上跌得最狠的时候跌了多少',
      emoji: '📉', foldLevel: 'L2_label_desc',
    },
    {
      id: 'VAR_95', nameEn: 'VaR95', nameCn: '95%风险价值',
      humanLabel: '每天最多亏多少',
      humanDesc: '有95%的把握日内亏损不超过VaR。5%的情况可能更糟——要有准备。',
      dontUseWhen: 'VaR假设正态分布——市场暴跌的时候5%就是100%，模型全废。',
      threeSecSummary: '你每天能亏多少 — 95%的置信度',
      emoji: '🎲', foldLevel: 'L3_full',
    },
    {
      id: 'CVAR_95', nameEn: 'CVaR95', nameCn: '条件风险价值',
      humanLabel: '真出事的话会亏多少',
      humanDesc: '落在尾部5%时的平均亏损——比VaR更真实，告诉你最坏情况。',
      dontUseWhen: 'CVaR从历史算出来，利率突变或战争等事件没法在历史里找到。',
      threeSecSummary: '如果真遇到倒霉的日子你会亏多少',
      emoji: '⚠️', foldLevel: 'L3_full',
    },
    {
      id: 'DOWNSIDE_DEVIATION', nameEn: 'DownsideDeviation', nameCn: '下行偏差',
      humanLabel: '亏的时候跌得有多狠',
      humanDesc: '只看亏损日的波动——上行波动不算。比标准差更贴近你的真实痛苦。',
      dontUseWhen: '只能描述历史下行——无法预测未来下行有多大。',
      threeSecSummary: '当它跌的时候跌的有多深',
      emoji: '📉', foldLevel: 'L2_label_desc',
    },
    {
      id: 'SORTINO_RATIO', nameEn: 'SortinoRatio', nameCn: '索提诺比率',
      humanLabel: '冒险值得吗（只看亏损风险）',
      humanDesc: 'Sortino>2=好风险调整回报。>3=优秀。只看下行风险，上行不算风险。',
      dontUseWhen: '短期Sortino可以用超高单边涨幅得出虚高的数字。',
      threeSecSummary: '每多承受一分亏损风险，你多赚了多少',
      emoji: '🛡️', foldLevel: 'L3_full',
    },
    {
      id: 'OMEGA_RATIO', nameEn: 'OmegaRatio', nameCn: 'Omega比率',
      humanLabel: '赚的够不够覆盖亏的',
      humanDesc: 'Omega>2意味着盈利区间是亏损区间的2倍大。比夏普更完整。',
      dontUseWhen: '阈值选择会影响结果——不同阈值会得出不同结论。',
      threeSecSummary: '赚钱的分布和亏钱的分布哪个更大',
      emoji: '📊', foldLevel: 'L3_full',
    },
    {
      id: 'TAIL_DEPENDENCE', nameEn: 'TailDependence', nameCn: '尾部相关',
      humanLabel: '大盘跌的时候一起跌吗',
      humanDesc: '尾部相关高=大盘暴跌时你也跟着暴跌——没有躲的地方。',
      dontUseWhen: '只在大熊市时真正测得出，平时看不出这个风险。',
      threeSecSummary: '系统性大跌的时候你跑得掉吗',
      emoji: '🔗', foldLevel: 'L3_full',
    },
    {
      id: 'CROWDING', nameEn: 'Crowding', nameCn: '拥挤度',
      humanLabel: '太多人追着买了小心踩踏',
      humanDesc: '拥挤度>80%=这个因子被用烂了，未来收益会被套利。>90%=快跑。',
      dontUseWhen: '新因子天生拥挤度低，老因子高——这不代表新因子就更好。',
      threeSecSummary: '用这个策略的人多到互相踩踏了吗',
      emoji: '🐑', foldLevel: 'L2_label_desc',
    },
    {
      id: 'MOM_CRASH', nameEn: 'MomentumCrash', nameCn: '动量崩盘预警',
      humanLabel: '追涨策略要被炸了',
      humanDesc: '当动量因子大幅亏损时=动量崩盘进行中。历史平均跌-15%后反弹。',
      dontUseWhen: '崩盘警报不是交易信号——是告诉你要跑了。',
      threeSecSummary: '追涨的高空绳子要断了',
      emoji: '💥', foldLevel: 'L3_full',
    },
    {
      id: 'BETA_STABILITY', nameEn: 'BetaStability', nameCn: 'Beta稳定性',
      humanLabel: 'Beta忽高忽低不靠谱',
      humanDesc: 'Beta变化大=公司特性在变。Beta稳定=策略可以放心用它对冲。',
      dontUseWhen: '新上市公司Beta不稳定是正常的——看至少1年。',
      threeSecSummary: '这只股票的涨跌跟大盘的关系稳定吗',
      emoji: '📊', foldLevel: 'L3_full',
    },
    {
      id: 'SKEWNESS', nameEn: 'Skewness', nameCn: '偏度',
      humanLabel: '赚小赔大还是赚大赔小',
      humanDesc: '正偏度=偶有大赚、经常小亏。负偏度=偶有大亏、经常小赚——小心。',
      dontUseWhen: '偏度需要很长时间的数据才可靠——3个月数据没法确定。',
      threeSecSummary: '赚钱的时候是大赚还是小赚',
      emoji: '🎯', foldLevel: 'L3_full',
    },
    {
      id: 'KURTOSIS', nameEn: 'Kurtosis', nameCn: '峰度',
      humanLabel: '极端收益发生的频率',
      humanDesc: '峰度高=暴涨暴跌次数比正态分布多。要么赚翻要么亏惨。',
      dontUseWhen: '短期数据的小概率事件没体现在峰度里——可能突然暴。',
      threeSecSummary: '这只股票是不是经常走极端',
      emoji: '🌪️', foldLevel: 'L3_full',
    },
    {
      id: 'ALPHA_DECAY', nameEn: 'AlphaDecay', nameCn: 'Alpha衰减监测',
      humanLabel: '你的策略正慢慢不灵了吗',
      humanDesc: 'Alpha半衰期越短越危险。如果衰减加速，这个因子快完蛋了。',
      dontUseWhen: '短期的Alpha衰减可能只是无Alph周期——不是因子真的死了。',
      threeSecSummary: '这个策略的秘密是不是越来越多人知道了',
      emoji: '⏳', foldLevel: 'L3_full',
    },
    {
      id: 'DOWNSIDE_VOL', nameEn: 'DownsideVolatility', nameCn: '下行波动率',
      humanLabel: '亏的时候走得有多颠',
      humanDesc: '只看亏损日的波动幅度。比整体波动率更精确地反映你的心理痛苦。',
      dontUseWhen: '下行波动率只能描述过去——没有预测能力。',
      threeSecSummary: '等你亏钱的时候会跌得多凶',
      emoji: '📉', foldLevel: 'L2_label_desc',
    },
    {
      id: 'IDIO_VOL', nameEn: 'IdiosyncraticVolatility', nameCn: '特质波动率',
      humanLabel: '剔除大盘的个股波动',
      humanDesc: '公司自身特色的波动——不被大盘解释的部分。低特质波动有溢价。',
      dontUseWhen: '高特质波动=不确定性，但可能有高成长——不要一概而论排除。',
      threeSecSummary: '除掉大盘因素后的纯粹个股波动',
      emoji: '🎯', foldLevel: 'L3_full',
    },
    {
      id: 'BAB', nameEn: 'BettingAgainstBeta', nameCn: '低Beta溢价(BAB)',
      humanLabel: '低风险高回报之谜',
      humanDesc: '低Beta股票长期居然跑赢高Beta——因为资金被迫不能加杠杆。反直觉。',
      dontUseWhen: '在牛市中BAB因子会跑输大盘——要有耐心。',
      threeSecSummary: '风险小的股票反而赚得多 — 金融学大谜题',
      emoji: '🧩', foldLevel: 'L2_label_desc',
    },
    {
      id: 'FACTOR_CROWDING', nameEn: 'FactorCrowding', nameCn: '因子拥挤度',
      humanLabel: '这个因子还有没有油水',
      humanDesc: '因子被大量资金使用=α被摊薄。拥挤度>80%=信号对你不利。',
      dontUseWhen: '拥挤不代表马上不赚钱——只是赚钱效率在下降。',
      threeSecSummary: '跟你用同样策略的人太多了',
      emoji: '🐠', foldLevel: 'L2_label_desc',
    },
    {
      id: 'TAIL_RISK', nameEn: 'TailRisk', nameCn: '尾部风险(VaR)',
      humanLabel: '最坏情况的极端风险',
      humanDesc: '综合评估极端跌损失。用多种分布模型（不只用正态）看尾端。',
      dontUseWhen: '模型都是基于历史——真正的黑天鹅你永远算不出。',
      threeSecSummary: '如果发生最坏的事 — 你扛得住吗',
      emoji: '🆘', foldLevel: 'L2_label_desc',
    },
  ],

  // ════════════════════════ 7. Macro Sensitivity ════════════════════════
  L1_MACRO: [
    {
      id: 'SECTOR_ROTATION', nameEn: 'SectorRotation', nameCn: '板块轮动',
      humanLabel: '钱在行业之间转来转去',
      humanDesc: '资金先金融→成长→价值→防御，按这个节奏提前布局比追涨强。',
      dontUseWhen: '经济周期变了旧的轮动模型就废了——现在是新规则时代。',
      threeSecSummary: '大资金在偷偷往哪个行业流',
      emoji: '🔄', foldLevel: 'L2_label_desc',
    },
    {
      id: 'FX_EXPOSURE', nameEn: 'FXExposure', nameCn: '外汇敞口',
      humanLabel: '汇率波动吃掉你多少回报',
      humanDesc: 'A股港美股都有汇率风险——人民币涨你持有的美元资产就缩水了。',
      dontUseWhen: '对冲也有成本——小投资者不需要完全对冲汇率风险。',
      threeSecSummary: '人民币升值还是贬值会影响你多少',
      emoji: '💱', foldLevel: 'L2_label_desc',
    },
    {
      id: 'RATE_BETA', nameEn: 'RateBeta', nameCn: '利率敏感度',
      humanLabel: '利率一涨你就亏了吗',
      humanDesc: '利率敏感度越高，央行加息时这只股票跌越多。地产/公用事业最敏感。',
      dontUseWhen: '利率预期已经被定价——真正加息时市场在交易降息的预期。',
      threeSecSummary: '央行一动你的股票跟着抖多厉害',
      emoji: '🏦', foldLevel: 'L2_label_desc',
    },
    {
      id: 'INFLATION_BETA', nameEn: 'InflationBeta', nameCn: '通胀敏感度',
      humanLabel: '物价涨对你有利还是有弊',
      humanDesc: '通胀敏感度高=通胀利好。商品/材料行业受益，消费/科技受损。',
      dontUseWhen: '通胀高但见顶时这个指标就反了——跟着通胀数据滞后。',
      threeSecSummary: '通胀来了你的股票是涨是跌',
      emoji: '🔥', foldLevel: 'L2_label_desc',
    },
    {
      id: 'USD_BETA', nameEn: 'USDBeta', nameCn: '美元敏感度',
      humanLabel: '美元强对你是福是祸',
      humanDesc: '美元指数涨新兴市场资金流出。持有港美股中国资产时关注这个。',
      dontUseWhen: '去美元化趋势下美元影响力在长期下降。',
      threeSecSummary: '美元走强的时候你的资产还能不能撑住',
      emoji: '💵', foldLevel: 'L2_label_desc',
    },
    {
      id: 'OIL_BETA', nameEn: 'OilBeta', nameCn: '原油敏感度',
      humanLabel: '油价涨了对你怎样',
      humanDesc: '航空股=负敏感（油价涨=亏），能源股=正敏感。看你的暴露。',
      dontUseWhen: '地缘政治会让油价和行业关系短暂脱钩——别在那时重平衡。',
      threeSecSummary: '原油市场一动你的股票往哪走',
      emoji: '🛢️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CREDIT_SPREAD_BETA', nameEn: 'CreditSpreadBeta', nameCn: '信用利差敏感度',
      humanLabel: '信贷市场紧张时你紧张吗',
      humanDesc: '信用利差放宽=信贷紧缩→高利差敏感股被杀。金融板块最爱受害。',
      dontUseWhen: '信用利差不是日内指标——看周级别的趋势更有意义。',
      threeSecSummary: '银行不敢借钱的时候这只股票跌多少',
      emoji: '🏗️', foldLevel: 'L3_full',
    },
    {
      id: 'ECONOMIC_SURPRISE', nameEn: 'EconomicSurprise', nameCn: '经济意外指数',
      humanLabel: '经济数据比预期好还是差',
      humanDesc: '数据持续超预期=经济动能好，股票涨。持续不如预期=衰退前兆。',
      dontUseWhen: '数据太好的话央行可能更紧——不是所有「好」都好。',
      threeSecSummary: '最近的经济数据是惊喜多还是惊吓多',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'MARKET_REGIME', nameEn: 'MarketRegime', nameCn: '市场状态',
      humanLabel: '现在的市场是牛是熊是震',
      humanDesc: '判断当前是牛市/熊市/震荡市/复苏——不同体制用不同策略。',
      dontUseWhen: '体制切换有滞后——等你确认了大家也知道了。',
      threeSecSummary: '现在大环境是什么行情',
      emoji: '🎯', foldLevel: 'L2_label_desc',
    },
    {
      id: 'VOLUME_REGIME', nameEn: 'VolumeRegime', nameCn: '量能状态',
      humanLabel: '市场活跃程度有多高',
      humanDesc: '放量上涨=牛市特征，缩量下跌=熊市，放量下跌=恐慌，缩量上涨=弱反弹。',
      dontUseWhen: '节假日/季末成交量会结构性偏低——不是真正的量能萎缩。',
      threeSecSummary: '今天是真刀真枪还是小打小闹',
      emoji: '🔊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'YIELD_CURVE_SLOPE', nameEn: 'YieldCurveSlope', nameCn: '收益率曲线斜率',
      humanLabel: '债的长期利率vs短期利率',
      humanDesc: '曲线倒挂（短>长）=衰退预测。历史上每次倒挂后6-18月都衰退。',
      dontUseWhen: '倒挂是领先指标——倒了12个月都不一定衰退，但早晚要来。',
      threeSecSummary: '债券市场在预示经济是热还是冷',
      emoji: '📈', foldLevel: 'L2_label_desc',
    },
    {
      id: 'REAL_RATE', nameEn: 'RealRate', nameCn: '实际利率',
      humanLabel: '扣除通胀后的真实利率',
      humanDesc: '实际利率下降=黄金+成长股利好。实际利率升=价值股+现金为王。',
      dontUseWhen: '实际利率是一个百分比——关注方向比关注绝对数字更重要。',
      threeSecSummary: '你的钱真实能赚多少',
      emoji: '💎', foldLevel: 'L3_full',
    },
    {
      id: 'PMI_INDEX', nameEn: 'PMIIndex', nameCn: 'PMI指数',
      humanLabel: '工厂订单是在扩张还是收缩',
      humanDesc: 'PMI>50=制造业扩张，股市利好。PMI转弱领先GDP下滑3-6个月。',
      dontUseWhen: '服务业PMI和制造业PMI方向可能相反——当前看服务业更准。',
      threeSecSummary: '工厂里的订单是越来越多还是越来越少',
      emoji: '🏭', foldLevel: 'L2_label_desc',
    },
    {
      id: 'VOLATILITY_REGIME', nameEn: 'VolatilityRegime', nameCn: '波动率体制',
      humanLabel: '波动率趋势在往哪走',
      humanDesc: '波动率在上升期=减仓信号。在下降期=可以加仓。趋势比绝对数重要。',
      dontUseWhen: '波动率短期的跳跃不代表体制改变——看3天以上的持续。',
      threeSecSummary: '市场的波动在变大还是变小',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'FACTOR_LEAD_LAG', nameEn: 'FactorLeadLag', nameCn: '因子领先滞后',
      humanLabel: '哪些因子的信号最及时',
      humanDesc: '不同因子反应速度不同——宏观最领先、基本面最滞后。要排列前后。',
      dontUseWhen: '领先关系不是固定的——市场结构变了因果也会变。',
      threeSecSummary: '市场信号到达的先后顺序',
      emoji: '⏱️', foldLevel: 'L3_full',
    },
    {
      id: 'SECTOR_STRENGTH', nameEn: 'SectorStrength', nameCn: '行业强度',
      humanLabel: '各行业现在的强弱如何',
      humanDesc: '最近哪个行业跑赢大盘最多。强势行业往往还能延续1-3个月。',
      dontUseWhen: '行业轮动是缓慢的——最强行业不会一天变最差。不要太快追。',
      threeSecSummary: '哪个行业是现在最强的王者',
      emoji: '🏆', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CURRENCY_EFFECT', nameEn: 'CurrencyEffect', nameCn: '汇率影响',
      humanLabel: '汇率对你的持仓影响多大',
      humanDesc: '假设汇率不动时的回报 vs 含汇率回报。别把货币赚的当公司赚的。',
      dontUseWhen: '汇率变化本来就是回报的一部分——剥开来看是为了理解但你不一定对冲。',
      threeSecSummary: '你赚的钱里多少是公司赚的多少是汇率送的',
      emoji: '💱', foldLevel: 'L3_full',
    },
    {
      id: 'BOND_SPREAD', nameEn: 'BondCreditSpread', nameCn: '债券信用利差',
      humanLabel: '企业债成本有多高',
      humanDesc: '信用利差收窄=风险偏好上升，股市好。放宽=避险，股市要跌。',
      dontUseWhen: '利差是被央行钉住的——QE时代利差信号可能有延迟。',
      threeSecSummary: '市场借钱给企业的利率有多高',
      emoji: '📊', foldLevel: 'L3_full',
    },
    {
      id: 'GDP_BETA', nameEn: 'GDPBeta', nameCn: 'GDP敏感度',
      humanLabel: '经济增长对你有多关键',
      humanDesc: 'GDP高敏感股票=经济好时最大赢家。GDP回落=这些股票最先被甩。',
      dontUseWhen: 'GDP是滞后指标——已经发生的事。不预测未来。',
      threeSecSummary: '国家经济增长时这只股票能涨多少',
      emoji: '📈', foldLevel: 'L3_full',
    },
    {
      id: 'RATE_SENSITIVITY', nameEn: 'RateSensitivity', nameCn: '利率敏感度',
      humanLabel: '利率一动你的盈亏就变',
      humanDesc: '利率每变1%你的预期回报变多少。越高=越被利率绑架。',
      dontUseWhen: '利率敏感度假设其他不变——但利率变的时候别的也在变。',
      threeSecSummary: '央行调利率的时候你的股票幅度有多大',
      emoji: '💹', foldLevel: 'L2_label_desc',
    },
  ],

  // ════════════════════════ 8. Reversal & Seasonality ════════════════════════
  L1_REVERSAL: [
    {
      id: 'STR_5D', nameEn: 'ShortTermReversal5D', nameCn: '5日短期反转',
      humanLabel: '暴跌5天能弹回来吗',
      humanDesc: '跌得最多的5只股票下一周有反弹惯性。做反弹的超短线用。',
      dontUseWhen: '有基本面利空（业绩暴雷/欺诈）的暴跌不是反弹机会。',
      threeSecSummary: '最近跌得最惨的会不会反弹',
      emoji: '🔄', foldLevel: 'L2_label_desc',
    },
    {
      id: 'LTR_60M', nameEn: 'LongTermReversal60M', nameCn: '60月长期反转',
      humanLabel: '跌了5年还能回来吗',
      humanDesc: '过去5年跌最多的板块往往接下来5年能领跑。极需耐心和信念。',
      dontUseWhen: '行业已经结构性死亡（如煤油车时代结束），不会反转。',
      threeSecSummary: '被遗忘了5年的角落会不会重新发光',
      emoji: '💤', foldLevel: 'L2_label_desc',
    },
    {
      id: 'SEASONAL_1M', nameEn: 'Seasonal1M', nameCn: '月度效应',
      humanLabel: '这个月历史上是涨是跌',
      humanDesc: '某些月平均涨跌量有规律：9月差，11月好。给仓位调调参考。',
      dontUseWhen: '季节性只是概率论——永远不可以用这个替掉基本面分析。',
      threeSecSummary: '按历史，这个月份好不好做',
      emoji: '📅', foldLevel: 'L2_label_desc',
    },
    {
      id: 'GAP_REVERSION', nameEn: 'GapReversion', nameCn: '缺口回补',
      humanLabel: '跳空缺口真的要回补吗',
      humanDesc: '跳空缺口有回到原位的概率——但时间不确定。放量缺口回补概率更高。',
      dontUseWhen: '财报后的突破缺口（放大量+好业绩）可以永久不补。',
      threeSecSummary: '突然跳空的位置会不会再回来',
      emoji: '🕳️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'MEAN_REVERSION_SPEED', nameEn: 'MeanReversionSpeed', nameCn: '均值回归速度',
      humanLabel: '偏离中线后多久回来',
      humanDesc: '回归速度快的股票=容易回均值=适合做波段。慢的=趋势持续=适合追。',
      dontUseWhen: '打了鸡血的行情均值回归会失效很久——要有耐心。',
      threeSecSummary: '这只股票偏离正常水平后回头的速度',
      emoji: '⏪', foldLevel: 'L3_full',
    },
  ],
};

export default CORE_FACTOR_HUMANIZE;
