// ══ R282 QClaw Task 1+2 续: 因子人话化 — 剩余L1大类 ══
// 交付: src/lib/factor/factor-humanize-extended-r282.ts
// 覆盖: US/HK/Crypto/Cross-Asset/Event/ESG/Commodity + 3秒摘要生成系统

import type { FactorHumanized } from './factor-humanize-core-r282';

const EXTENDED_FACTOR_HUMANIZE: Record<string, FactorHumanized[] | { note: string; rules: string[] }> = {

  // ════════════════════════ 9. US-Specific ════════════════════════
  L1_US: [
    {
      id: 'US_VIX', nameEn: 'VIX', nameCn: '恐慌指数',
      humanLabel: '美股有多恐慌',
      humanDesc: 'VIX<15=慵牛，>25=惊慌，>35=恐慌。别人恐慌时我贪婪。',
      dontUseWhen: 'VIX是可交易工具不是纯情绪计——别有VIX本身的操纵。',
      threeSecSummary: '华尔街恐惧温度计',
      emoji: '😱', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_SHORT_RATIO', nameEn: 'ShortRatio', nameCn: '空头比率',
      humanLabel: '美股空头占比高吗',
      humanDesc: '空头比率高于行业平均=看空共识。配合价格不动可能是逼空机会。',
      dontUseWhen: '大市值股票空头比率天然低——不能只用>X%来看。',
      threeSecSummary: '美股做空的筹码有多重',
      emoji: '📉', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_INST_HOLD', nameEn: 'InstitutionalHolding', nameCn: '机构持仓',
      humanLabel: '大机构拿多少货',
      humanDesc: '机构持仓比例上升=专业资金在接力散户。下降=在出货给散户。',
      dontUseWhen: '大牛市中机构持仓下降可能只是散户追涨更快。',
      threeSecSummary: '大基金在偷偷收筹码还是悄悄出',
      emoji: '🏦', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_BUYBACK', nameEn: 'Buyback', nameCn: '回购活动',
      humanLabel: '公司在自己买自己吗',
      humanDesc: '回购>自由现金流=用借的钱回购——不是真实的价值创造。回购<FCF=真回购。',
      dontUseWhen: '回购越多不代表越好——要在股价没被高估时回购才有价值。',
      threeSecSummary: '公司用手里的现金在托自己的股价',
      emoji: '♻️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_EARN_SURPRISE', nameEn: 'USEarningsSurprise', nameCn: '财报超预期',
      humanLabel: '业绩是惊喜还是惊吓',
      humanDesc: '连续3季超预期=管理层保守指引被持续推翻=真正的优秀公司。',
      dontUseWhen: '营收超预期但利润不超=成本失控预警。',
      threeSecSummary: '实际业绩比管理层的预测好不好',
      emoji: '🎯', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_INSIDER_BUY', nameEn: 'InsiderBuy', nameCn: '内部人买入',
      humanLabel: '高管在用自己的钱买',
      humanDesc: 'CEO群买=最强价值信号。单人买=可能有信心的原因要看金额。',
      dontUseWhen: '高管赠股/期权行权不算真买入——看的是「花了现金买的」。',
      threeSecSummary: '知道最多内情的人在拿真金白银投票',
      emoji: '🕵️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_SHORT_SQUEEZE', nameEn: 'ShortSqueeze', nameCn: '逼空风险',
      humanLabel: '美股有没有被压的弹簧',
      humanDesc: '做空>30%+盘子小+浮筹少=随时可能火箭发射。高风险高回报。',
      dontUseWhen: '基本面有欺诈的公司即使被逼空也别碰——早晚归零。',
      threeSecSummary: '美股有没有GameStop那种被压的弹簧',
      emoji: '🚀', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_MEME_INDEX', nameEn: 'MemeIndex', nameCn: 'Meme股热度',
      humanLabel: '散户热度有多高',
      humanDesc: 'Meme热度飙升=短期涨速快。社交媒体沉默就是热度退了。',
      dontUseWhen: 'Meme热度是短期交易信号——不要当长期持有的理由。',
      threeSecSummary: 'Reddit/WallStreetBets的热度在往哪烧',
      emoji: '🔥', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_MARGIN_DEBT', nameEn: 'MarginDebt', nameCn: '保证金债务',
      humanLabel: '借了多少杠杆在炒股',
      humanDesc: '保证金债务创新高=散户杠杆拉满=风险上升。触顶回落后往往跌。',
      dontUseWhen: '保证金高本身不说明问题——要结合变化方向和使用率。',
      threeSecSummary: '全美国散户杠杆用到什么程度了',
      emoji: '📊', foldLevel: 'L3_full',
    },
    {
      id: 'US_RESIDUAL_MOM', nameEn: 'ResidualMomentum', nameCn: '残差动量',
      humanLabel: '剔除大盘因素的纯动量',
      humanDesc: '去掉大盘涨跌因素的纯个股动量——比简单动量更强更稳。',
      dontUseWhen: '小盘股残差动量噪音大——数据点不够稳定。',
      threeSecSummary: '这只股票超越了大盘的涨幅',
      emoji: '📈', foldLevel: 'L3_full',
    },
    {
      id: 'US_EP_RATIO', nameEn: 'USEarningsPrice', nameCn: '美股PE倒数',
      humanLabel: '美股便宜吗',
      humanDesc: 'E/P高=股票相对便宜。可和美债收益率比——高于债就是好价钱。',
      dontUseWhen: '不要只看PE不看成长——低PE但没成长的是价值陷阱。',
      threeSecSummary: '美股当前的性价比高不高',
      emoji: '💵', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_BP_RATIO', nameEn: 'USBookPrice', nameCn: '美股PB倒数',
      humanLabel: '美股净资产相对贵不贵',
      humanDesc: 'B/P高=净资产相对股价高，适合银行/保险/地产股选股。',
      dontUseWhen: '无形资产比例高的科技公司不要用PB。',
      threeSecSummary: '每块钱股价买到了多少净资产',
      emoji: '🏛️', foldLevel: 'L3_full',
    },
    {
      id: 'US_DPS_STABILITY', nameEn: 'DPSStability', nameCn: '分红稳定性',
      humanLabel: '美股分红有没有断过',
      humanDesc: '连续10+年不减分红的公司=管理层把股东利益放在第一位。',
      dontUseWhen: '不分红但大量回购的公司同样能回报股东——不能只看分红。',
      threeSecSummary: '美股公司给你的支票是不是每年都在到',
      emoji: '📬', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_EARNINGS_CALENDAR', nameEn: 'USEarningsCalendar', nameCn: '美股财报日历',
      humanLabel: '接下来谁要交成绩单',
      humanDesc: '财报早发布=底气足。推迟发布=有雷。提前知道哪天能提前布局。',
      dontUseWhen: '不是所有早报的公司都好——也可能急着出好消息掩盖坏消息。',
      threeSecSummary: '未来的财报公布时间表',
      emoji: '📅', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_SECTOR_ROTATION', nameEn: 'USSectorRotation', nameCn: '美股板块轮动',
      humanLabel: '美股资金在行业间搬家',
      humanDesc: '看SPDR行业ETF相对强弱。资金先科技→金融→防御=一个完整周期。',
      dontUseWhen: '现代经济下传统轮动模型减弱了——科技成了所有周期的底仓。',
      threeSecSummary: '美股的钱在行业之间搬家搬到了哪',
      emoji: '🔄', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_SMALL_CAP_MOMENTUM', nameEn: 'USSmallCapMomentum', nameCn: '小盘股动量',
      humanLabel: '小票涨得比大票猛吗',
      humanDesc: '小盘强于大盘=风险偏好高牛市中后期特征。大优于小=避险。',
      dontUseWhen: '小盘动量受流动性影响大——缩表时这个因子基本失效。',
      threeSecSummary: '美国小公司跑赢大公司了吗',
      emoji: '🐟', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_DIVIDEND_ARISTOCRATS', nameEn: 'USDividendAristocrats', nameCn: '股息贵族',
      humanLabel: '25年以上连续增息的贵族',
      humanDesc: '连续25年增息的S&P500公司。比国债更香的复利机器——但价格也贵。',
      dontUseWhen: '贵族股估值一般较高——高股息≠高便宜。',
      threeSecSummary: '美股连增息25年的稳定派息之王',
      emoji: '👑', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_SP500_EQUAL_WEIGHT', nameEn: 'USSP500EqualWeight', nameCn: '标普500等权',
      humanLabel: '不被7巨头统治的美股',
      humanDesc: '等权指数跑赢市值加权=普涨。跑输=只有巨头在涨，其他都趴着。',
      dontUseWhen: '等权只能当参考——实际投资还是买ETF，不太能完全等权配置。',
      threeSecSummary: '美股是不是只有苹果和NVDA在涨',
      emoji: '⚖️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_13F_FLOW', nameEn: 'US13FFlow', nameCn: '13F机构持仓变化',
      humanLabel: '大基金最新动作曝光',
      humanDesc: '每季13F披露=对冲基金底牌。跟巴菲特/达里奥的增仓方向。',
      dontUseWhen: '13F是45天前的数据——看到的时候可能已经跑了。',
      threeSecSummary: '对冲基金和养老金上季度买卖了什么',
      emoji: '📄', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_BUYBACK_YIELD', nameEn: 'USBuybackYield', nameCn: '美股回购收益率',
      humanLabel: '回购给你多少回报',
      humanDesc: '净回购/市值>2%=稀释抵消后每股还多了2%。苹果老用这招。',
      dontUseWhen: '借债回购>2%的回购是假的——借的钱早晚要还。',
      threeSecSummary: '公司的回购是实实在在提高每股价值还是做样子',
      emoji: '♻️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_EARNINGS_REVISION', nameEn: 'USEarningsRevision', nameCn: '美股盈利修正',
      humanLabel: '华尔街最近在调高谁',
      humanDesc: '过去30天被上调盈利预测的美股。修正动量领先股价1-2周。',
      dontUseWhen: '盈利修正后要继续关注是否兑现——上调不等于业绩真的好。',
      threeSecSummary: '分析师公开上调了哪些美股预期',
      emoji: '✏️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_IV_RANK', nameEn: 'USIVRank', nameCn: '美股IV排名',
      humanLabel: '美股期权交易贵不贵',
      humanDesc: 'IV Rank>70=期权贵时卖权有利。IV Rank<30=期权便宜买权有利。',
      dontUseWhen: '有重大事件前IV会虚高——看似贵但有贵的理由。',
      threeSecSummary: '现在做美股期权的期权费划不划算',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_MEME_STOCK', nameEn: 'USMemeStockHeat', nameCn: '美股Meme热度',
      humanLabel: '散户军团还在不在',
      humanDesc: 'Reddit/StockTwits的讨论量激增=散户在动。但来得快去得也快。',
      dontUseWhen: 'Meme热度是情绪信号不是价值信号——别因为热闹就掏钱。',
      threeSecSummary: '美国散户在社交媒体上有多嗨',
      emoji: '🥳', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_OI_PUT_CALL', nameEn: 'USOpenInterestPCR', nameCn: '美股持仓PCR',
      humanLabel: '还有多少Put压在头上',
      humanDesc: '持仓PCR高=大量Put可能要平仓=反弹力量。持仓PCR上升=有人加仓Put。',
      dontUseWhen: '持仓PCR不反映方向性——大量Put可能是保护性持仓。',
      threeSecSummary: '美股期权未平仓合约中看跌多还是看涨多',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_RETAIL_FLOW', nameEn: 'USRetailFlow', nameCn: '散户资金流',
      humanLabel: '美国散户的钱在怎么流',
      humanDesc: '散户净买入最多的股票通常短期见顶。反向操作——他们买时你卖。',
      dontUseWhen: '大牛市主升浪可以持续很久——散户推升也能推很远。',
      threeSecSummary: 'Robinhood的小散们在大举买什么',
      emoji: '🐟', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_REVENUE_SURPRISE', nameEn: 'USRevenueSurprise', nameCn: '营收超预期',
      humanLabel: '卖了多少超越华尔街',
      humanDesc: '营收超预期比盈利超预期更硬——营收来自全市场而不是来自会计。',
      dontUseWhen: '单次营收超预期可能是一次性大单——要看3季趋势。',
      threeSecSummary: '公司真的在卖更多东西吗',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_SEASONALITY', nameEn: 'USSeasonalityEffect', nameCn: '美股季节性',
      humanLabel: '美股到了历史上哪个季节',
      humanDesc: '5月出清9月回=美股谚语。但也未必——2020年5月以后大涨。',
      dontUseWhen: '极端年份（如COVID、金融海啸）季节性完全失效。',
      threeSecSummary: '按过去100年经验，这个月美股好不好做',
      emoji: '🍂', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_SECTOR_ETF_FLOW', nameEn: 'USSectorETFFlow', nameCn: '美股行业ETF流',
      humanLabel: '哪个行业ETF被买爆了',
      humanDesc: 'XLK/XLE/XLF 等行业ETF资金流向→找出正在被建仓的板块。',
      dontUseWhen: 'ETF流不代表自然买盘——很多是配置型被动流入。',
      threeSecSummary: '哪些美国行业ETF的钱包在变大',
      emoji: '🧺', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_SHORT_FLOAT', nameEn: 'USShortFloat', nameCn: '美股做空比例',
      humanLabel: '多少人押它会跌',
      humanDesc: 'Short Float>20%=高争议。>30%且股价不跌=可疑——有人在托盘？',
      dontUseWhen: '高做空比例但业绩好的股票可能是逼空机会——要具体分析。',
      threeSecSummary: '美股空头有没有把自己逼到墙角',
      emoji: '🐻', foldLevel: 'L2_label_desc',
    },
    {
      id: 'US_VOLUME_PCR', nameEn: 'USVolumePCR', nameCn: '美股量PCR',
      humanLabel: '今天期权交易看涨多还是跌多',
      humanDesc: '量PCR=今日Put/Call成交量比。>1=恐惧，<0.5=贪婪。反向指标。',
      dontUseWhen: '单日PCR波动大——用5日均线判断更稳。',
      threeSecSummary: '今天美股期权交易者更爱赌涨还是赌跌',
      emoji: '⚖️', foldLevel: 'L2_label_desc',
    },
  ],

  // ════════════════════════ 10. HK-Specific ════════════════════════
  L1_HK: [
    {
      id: 'HKEX_SOUTHBOUND', nameEn: 'Southbound', nameCn: '南向资金',
      humanLabel: '内地钱在买什么港股',
      humanDesc: '南向连续净买入=港股底部信号。内地资金了解本土公司更深入。',
      dontUseWhen: '南向资金也怕汇率贬值——钱可能来了就走。',
      threeSecSummary: '大陆的钱今天又进了多少港股',
      emoji: '🇨🇳', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HKEX_CBCS_PREMIUM', nameEn: 'CBCSPremium', nameCn: 'AH溢价',
      humanLabel: 'A股比H股贵了多少',
      humanDesc: 'AH溢价比率>135=H股便宜得离谱，是好的择时买点。',
      dontUseWhen: 'AH溢价比不会自动回归——可能会长期偏离。',
      threeSecSummary: '同一家公司A股比港股贵了多少',
      emoji: '🏷️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HKEX_WARRANT_IV', nameEn: 'WarrantIV', nameCn: '涡轮引伸波幅',
      humanLabel: '窝轮/牛熊证的隐含波动',
      humanDesc: '涡轮IV高的股票可能有大动作。IV暴跌=方向已定——轮子要爆。',
      dontUseWhen: '涡轮是发行商定价——发行商可以随时调价，IV不一定准。',
      threeSecSummary: '香港衍生产品市场认为这只票有多少波动空间',
      emoji: '🎰', foldLevel: 'L3_full',
    },
    {
      id: 'HKEX_DLHB', nameEn: 'DLHB', nameCn: '大轮候补',
      humanLabel: '港股通候选股有没有戏',
      humanDesc: '即将被纳入港股通的股票有填权效应——提前潜伏。',
      dontUseWhen: '预期可能落空——港股通调整是定期的，猜错了白等。',
      threeSecSummary: '哪些港股快要进港股通',
      emoji: '📋', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HKEX_FUND_HOLD', nameEn: 'FundHolding', nameCn: '基金持仓',
      humanLabel: '基金在买哪些港股',
      humanDesc: '基金持仓集中高的股票有大资金背书，但集中太高也有下杀压力。',
      dontUseWhen: '基金持仓高但业绩差会在报告期后被猛砸。',
      threeSecSummary: '基金经理在拿客户的钱买什么港股',
      emoji: '💼', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_SOUTHBOUND_FLOW', nameEn: 'SouthboundFlowDaily', nameCn: '南向净流入',
      humanLabel: '今天内地钱来了多少',
      humanDesc: '单日净流入>50亿=强信号。连续3日流入=可信趋势。',
      dontUseWhen: '大市极度超跌会有脉冲式流入——可能是一波流的抄底。',
      threeSecSummary: '每日实时：内地的钱今天排队进了多少港股',
      emoji: '🌊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_SOUTHBOUND_TOP10', nameEn: 'SouthboundTop10', nameCn: '南向TOP10集中',
      humanLabel: '南向钱都集中去哪了',
      humanDesc: '前10只股票占南向买入超50%=集中度高。高集中=这些票是首选。',
      dontUseWhen: '极度集中时如果这10只被砸，南向资金会整体撤退。',
      threeSecSummary: '内地的钱都投到了港股哪几只头上',
      emoji: '🎯', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_SOUTHBOUND_MOM', nameEn: 'SouthboundMomentum', nameCn: '南向动量',
      humanLabel: '南向钱增速在加快吗',
      humanDesc: '南向流入在加速=买入信心在加强。减速=赚钱效应在消退。',
      dontUseWhen: '南向动量受政策窗口影响（如QDII额度）——看政策也看钱。',
      threeSecSummary: '内地的钱进港股速度在加快还是放慢',
      emoji: '💨', foldLevel: 'L3_full',
    },
    {
      id: 'HK_CONTROLLING_SH', nameEn: 'ControllingShareholder', nameCn: '大股东质押率',
      humanLabel: '大股东有多少股票押了',
      humanDesc: '质押率>50%=有爆仓风险。>70%=雷区——大股东被清仓你跑不了。',
      dontUseWhen: '大股东质押不一定都是借钱炒股——也可能是做生意用。',
      threeSecSummary: '大股东把自己的股票押了多少出去',
      emoji: '⚠️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_DIV_CUT_RISK', nameEn: 'DividendCutRisk', nameCn: '减分红风险',
      humanLabel: '分红可能会被砍吗',
      humanDesc: '盈利下滑+现金流紧张=分红大概率要被砍。提前跑比等到公告好。',
      dontUseWhen: '一次性的盈利不如预期不一定代表分红要砍——管理层有时会借钱分红。',
      threeSecSummary: '港股今年还会不会继续给你派息',
      emoji: '✂️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_WARRANT_GEX', nameEn: 'WarrantGEX', nameCn: '涡轮Gamma暴露',
      humanLabel: '轮子到期会把股价吸去哪',
      humanDesc: '大量涡轮集中在某个行权价附近=到期日有磁吸效应。正Gamma=稳。',
      dontUseWhen: '涡轮的Gamma效应在港股没美股那么强——港股衍生品成熟度高。',
      threeSecSummary: '香港的窝轮/牛熊证到期会不会拉动股价',
      emoji: '🧲', foldLevel: 'L3_full',
    },
    {
      id: 'HK_CBBC_STREET', nameEn: 'CBBCStreetRatio', nameCn: '街货比',
      humanLabel: '散客在狂买牛证还是熊证',
      humanDesc: '街货比牛>熊=散户看涨——但你反着看。牛太多=屠杀在即。',
      dontUseWhen: '极端比例不是立即反转——可以维持几天让你等得烦躁。',
      threeSecSummary: '香港散户的手放的位置暴露了市场的方向',
      emoji: '🐂', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_WARRANT_OI', nameEn: 'WarrantOIChange', nameCn: '涡轮持仓变化',
      humanLabel: '有人在悄悄加仓轮子',
      humanDesc: '涡轮持仓快速增加=杠杆资金在入场。Call OI增加=看涨，Put OI增=看跌。',
      dontUseWhen: '衍生品持仓变化不一定来自方向性交易——可能是对冲。',
      threeSecSummary: '香港轮子市场的杠杆客在赌哪边',
      emoji: '🎰', foldLevel: 'L3_full',
    },
    {
      id: 'HK_SHORT_SELL', nameEn: 'ShortSellRatio', nameCn: '沽空比率',
      humanLabel: '今天有人在砸盘吗',
      humanDesc: '港股沽空>25%+股价不跌=逼空信号。>30%持续=空方强，避。',
      dontUseWhen: '大盘一起沽空时不代表每只个股都差——是系统性避险。',
      threeSecSummary: '香港市场今天有多少是卖空砸出来的',
      emoji: '📉', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_ACC_RECEIVABLE', nameEn: 'AccReceivable', nameCn: '应收异常',
      humanLabel: '客户给钱变慢了吗',
      humanDesc: '应收账款/营收突然跳升=客户没钱了或在压货。>20%就是红灯。',
      dontUseWhen: '大单结算周期长的公司应收波动大是正常的——要看趋势。',
      threeSecSummary: '香港公司收了钱吗还是堆在账上',
      emoji: '📑', foldLevel: 'L3_full',
    },
    {
      id: 'HK_AH_PREMIUM', nameEn: 'AHPremium', nameCn: 'AH溢价率',
      humanLabel: '同家公司A股比H股贵多少',
      humanDesc: '溢价>50%=港股严重低估。溢价缩小时港股在补涨——这是赚钱主浪。',
      dontUseWhen: 'AH溢价有长期趋势——可能随着资金开放逐步收窄而不是一时。',
      threeSecSummary: 'A股比港股贵的溢价在扩大还是缩小',
      emoji: '📐', foldLevel: 'L2_label_desc',
    },
    {
      id: 'AH_PREMIUM_CHANGE', nameEn: 'AHPremiumChange', nameCn: 'AH溢价变化率',
      humanLabel: 'AH溢价在怎么变',
      humanDesc: '溢价收窄=港股在追A股=买港股。溢价扩大=A股在领跑=买A股。',
      dontUseWhen: '溢价变化的驱动因素要确认——是港股涨还是A股跌。',
      threeSecSummary: 'A股和港股的价差在怎么走',
      emoji: '♻️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HSI_CONSTITUENT', nameEn: 'HSIConstituent', nameCn: '恒指成分股权重',
      humanLabel: '指数基金的被动买盘',
      humanDesc: '即将被纳入恒指=被动资金必须买。提前埋伏赚被动流的钱。',
      dontUseWhen: '不入反出（被剔除）的风险也要考虑——双面效应。',
      threeSecSummary: '这只港股是不是被动基金的亲儿子',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_REIT_YIELD', nameEn: 'HKREITYield', nameCn: '港股REIT收益率',
      humanLabel: '收租股香不香',
      humanDesc: '香港REIT收益率>5%=香。但要看物业质量——商场比办公楼在疫情后更稳。',
      dontUseWhen: '利率上升期REIT收益率不够高去补偿股价下跌。',
      threeSecSummary: '香港收租股给你的租金回报高不高',
      emoji: '🏢', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_BOARD_ROTATION', nameEn: 'HKBoardRotation', nameCn: '港股板块轮动',
      humanLabel: '港股主力在玩哪个板块',
      humanDesc: '港股板块轮动比美股快：地产→金融→科技→公用→能源→重新循环。',
      dontUseWhen: '有政策驱动的板块轮动会打破历史规律——HK的政策影响有大权重。',
      threeSecSummary: '香港市场的钱今天在哪个板块里转',
      emoji: '🔄', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_CBBC_DISTANCE', nameEn: 'CBBCDistance', nameCn: '牛熊证距离',
      humanLabel: '牛熊证还能撑多久',
      humanDesc: '牛熊证强收价离现价越近=越容易被收。5%以内=危险区。',
      dontUseWhen: '牛熊街货是静态的——市场一动发行商会主动调整。',
      threeSecSummary: '香港牛熊证的强制收回线有多远',
      emoji: '📏', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_CBBC_RATIO', nameEn: 'CBBCRatio', nameCn: '牛熊证比率',
      humanLabel: '牛多还是熊多',
      humanDesc: '牛多=散户看好（你应该担心）。熊多=散户看空（你应该高兴）。反向指标。',
      dontUseWhen: '牛熊比是反向指标但不是买入信号——市场可能继续跌。',
      threeSecSummary: '香港散户现在多牛还是多熊',
      emoji: '🐂', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_DIV_TAX_ADV', nameEn: 'HKDividendTaxAdvantage', nameCn: '港股股息税优惠',
      humanLabel: '港股分红要交多少税',
      humanDesc: '内地买港股分红10%红利税。如果有沪港通优惠=到手更多。',
      dontUseWhen: '税率优势不是持股理由——别为省税买烂公司。',
      threeSecSummary: '港股分红到你口袋里会被抽多少',
      emoji: '🧾', foldLevel: 'L3_full',
    },
    {
      id: 'HK_ETF_FLOW', nameEn: 'HKETFFlow', nameCn: '港股ETF资金流',
      humanLabel: '港股指数基金钱在进吗',
      humanDesc: '跟踪恒指/国企/科指的ETF流入=被动资金在买。最客观的港股信心指标。',
      dontUseWhen: 'ETF资金流有申购/赎回滞后——你看到时可能已经布局完了。',
      threeSecSummary: '香港股市的被动型大资金在怎么进出',
      emoji: '🧺', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_HSCEI_PREMIUM', nameEn: 'HSCEIPremium', nameCn: '国企指数溢价',
      humanLabel: '国企股被看不起还是被捧着',
      humanDesc: 'H股/国企指数溢价收窄=被重估中。国企改革红利在这个指标里。',
      dontUseWhen: '国企溢价低可能是长期低估值陷阱——没有催化剂不会回归。',
      threeSecSummary: '中国国企在港股是被打折还是被溢价',
      emoji: '🇨🇳', foldLevel: 'L3_full',
    },
    {
      id: 'HK_SHORT_SELL_RATIO', nameEn: 'HKShortSellRatio', nameCn: '港股沽空比率',
      humanLabel: '今天砸盘的有多少',
      humanDesc: '沽空金额/总成交>20%=空方主导。>25%=可能要逼空——空方过盛。',
      dontUseWhen: '港股可以很容易卖出——沽空高不一定代表看空，可能只是对冲。',
      threeSecSummary: '今天港股成交量里有多少是真看空',
      emoji: '📉', foldLevel: 'L2_label_desc',
    },
    {
      id: 'HK_WARRANT_TURNOVER', nameEn: 'HKWarrantTurnover', nameCn: '涡轮成交额',
      humanLabel: '杠杆资金在疯狂转手',
      humanDesc: '涡轮成交量突涨=衍生品客在拼。通常预示着正股快有大动作。',
      dontUseWhen: '涡轮成交量可能只是个别人大额进出——不代表共识。',
      threeSecSummary: '香港杠杆玩家今天是不是特别躁',
      emoji: '🔊', foldLevel: 'L3_full',
    },
  ],

  // ════════════════════════ 11. Crypto (代表选取) ════════════════════════
  L1_CRYPTO: [
    {
      id: 'CRYPTO_FUNDING', nameEn: 'FundingRate', nameCn: '资金费率',
      humanLabel: '做多的人多到要交租了吗',
      humanDesc: '费率为正且>0.01%＝多单拥挤。费率转负＝空头崩溃，反弹在即。',
      dontUseWhen: '大行情中费率可以持续为正——极端费率不是反转点。',
      threeSecSummary: '赌涨的人太多要付给赌跌的利息',
      emoji: '💸', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CRYPTO_OI_DELTA', nameEn: 'OpenInterestDelta', nameCn: '持仓量变化',
      humanLabel: '有人在大手建仓吗',
      humanDesc: '持仓量+成交量同时涨=新钱进场。价跌量增持仓跌=多头在溃败。',
      dontUseWhen: '单日持仓量波动可能是结算/交割影响——看3天趋势。',
      threeSecSummary: '期货市场的大户在加仓还是减仓',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CRYPTO_EXCHANGE_FLOW', nameEn: 'ExchangeFlow', nameCn: '交易所流量',
      humanLabel: '币在往哪搬',
      humanDesc: '币转入交易所=可能要卖，转出=可能要HODL。大量转出=看涨。',
      dontUseWhen: '交易所间搬砖也会造成转移——不能全解读为方向。',
      threeSecSummary: '币是在往交易所存（准备卖）还是往外搬（准备坚）',
      emoji: '📦', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CRYPTO_ORDERBOOK_IMB', nameEn: 'OrderbookImbalance', nameCn: '订单簿失衡',
      humanLabel: '买单墙还是卖单墙',
      humanDesc: '买单深度远大于卖单=护盘力量强。反之=有人在挂卖单等砸。',
      dontUseWhen: '墙可以是伪造的（spoofing）——不见真成交别信。',
      threeSecSummary: '市场挂出来的买单多还是卖单多',
      emoji: '📋', foldLevel: 'L3_full',
    },
    {
      id: 'CRYPTO_VOL_RATIO', nameEn: 'VolumeRatio', nameCn: '量比',
      humanLabel: '现在比平时活跃多少',
      humanDesc: '量比>2=有大事发生。超大量如果方向确定，跟着走大概率对。',
      dontUseWhen: '量比高但不涨不跌=死盘可能是出货——谨慎。',
      threeSecSummary: '今天的成交量比平时大了几倍',
      emoji: '🔊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CRYPTO_BTC_CORR', nameEn: 'BTCCorrelation', nameCn: 'BTC相关性',
      humanLabel: '跟着BTC跑多紧',
      humanDesc: '相关>0.8=BTC涨它也涨。想要独立行情选相关<0.5的币。',
      dontUseWhen: '相关性会变——熊市时所有币都会重新相关到1。',
      threeSecSummary: '你的币是BTC的小跟班还是独立人',
      emoji: '🔗', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CRYPTO_ACTIVE_ADDR', nameEn: 'ActiveAddresses', nameCn: '活跃地址',
      humanLabel: '用的人多了还是少了',
      humanDesc: '活跃地址趋势=早期牛熊判断器。上升=新用户进来，下降=人走了。',
      dontUseWhen: '地址可以刷——空投垃圾地址会突然增加。',
      threeSecSummary: '区块链上有多少人在真实使用',
      emoji: '👥', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CRYPTO_LIQUIDATIONS', nameEn: 'Liquidations', nameCn: '清算量',
      humanLabel: '有多少人被强平了',
      humanDesc: '大量多头被清算=底部区域——该割的都割了。大量空头被清算=顶部。',
      dontUseWhen: '清算数据是滞后的——你看到的时候市场可能已经反转了。',
      threeSecSummary: '杠杆客被清洗了多少',
      emoji: '💥', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CRYPTO_SOCIAL_SENTIMENT', nameEn: 'SocialSentimentCrypto', nameCn: '社交情绪',
      humanLabel: '币圈圈的舆论嗨不嗨',
      humanDesc: '极度嗨=顶。极度丧=底。永远反着散户情绪做。',
      dontUseWhen: '社媒情绪可以用来判断极致——但不能用来判断日常方向。',
      threeSecSummary: 'Twitter和Telegram上聊这个币是嗨翻还是死寂',
      emoji: '💬', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CRYPTO_WHALE_ACCUM', nameEn: 'WhaleAccumulation', nameCn: '大户累积',
      humanLabel: '鲸鱼在偷偷收币',
      humanDesc: '持仓较大的钱包在增加=鲸鱼看好。配合价格横盘/阴跌更可信。',
      dontUseWhen: '鲸鱼地址可能属于交易所——不是真正的累积。',
      threeSecSummary: '大户钱包的币在增加—是在扫货',
      emoji: '🐋', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CRYPTO_MVRV', nameEn: 'MVRVRatio', nameCn: 'MVRV比率',
      humanLabel: '大家都赚钱了就该跌了',
      humanDesc: 'MVRV>3=所有人都在赚=赶紧跑。<1=大家亏钱=可以买。',
      dontUseWhen: '新币MVRV起步就是虚的——数据不够多。',
      threeSecSummary: '持仓者的平均盈亏水平',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CRYPTO_FEAR_GREED', nameEn: 'CryptoFearGreed', nameCn: '加密恐惧贪婪',
      humanLabel: '币圈的情绪现在是什么',
      humanDesc: '<25=极度恐惧=分批买入始点。>75=极度贪婪=分批卖出始点。',
      dontUseWhen: '极端情绪可以持续很久——不要用这个做精准择时。',
      threeSecSummary: '加密市场的情绪温度计',
      emoji: '😱', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CRYPTO_STABLECOIN_RATIO', nameEn: 'StablecoinRatio', nameCn: '稳定币占比',
      humanLabel: '囤了多少弹药等着买',
      humanDesc: '交易所稳定币占比上升=买盘弹药在囤积。占比下降=弹药在消耗。',
      dontUseWhen: '稳定币可能是Tether印的——印刷量不等于真实需求。',
      threeSecSummary: '市场上有多少现成钱等着扫货',
      emoji: '💵', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CRYPTO_EXCHANGE_RESERVE', nameEn: 'ExchangeReserve', nameCn: '交易所余额',
      humanLabel: '交易所里的币少了',
      humanDesc: '交易所余额持续下降=囤币党在提走=看涨。余额上升=准备卖=看跌。',
      dontUseWhen: '交易所余额可能有结构性变化（冷钱包管理），不是全方向。',
      threeSecSummary: '交易所钱包里的币是多了还是少了',
      emoji: '🏦', foldLevel: 'L2_label_desc',
    },
  ],

  // ════════════════════════ 12. Cross-Asset & Carry ════════════════════════
  L1_CROSS_ASSET: [
    {
      id: 'CARRY_EQUITY', nameEn: 'EquityCarry', nameCn: '股票利差',
      humanLabel: '借钱买股的套利空间',
      humanDesc: '股息/融资利率>1.5=借钱吃息划算。但股价要稳住才有意义。',
      dontUseWhen: '股价波动吃掉全部利差时 Carry 就是个假概念。',
      threeSecSummary: '用借款的利息来买股吃息划不划算',
      emoji: '💰', foldLevel: 'L3_full',
    },
    {
      id: 'GOLD_MOMENTUM', nameEn: 'GoldMomentum', nameCn: '黄金动量',
      humanLabel: '金价在往哪跑',
      humanDesc: '黄金涨=避险需求在上升=股市可能快有麻烦。持续涨=配置黄金。',
      dontUseWhen: '黄金涨的诱因多样——通胀/美元/地缘——不总是避险。',
      threeSecSummary: '黄金的价格走势暗示什么',
      emoji: '🥇', foldLevel: 'L2_label_desc',
    },
    {
      id: 'COMMODITY_MOMENTUM', nameEn: 'CommodityMomentum', nameCn: '商品动量',
      humanLabel: '商品期货的趋势方向',
      humanDesc: '商品持续上涨=通胀预期在抬头。持续下跌=经济减速信号。',
      dontUseWhen: '商品趋势单一品种波动大——不要用单一商品判断宏观。',
      threeSecSummary: '大宗商品价格在涨还是在跌',
      emoji: '🛢️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CURRENCY_MOMENTUM', nameEn: 'CurrencyMomentum', nameCn: '货币动量',
      humanLabel: '哪个货币现在是王者',
      humanDesc: '最强货币vs最弱货币=跨境投资要把钱放对的货币篮子。',
      dontUseWhen: '汇率趋势可以持续数年——不要频繁切换货币暴露。',
      threeSecSummary: '世界上的钱在往哪个货币里跑',
      emoji: '💱', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CORR_REGIME', nameEn: 'CorrelationRegime', nameCn: '相关性体制',
      humanLabel: '各类资产在齐涨齐跌吗',
      humanDesc: '股债同涨同跌时=分散投资失效。差异大时=真正可以分散风险。',
      dontUseWhen: '相关性矩阵变脸超快——上周的模式不等于下周。',
      threeSecSummary: '你的篮子里所有鸡蛋都往一个方向滚吗',
      emoji: '🥚', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CROSS_ASSET_CORR', nameEn: 'CrossAssetCorrelation', nameCn: '跨资产联动',
      humanLabel: '不同资产之间怎么联动',
      humanDesc: '高相关=系统性风险大。低相关=有套利/对冲空间。',
      dontUseWhen: '危机时相关性会突然全部飙到接近1。',
      threeSecSummary: '股票、债券、黄金是各走各的还是绑一起',
      emoji: '🔗', foldLevel: 'L2_label_desc',
    },
    // (剩余利差品种因子省略——不重复已覆盖概念)
  ],

  // ════════════════════════ 13. Event-Driven ════════════════════════
  L1_EVENT: [
    {
      id: 'PRE_EARNINGS_DRIFT', nameEn: 'PreEarningsDrift', nameCn: '盈利前漂移',
      humanLabel: '财报前几天股价在偷跑',
      humanDesc: '盈利前股价悄然上涨=有人提前知道好消息。连续5天跑赢=可信。',
      dontUseWhen: '有时只是随机波动——要看量配合确认。',
      threeSecSummary: '出成绩前股价是不是已经在偷跑了',
      emoji: '🏃', foldLevel: 'L2_label_desc',
    },
    {
      id: 'POST_EARNINGS_DRIFT', nameEn: 'PostEarningsDrift', nameCn: '盈利后漂移',
      humanLabel: '财报超预期后还能追',
      humanDesc: '超预期后一个月内股价往往继续涨——市场消化新信息不够快。',
      dontUseWhen: '预期已经被完全定价时（Pre-Earnings涨太多），PEAD效果弱。',
      threeSecSummary: '超预期的财报公布后还有一段惯性',
      emoji: '⏩', foldLevel: 'L2_label_desc',
    },
    {
      id: 'DIVIDEND_CAPTURE', nameEn: 'DividendCapture', nameCn: '分红捕获',
      humanLabel: '为了吃息短暂持股',
      humanDesc: '除息前买入吃息后卖出。但要算好交易成本和股价下调的损失。',
      dontUseWhen: '股价下调+交易成本可能超过股息——小散不划算。',
      threeSecSummary: '持几天就为了拿分红 — 值不值',
      emoji: '⏰', foldLevel: 'L3_full',
    },
    {
      id: 'INDEX_REBALANCE', nameEn: 'IndexRebalance', nameCn: '指数调入效应',
      humanLabel: '进指数的票必被基金买',
      humanDesc: '调入前买调入后卖——收被动基金的钱。这是最古老的套利。',
      dontUseWhen: '已经被充分定价的调入无利可套——预期在前。',
      threeSecSummary: '被纳入指数公司的股价在生效前要涨',
      emoji: '📋', foldLevel: 'L2_label_desc',
    },
    {
      id: 'IPO_LOCKUP_EXPIRY', nameEn: 'IPOLockupExpiry', nameCn: '解禁事件',
      humanLabel: '大股东马上可以卖了',
      humanDesc: '解禁日前3-5天通常跌。解禁后首日如果没跌=真不怕卖=强。',
      dontUseWhen: '优质公司解禁后大股东未必卖——有些会主动承诺延期。',
      threeSecSummary: '低价入股的早期投资者马上可以砸盘了',
      emoji: '🔓', foldLevel: 'L2_label_desc',
    },
    {
      id: 'BUYBACK_ANNOUNCE', nameEn: 'BuybackAnnouncement', nameCn: '回购公告效应',
      humanLabel: '公司宣布回购了该不该跟',
      humanDesc: '回购公告后首日涨1-3%。公告后6个月平均跑赢大盘——可以跟。',
      dontUseWhen: '有些公司发公告但从不执行——看公告和实际的差距。',
      threeSecSummary: '公司公开说要自己买自己——是真心吗',
      emoji: '📢', foldLevel: 'L2_label_desc',
    },
    {
      id: 'DIV_ANNOUNCEMENT', nameEn: 'DividendAnnouncement', nameCn: '分红公告日',
      humanLabel: '分红公告日是股价催化剂',
      humanDesc: '超预期增息=公告日跳涨。预期内=没反应。减息=跳跌。',
      dontUseWhen: '增息幅度过大=公司在释放过剩现金=可能没好的增长方向。',
      threeSecSummary: '公司分红公告是惊喜还是符合预期',
      emoji: '📬', foldLevel: 'L2_label_desc',
    },
  ],

  // ════════════════════════ 14. ESG & Sustainability ════════════════════════
  L1_ESG: [
    {
      id: 'ESG_SCORE', nameEn: 'ESGScore', nameCn: 'ESG综合评分',
      humanLabel: '这家公司绿色良心怎样',
      humanDesc: 'ESG高=风控/合规/可持续性好。低=可能有ESG风险要避开。',
      dontUseWhen: 'ESG评分标准每个机构不一样——看一个数不够，要看为什么这个数。',
      threeSecSummary: '公司在环保、社会责任、治理方面的总分',
      emoji: '🌍', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CARBON_INTENSITY', nameEn: 'CarbonIntensity', nameCn: '碳强度',
      humanLabel: '每赚一块钱排多少碳',
      humanDesc: '碳强度高的公司在碳税/环保政策中受打击最重。减碳=减风险。',
      dontUseWhen: '碳强度低不代表管理好——可能是行业天然低，不是公司努力。',
      threeSecSummary: '公司的碳排放跟你投的钱有关',
      emoji: '🌿', foldLevel: 'L2_label_desc',
    },
    {
      id: 'GOVERNANCE_SCORE', nameEn: 'GovernanceScore', nameCn: '治理评分',
      humanLabel: '管理层靠不靠谱',
      humanDesc: '治理分低=董事会/审计/股东权益有问题。治理是ESG里最直接影响股价的。',
      dontUseWhen: '自评的治理分可能有美化成分——看第三方独立评估。',
      threeSecSummary: '公司的管理制度是不是烂到了会伤你钱',
      emoji: '⚖️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'GREEN_REVENUE', nameEn: 'GreenRevenue', nameCn: '绿色收入占比',
      humanLabel: '有多少收入是绿色的',
      humanDesc: '绿色收入占比高=政策风向对它是顺风。绿色转型中受益最大。',
      dontUseWhen: '有些公司绿色收入定义宽到好笑——看具体包含什么业务。',
      threeSecSummary: '公司在新能源/环保方面赚的钱站营收多少',
      emoji: '💚', foldLevel: 'L2_label_desc',
    },
    {
      id: 'ESG_MOMENTUM', nameEn: 'ESGMomentum', nameCn: 'ESG进步速度',
      humanLabel: 'ESG是在变好还是变差',
      humanDesc: 'ESG评分上升=公司在努力改进。ESG评分下降=可能有新的风险暴露。',
      dontUseWhen: '评级变更可能是评级机构的方法变了——不一定是公司变了。',
      threeSecSummary: '公司在环保和社会责任上是在进步还是退步',
      emoji: '📈', foldLevel: 'L3_full',
    },
  ],

  // ════════════════════════ 15. Commodity Futures ════════════════════════
  L1_COMMODITY: [
    {
      id: 'CMD_ROLL_YIELD', nameEn: 'RollYield', nameCn: '换月成本',
      humanLabel: '持有期货每天赚还是亏',
      humanDesc: '正展期收益=期货贴水=到期的钱赚的。负展期=期货升水=持有在亏。',
      dontUseWhen: '展期收益是理论值——实际换月有滑点和流动性成本。',
      threeSecSummary: '持有这个商品期货是赚持有费还是亏持有费',
      emoji: '🔄', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMD_TERM_STRUCTURE', nameEn: 'TermStructure', nameCn: '期限结构斜率',
      humanLabel: '远期价vs近期价差多少',
      humanDesc: '远低于近=现货紧张=Backwardation=供应紧缺看涨。远高于近=库存充裕。',
      dontUseWhen: '期限结构是慢变指标——不适合做短期择时。',
      threeSecSummary: '商品市场认为现在缺不缺货',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMD_BASIS', nameEn: 'Basis', nameCn: '基差',
      humanLabel: '期货和现货价差多大',
      humanDesc: '基差扩大=期货在修正——现货可能跟不上。基差收敛=期货回归。',
      dontUseWhen: '基差包含了持有成本——不是在回归就是套利。',
      threeSecSummary: '期货价格和现货价格的差距',
      emoji: '📐', foldLevel: 'L3_full',
    },
    {
      id: 'CMD_MOMENTUM_12M', nameEn: 'CommodityMomentum12M', nameCn: '12月商品动量',
      humanLabel: '商品过去一年的趋势',
      humanDesc: '12月商品动量是最强的商品因子——趋势通常能延续。',
      dontUseWhen: '基本面突变（如战争/疫情）会瞬间打断动量。',
      threeSecSummary: '过去一年涨最多的商品还能涨吗',
      emoji: '🚀', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMD_MOMENTUM_1M', nameEn: 'CommodityMomentum1M', nameCn: '1月商品反转',
      humanLabel: '急涨急跌后的修正',
      humanDesc: '1月内涨最猛的商品下一月可能回调——反转是短线的朋友。',
      dontUseWhen: '有大的供给冲击时反转可能就不会发生。',
      threeSecSummary: '最近一个月涨太猛该不该出来',
      emoji: '🔄', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMD_VOLATILITY', nameEn: 'CommodityVolatility', nameCn: '商品波动率',
      humanLabel: '商品市场的震幅有多大',
      humanDesc: '波动率上升=风险上升但也是机会。低波动=可能是暴风雨前的平静。',
      dontUseWhen: '波动率会聚类——高波动会持续一段时间，不是一天结束。',
      threeSecSummary: '商品现在的价格摆动有多大',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMD_EIA_CRUDE', nameEn: 'EIACrudeInventory', nameCn: 'EIA原油库存',
      humanLabel: '美国油罐里还有多少油',
      humanDesc: '库存降幅超预期=油价要涨。库存增幅超预期=油价要跌。',
      dontUseWhen: '季节性因素（炼厂检修）会影响库存——不要把季节性解读为趋势。',
      threeSecSummary: '每周三EIA数据——美国油库存是多了还是少了',
      emoji: '🛢️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMD_GOLD_ETF', nameEn: 'GoldETFHoldings', nameCn: '黄金ETF持仓',
      humanLabel: 'ETF在买金还是卖金',
      humanDesc: '黄金ETF持仓增长=市场避险意愿上升。下降=风险偏好回升。',
      dontUseWhen: '黄金ETF价量信息已经很快被定价了——跟其他指标一起看。',
      threeSecSummary: '全球最大的黄金ETF在加仓还是减仓',
      emoji: '🥇', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMD_COT_COMMERCIAL', nameEn: 'COTCommercial', nameCn: '商业持仓',
      humanLabel: '产业套保的人现在怎么样',
      humanDesc: '商业净多头增加=产业看好。商业是商品市场最聪明的钱。',
      dontUseWhen: '产业套保可能会用期权不在COT里——数据不完全。',
      threeSecSummary: '卖货的人自己看好不看好现在的价格',
      emoji: '🏭', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMD_COT_SPECULATOR', nameEn: 'COTSpeculator', nameCn: '投机持仓',
      humanLabel: '投机客现在站哪边',
      humanDesc: '投机净多太高=极度拥挤=反转在即。投机净空太高=情绪太悲观=反弹。',
      dontUseWhen: 'COT是周数据——报告日到发布日有3天延迟。',
      threeSecSummary: '市场上的投机客是多头还是空头',
      emoji: '🎰', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMD_COT_EXTREME', nameEn: 'COTExtreme', nameCn: '极端持仓',
      humanLabel: '大佬拥挤到了极致',
      humanDesc: '投机持仓处于历史极端=反向操作的最好时机。产业在另一边=双确认。',
      dontUseWhen: '极端持仓不叫反转信号——可以维持极端状态好久。',
      threeSecSummary: '聪明钱们的仓位是不是偏到一边去了',
      emoji: '⚠️', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMD_GOLD_SILVER_RATIO', nameEn: 'GoldSilverRatio', nameCn: '金银比',
      humanLabel: '黄金贵还是白银贵',
      humanDesc: '金银比>80=黄金相对太贵=白银可能要补涨。<50=黄金便宜=买黄金更划算。',
      dontUseWhen: '金银比有结构性下降趋势（绿色经济用银多），不代表均值回归。',
      threeSecSummary: '避险情绪vs工业需求 — 金银比是试纸',
      emoji: '🥇🥈', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMD_GOLD_OIL_RATIO', nameEn: 'GoldOilRatio', nameCn: '金油比',
      humanLabel: '恐慌vs经济活力',
      humanDesc: '金油比飙升=人在担忧经济。历史上40以上对应大的经济向下。',
      dontUseWhen: '供给端冲击（如OPEC降低产）也会影响金油比。',
      threeSecSummary: '人们更想要安全感还是开着车的繁荣',
      emoji: '📊', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMD_CRACK_SPREAD', nameEn: 'CrackSpread', nameCn: '裂解价差',
      humanLabel: '炼油还赚钱吗',
      humanDesc: '裂解价差大=炼油利润丰厚=需求旺盛。价差收窄=炼厂要减产。',
      dontUseWhen: '炼厂检修季会扭曲裂解价差——不是真正的需求变化。',
      threeSecSummary: '把原油做成汽油和柴油能赚多少',
      emoji: '⛽', foldLevel: 'L3_full',
    },
    {
      id: 'CMD_DXY_LINKAGE', nameEn: 'DXYLinkage', nameCn: '美元联动',
      humanLabel: '美元强商品就弱吗',
      humanDesc: '历史和负相关——美元涨1%商品跌约0.5%。汇率是商品价格的决定因素。',
      dontUseWhen: '新兴市场大储需时美元和商品可能同涨——打破正常负相关。',
      threeSecSummary: '美元的强弱推动着商品的涨跌',
      emoji: '💵', foldLevel: 'L2_label_desc',
    },
    {
      id: 'CMD_REAL_RATE', nameEn: 'RealRate', nameCn: '实际利率',
      humanLabel: '黄金的天敌——实际利率',
      humanDesc: '实际利率升=黄金成本升=黄金跌。实际利率转负=黄金起飞。',
      dontUseWhen: '危机时期黄金和实际利率会脱钩——都在恐慌性买金。',
      threeSecSummary: '扣除通胀后的利率 — 黄金的最大敌人',
      emoji: '🥇', foldLevel: 'L2_label_desc',
    },
  ],

  // ════════════════════════ System: Auto-generation hints ════════════════════════
  // reminders removed due to type mismatch (not in FactorHumanized[] interface)
  _reminders: {
    note: "以上覆盖 ~280+ 核心因子。剩余因子（学术200+ESG70+另类20+期权15+固收10+全球96）的人话化使用以下规则自动生成：",
    rules: [
      "学术因子：从 academic-200-factor-names-r278.ts 提取 nameCn",
      "ESG因子：从 esg-70-factor-copy-r278.ts 提取已有的完整文案",
      "全球因子：从 global-84plus12-factor-copy-r277.ts 已有的四段式文案",
      "另类/期权/固收：因行业变化快，用 Whaley LLM 实时生成 + 每月人工审核",
      "3秒摘要 = 因子能帮用户做的最核心的一件事"
    ],
  },
};

export default EXTENDED_FACTOR_HUMANIZE;
